const PROJECT_KEY = "schola-stundenplan-projects-v1";
const PLAN_KEY = "schola-stoffverteilung-plans-v1";
const ACTIVE_KEY = "schola-stoffverteilung-calendar-id-v1";
const WEEKDAYS = ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"];
const $ = (id) => document.getElementById(id);
const elements = Object.fromEntries(["connectionView","connectionForm","calendarIdInput","availableCalendars","connectionStatus","workspace","projectName","changeCalendarButton","courseSearch","courseList","planMeta","planTitle","summaryCards","planRows","emptyPlan","addRowButton","settingsButton","settingsDialog","settingsForm","closeSettingsButton","frameworkInput","frameworkUrlInput","reserveInput","yearGoalInput","showHolidays","printButton","exportButton","saveState"].map((id)=>[id,$(id)]));
let projects = readJson(PROJECT_KEY, []);
let plans = readJson(PLAN_KEY, {});
let project = null;
let courses = [];
let activeCourseId = "";
let activeFilter = "all";

function readJson(key, fallback){try{return JSON.parse(localStorage.getItem(key)||"null")??fallback}catch{return fallback}}
function uid(prefix="row"){return globalThis.crypto?.randomUUID?.()||`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2)}`}
function esc(value){return String(value??"").replace(/[&<>"]/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[char]))}
function dateKey(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`}
function parseDate(value){const [y,m,d]=String(value).split("-").map(Number);return new Date(y,m-1,d)}
function formatDate(value){return new Intl.DateTimeFormat("de-DE",{day:"2-digit",month:"2-digit",year:"2-digit"}).format(parseDate(value))}
function isoWeek(value){const date=parseDate(value);date.setHours(0,0,0,0);date.setDate(date.getDate()+3-((date.getDay()+6)%7));const first=new Date(date.getFullYear(),0,4);return 1+Math.round(((date-first)/86400000-3+((first.getDay()+6)%7))/7)}
function save(){localStorage.setItem(PLAN_KEY,JSON.stringify(plans));elements.saveState.textContent="Gespeichert";clearTimeout(save.timer);save.timer=setTimeout(()=>elements.saveState.textContent="Lokal gespeichert",1000)}
function normalizeId(value){return String(value||"").trim().replace(/^SP1:/i,"")}
function getCatalog(p){return p.layers?.find((layer)=>layer.type==="classCatalog")||{grades:[],subjects:[]}}
function getScheduleLayer(p){return p.layers?.find((layer)=>layer.type==="schedules")||{schedules:[],versions:[]}}
function getHolidayLayer(p){return p.layers?.find((layer)=>layer.type==="holidays")||{entries:[]}}
function projectRange(p){const schools=getHolidayLayer(p).schools||[];const starts=schools.map(s=>s.periods?.schoolYear?.startDate).filter(Boolean).sort();const ends=schools.map(s=>s.periods?.schoolYear?.endDate).filter(Boolean).sort();return {start:p.calendarRange?.startDate||starts[0]||p.periods?.schoolYear?.startDate,end:p.calendarRange?.endDate||ends.at(-1)||p.periods?.schoolYear?.endDate}}
function classLabel(catalog,lesson){if(lesson.courseId){for(const subject of catalog.subjects||[]){const course=(subject.courses||[]).find(c=>c.id===lesson.courseId);if(course)return course.name||"Kurs"}}for(const grade of catalog.grades||[]){const entry=(grade.classes||[]).find(c=>c.id===lesson.classId);if(entry)return entry.name}return lesson.grade||"Ohne Klasse"}
function subjectLabel(catalog,lesson){return (catalog.subjects||[]).find(s=>s.id===lesson.subjectId)?.name||lesson.subject||"Fach"}
function buildCourses(p){const catalog=getCatalog(p);const layer=getScheduleLayer(p);const map=new Map();for(const schedule of layer.schedules||[]){for(const lesson of schedule.lessons||[]){const subject=subjectLabel(catalog,lesson);const group=classLabel(catalog,lesson);const target=lesson.courseId||lesson.classId||lesson.grade||"none";const key=`${lesson.subjectId||subject}|${target}`;if(!map.has(key))map.set(key,{id:key,subject,group,subjectId:lesson.subjectId||"",targetId:target,items:[]});map.get(key).items.push({schedule,lesson})}}return [...map.values()].sort((a,b)=>`${a.subject}${a.group}`.localeCompare(`${b.subject}${b.group}`,"de"))}
function holidayFor(schedule,value){return (getHolidayLayer(project).entries||[]).find(entry=>["school-holiday","public-holiday","school-free-day"].includes(entry.type)&&value>=entry.startDate&&value<=entry.endDate&&(!schedule.schoolId||entry.schoolId===schedule.schoolId||(entry.schoolIds||[]).includes(schedule.schoolId)))}
function suppressed(lesson,schedule,value){const sickness=project.layers?.find(l=>l.type==="sickness")?.entries||[];if(sickness.some(e=>value>=e.startDate&&value<=e.endDate))return true;const individual=project.layers?.find(l=>l.type==="individual");const appointments=project.layers?.find(l=>l.type==="appointments");const entries=[...(individual?.appliedEntries||individual?.entries||[]),...[individual,appointments].flatMap(l=>(l?.groups||[]).flatMap(g=>g.appointments||g.entries||[]))];return entries.some(e=>{if(!e.overridesLessons&&!e.overridesClassLessons)return false;const start=e.startDate||e.date,end=e.endDate||e.date;if(!start||value<start||value>end)return false;const targets=[...(e.classIds||[]),...(e.classGroups||[]).flatMap(g=>g.classIds||[])];if(targets.length&&lesson.classId&&!targets.includes(lesson.classId))return false;if(e.courseId&&lesson.courseId&&e.courseId!==lesson.courseId)return false;if(e.startTime&&e.endTime&&lesson.start&&lesson.end)return lesson.start<e.endTime&&lesson.end>e.startTime;return true})}
function activeOnDate(lesson,schedule,value){const form=lesson.teachingForm||(lesson.epochal?"epochal":"regular");if(form==="regular")return true;const school=(getHolidayLayer(project).schools||[]).find(s=>s.id===schedule.schoolId);const periods=school?.periods||project.periods;if(form==="abWeek"){const week=periods?.models?.alternatingWeeks?.weeks?.find(w=>value>=w.startDate&&value<=w.endDate);return !week||week.variant===(lesson.abWeek==="B"?"B":"A")}const half=periods?.models?.halves?.[lesson.epochHalf==="second"?"second":"first"];return !half?.startDate||!half?.endDate||(value>=half.startDate&&value<=half.endDate)}
function occurrenceRows(course){const layer=getScheduleLayer(project);const result=[];const seen=new Set();for(const item of course.items){const version=(layer.versions||[]).find(v=>v.id===item.schedule.versionId);const range=projectRange(project);const start=version?.validFrom||item.schedule.validFrom||range.start;const end=version?.validUntil||item.schedule.validUntil||range.end;if(!start||!end)continue;for(let date=parseDate(start),last=parseDate(end);date<=last;date.setDate(date.getDate()+1)){if(date.getDay()!==Number(item.lesson.day)%7)continue;const key=dateKey(date);if(!activeOnDate(item.lesson,item.schedule,key)||holidayFor(item.schedule,key)||suppressed(item.lesson,item.schedule,key))continue;const unique=`${key}|${item.lesson.start}|${item.lesson.end}`;if(seen.has(unique))continue;seen.add(unique);result.push({id:unique,date:key,start:item.lesson.start||"",end:item.lesson.end||"",room:item.lesson.room||"",color:item.lesson.color||"#bfd2e2"})}}return result.sort((a,b)=>`${a.date}${a.start}`.localeCompare(`${b.date}${b.start}`))}
function planFor(course){const key=`${project.id}|${course.id}`;plans[key]??={version:1,projectId:project.id,courseId:course.id,framework:"",frameworkUrl:"",reserve:10,yearGoal:"",entries:{},freeRows:[]};return plans[key]}
function entryFor(plan,row){return plan.entries[row.id]??={topic:"",competences:"",implementation:"",assessment:"",status:"open",notes:""}}
function renderAvailable(){elements.availableCalendars.replaceChildren();projects.forEach(p=>{const button=document.createElement("button");button.type="button";button.className="calendar-chip";button.innerHTML=`<strong>${esc(p.name||"Schuljahr")}</strong><small>${esc(`SP1:${p.id}`)}</small>`;button.onclick=()=>{elements.calendarIdInput.value=`SP1:${p.id}`;connect(`SP1:${p.id}`)};elements.availableCalendars.append(button)});if(!projects.length)elements.availableCalendars.innerHTML="<small>Noch kein lokales Stundenplan-Schuljahr gefunden.</small>"}
function connect(raw){projects=readJson(PROJECT_KEY,[]);const id=normalizeId(raw);project=projects.find(p=>p.id===id);if(!project){elements.connectionStatus.textContent="Diese Kalender-ID wurde im lokalen Stundenplan nicht gefunden.";return}localStorage.setItem(ACTIVE_KEY,`SP1:${id}`);courses=buildCourses(project);activeCourseId=courses[0]?.id||"";elements.connectionView.hidden=true;elements.workspace.hidden=false;elements.projectName.textContent=project.name||"Schuljahr";renderCourseList();renderPlan()}
function renderCourseList(){const query=elements.courseSearch.value.trim().toLocaleLowerCase("de");elements.courseList.replaceChildren();courses.filter(c=>`${c.subject} ${c.group}`.toLocaleLowerCase("de").includes(query)).forEach(course=>{const button=document.createElement("button");button.type="button";button.className=`course-button${course.id===activeCourseId?" is-active":""}`;button.innerHTML=`<strong>${esc(course.subject)}</strong><small>${esc(course.group)}</small>`;button.onclick=()=>{activeCourseId=course.id;renderCourseList();renderPlan()};elements.courseList.append(button)})}
function holidayRows(course,occurrences){if(!elements.showHolidays.checked)return[];const range=projectRange(project);const schoolIds=new Set(course.items.map(i=>i.schedule.schoolId).filter(Boolean));const entries=(getHolidayLayer(project).entries||[]).filter(e=>["school-holiday","public-holiday","school-free-day"].includes(e.type)&&e.endDate>=range.start&&e.startDate<=range.end&&(!schoolIds.size||schoolIds.has(e.schoolId)||(e.schoolIds||[]).some(id=>schoolIds.has(id))));const weeks=new Map();entries.forEach(e=>{const key=`${isoWeek(e.startDate)}|${e.name}|${e.startDate}|${e.endDate}`;weeks.set(key,{holiday:true,id:key,date:e.startDate,endDate:e.endDate,name:e.name||"Schulfrei"})});return [...weeks.values()]}
function renderPlan(){const course=courses.find(c=>c.id===activeCourseId);elements.planRows.replaceChildren();if(!course){elements.emptyPlan.hidden=false;elements.planTitle.textContent="Kein Fachplan";elements.summaryCards.replaceChildren();return}elements.emptyPlan.hidden=true;elements.planMeta.textContent=`${course.subject} · ${course.group}`;elements.planTitle.textContent="Stoffverteilungsplan";const plan=planFor(course);const occurrences=occurrenceRows(course);const free=(plan.freeRows||[]).map(row=>({...row,free:true}));const rows=[...occurrences,...free,...holidayRows(course,occurrences)].sort((a,b)=>(a.date||"").localeCompare(b.date||""));const entries=Object.values(plan.entries);const done=entries.filter(e=>e.status==="done").length;const reserve=Math.round(occurrences.length*(Number(plan.reserve)||0)/100);elements.summaryCards.innerHTML=`<div class="summary-card"><span>Verfügbare Stunden</span><strong>${occurrences.length}</strong></div><div class="summary-card"><span>Planungsreserve</span><strong>${reserve}</strong></div><div class="summary-card"><span>Verplant</span><strong>${entries.filter(e=>e.topic.trim()).length}</strong></div><div class="summary-card"><span>Erledigt</span><strong>${done}</strong></div>`;rows.forEach(row=>{if(row.holiday){const tr=document.createElement("tr");tr.className="holiday-row";tr.innerHTML=`<td colspan="6"><strong>KW ${isoWeek(row.date)} · ${esc(row.name)}</strong>${formatDate(row.date)}${row.endDate!==row.date?` – ${formatDate(row.endDate)}`:""} · keine Unterrichtszeit</td>`;elements.planRows.append(tr);return}const entry=entryFor(plan,row);if(activeFilter!=="all"&&entry.status!==activeFilter)return;const tr=document.createElement("tr");tr.className="lesson-row";tr.dataset.status=entry.status;tr.innerHTML=`<td class="date-cell"><strong>KW ${isoWeek(row.date)}</strong><span>${WEEKDAYS[parseDate(row.date).getDay()]}, ${formatDate(row.date)}</span><small>${esc(row.start)}–${esc(row.end)}${row.room?` · ${esc(row.room)}`:""}${row.free?" · frei ergänzt":""}</small></td>${editor("topic",entry.topic,"Thema oder Unterrichtsvorhaben")}${editor("competences",entry.competences,"Die Lernenden können …")}${editor("implementation",entry.implementation,"Inhalte, Methode, Material, Differenzierung …")}${editor("assessment",entry.assessment,"Diagnose, Produkt oder Leistungsnachweis …")}<td><select class="status-select" data-field="status"><option value="open">Offen</option><option value="planned">Geplant</option><option value="done">Erledigt</option><option value="cancelled">Entfallen</option></select></td>`;tr.querySelector("select").value=entry.status;tr.querySelectorAll("[data-field]").forEach(control=>control.addEventListener("input",()=>{entry[control.dataset.field]=control.value;tr.dataset.status=entry.status;save();renderSummaryOnly(course)}));elements.planRows.append(tr)});save()}
function editor(field,value,placeholder){return `<td><textarea class="cell-editor" data-field="${field}" placeholder="${esc(placeholder)}">${esc(value)}</textarea></td>`}
function renderSummaryOnly(course){const plan=planFor(course);const occurrences=occurrenceRows(course);const values=Object.values(plan.entries);elements.summaryCards.children[0].querySelector("strong").textContent=occurrences.length;elements.summaryCards.children[1].querySelector("strong").textContent=Math.round(occurrences.length*(Number(plan.reserve)||0)/100);elements.summaryCards.children[2].querySelector("strong").textContent=values.filter(e=>e.topic.trim()).length;elements.summaryCards.children[3].querySelector("strong").textContent=values.filter(e=>e.status==="done").length}
function openSettings(){const course=courses.find(c=>c.id===activeCourseId);if(!course)return;const plan=planFor(course);elements.frameworkInput.value=plan.framework||"";elements.frameworkUrlInput.value=plan.frameworkUrl||"";elements.reserveInput.value=plan.reserve??10;elements.yearGoalInput.value=plan.yearGoal||"";elements.settingsDialog.showModal()}
function exportData(){if(!project)return;const payload={type:"schola-stoffverteilung",version:1,exportedAt:new Date().toISOString(),calendarId:`SP1:${project.id}`,projectName:project.name,plans:Object.fromEntries(Object.entries(plans).filter(([,p])=>p.projectId===project.id))};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`${String(project.name||"schuljahr").replace(/[^a-z0-9äöüß-]+/gi,"-")}.stoffverteilung.json`;a.click();URL.revokeObjectURL(url)}
elements.connectionForm.addEventListener("submit",e=>{e.preventDefault();connect(elements.calendarIdInput.value)});elements.changeCalendarButton.onclick=()=>{elements.workspace.hidden=true;elements.connectionView.hidden=false;elements.calendarIdInput.select();renderAvailable()};elements.courseSearch.oninput=renderCourseList;elements.showHolidays.onchange=renderPlan;elements.addRowButton.onclick=()=>{const course=courses.find(c=>c.id===activeCourseId);if(!course)return;const value=prompt("Datum der freien Planungszeile (JJJJ-MM-TT):",projectRange(project).start);if(!/^\d{4}-\d{2}-\d{2}$/.test(value||""))return;planFor(course).freeRows.push({id:uid("free"),date:value,start:"",end:""});save();renderPlan()};elements.settingsButton.onclick=openSettings;elements.closeSettingsButton.onclick=()=>elements.settingsDialog.close();elements.settingsForm.addEventListener("submit",()=>{const course=courses.find(c=>c.id===activeCourseId);if(!course)return;Object.assign(planFor(course),{framework:elements.frameworkInput.value.trim(),frameworkUrl:elements.frameworkUrlInput.value.trim(),reserve:Number(elements.reserveInput.value)||0,yearGoal:elements.yearGoalInput.value.trim()});save();renderPlan()});document.querySelectorAll("[data-filter]").forEach(button=>button.onclick=()=>{activeFilter=button.dataset.filter;document.querySelectorAll("[data-filter]").forEach(b=>b.setAttribute("aria-pressed",String(b===button)));renderPlan()});elements.printButton.onclick=()=>window.print();elements.exportButton.onclick=exportData;
function setMenuOpen(open){const menu=$("sideMenu"),overlay=$("menuOverlay"),button=$("menuButton");menu.classList.toggle("is-open",open);menu.setAttribute("aria-hidden",String(!open));menu.inert=!open;overlay.hidden=!open;button.setAttribute("aria-expanded",String(open))}
$("menuButton").onclick=()=>setMenuOpen($("menuButton").getAttribute("aria-expanded")!=="true");$("menuCloseButton").onclick=()=>setMenuOpen(false);$("menuOverlay").onclick=()=>setMenuOpen(false);document.addEventListener("keydown",e=>{if(e.key==="Escape")setMenuOpen(false)});
renderAvailable();const stored=localStorage.getItem(ACTIVE_KEY);if(stored)connect(stored);
