const STORAGE_KEY = "videothek-projects-v1";
const ACTIVE_KEY = "videothek-active-project-v1";
const PLAYLISTS_KEY = "videothek-playlists-v1";
const ACTIVE_PLAYLIST_KEY = "videothek-active-playlist-v1";
const LEGACY_STORAGE_KEY = "filmmap-projects-v1";
const LEGACY_ACTIVE_KEY = "filmmap-active-project-v1";
const LEGACY_PLAYLISTS_KEY = "filmmap-playlists-v1";
const LEGACY_ACTIVE_PLAYLIST_KEY = "filmmap-active-playlist-v1";
const TMDB_TOKEN_KEY = "atlas-tmdb-api-token-v1";
const TMDB_API_URL = "https://api.themoviedb.org/3";
const TMDB_IMAGE_BASE_URL = "https://image.tmdb.org/t/p";
const huePairs = [["#743b43","#c08b56"],["#315f5d","#98a486"],["#48557a","#bd7c70"],["#7b542d","#d1ad67"],["#554267","#78919d"]];
const LEGACY_DEMO_FILM_IDS = new Set(["film-metropolis","film-nosferatu","film-general","film-caligari"]);
const seedProjects = [{id:"projekt-filmarchiv",name:"Filmarchiv",description:"Persönliches Filmarchiv.",createdAt:new Date().toISOString(),films:[]}];
let projects = loadProjects();
let activeProjectId = localStorage.getItem(ACTIVE_KEY) || localStorage.getItem(LEGACY_ACTIVE_KEY) || projects[0].id;
let playlists = loadPlaylists();
let activePlaylistId = localStorage.getItem(ACTIVE_PLAYLIST_KEY) || localStorage.getItem(LEGACY_ACTIVE_PLAYLIST_KEY) || playlists[0]?.id || "";
let activeArchiveSection = "projects";
let catalogProjectId = "all";
let catalogPlaylistId = "all";
let catalogSort = "alphabetical";
let showCatalogOriginalTitles = false;
const catalogRandomOrder = new Map();
let selectedCatalogLanguages = new Set();
let activeGenre = "Alle";
let currentView = "cinema";
let tmdbToken = localStorage.getItem(TMDB_TOKEN_KEY) || "";
let draggedFilmReference = null;
const $ = (id) => document.getElementById(id);
const els = {cinemaView:$("cinemaView"),machineView:$("machineView"),projectSelect:$("projectSelect"),projectList:$("projectList"),projectHeading:$("projectHeading"),catalogHeading:document.querySelector(".section-heading"),machineProjectTitle:$("machineProjectTitle"),projectSummary:$("projectSummary"),genreFilters:$("genreFilters"),genreToggle:$("genreToggle"),genreVisibilityToggle:$("genreVisibilityToggle"),genreFilterRegion:document.querySelector(".genre-filter-region"),filmGrid:$("filmGrid"),filmCount:$("filmCount"),emptyState:$("emptyState"),filmTableBody:$("filmTableBody"),searchInput:$("searchInput"),filmDialog:$("filmDialog"),detailDialog:$("detailDialog"),projectDialog:$("projectDialog"),playlistDialog:$("playlistDialog"),playlistList:$("playlistList"),playlistTitle:$("playlistTitle"),playlistSummary:$("playlistSummary"),projectsSidebarPane:$("projectsSidebarPane"),playlistsSidebarPane:$("playlistsSidebarPane"),projectsContent:$("projectsContent"),playlistsContent:$("playlistsContent"),toast:$("toast")};
function uid(prefix){return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`}
function loadProjects(){try{const data=JSON.parse(localStorage.getItem(STORAGE_KEY)||localStorage.getItem(LEGACY_STORAGE_KEY));if(!Array.isArray(data)||!data.length)return structuredClone(seedProjects);const migrated=data.map(project=>project.id==="projekt-filmarchiv"&&project.films?.length===LEGACY_DEMO_FILM_IDS.size&&project.films.every(film=>LEGACY_DEMO_FILM_IDS.has(film.id))?{...project,description:"Persönliches Filmarchiv.",films:[]}:project);localStorage.setItem(STORAGE_KEY,JSON.stringify(migrated));return migrated}catch{return structuredClone(seedProjects)}}
function loadPlaylists(){try{const data=JSON.parse(localStorage.getItem(PLAYLISTS_KEY)||localStorage.getItem(LEGACY_PLAYLISTS_KEY));const storedPlaylists=Array.isArray(data)?data:[];localStorage.setItem(PLAYLISTS_KEY,JSON.stringify(storedPlaylists));return storedPlaylists}catch{return []}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(projects));localStorage.setItem(ACTIVE_KEY,activeProjectId);localStorage.setItem(PLAYLISTS_KEY,JSON.stringify(playlists));localStorage.setItem(ACTIVE_PLAYLIST_KEY,activePlaylistId)}
function activeProject(){return projects.find(p=>p.id===activeProjectId)||projects[0]}
function esc(value=""){return String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function sameId(a,b){return String(a)===String(b)}
function posterStyle(film){const pair=huePairs[Math.abs(hash(film.title))%huePairs.length];return `--poster-a:${pair[0]};--poster-b:${pair[1]}`}
function hash(s){return [...s].reduce((a,c)=>((a<<5)-a+c.charCodeAt(0))|0,0)}
function genres(films){return ["Alle",...new Set(films.flatMap(f=>f.genre.split(",").map(x=>x.trim()).filter(Boolean)))]}
function catalogFilms(){let films=catalogProjectId==="all"?projects.flatMap(project=>project.films):projects.find(project=>project.id===catalogProjectId)?.films||[];if(catalogPlaylistId!=="all"){const playlist=playlists.find(item=>sameId(item.id,catalogPlaylistId)),ids=new Set((playlist?.filmIds||[]).map(String));films=films.filter(film=>ids.has(String(film.id)))}return films}
function filmLanguages(film){const found=new Map();filmCopies(film).forEach(copy=>String(copy.languages||"").split(/[,;/|]+/).map(language=>language.trim()).filter(Boolean).forEach(language=>{const key=language.toLocaleLowerCase("de");if(!found.has(key))found.set(key,language)}));return [...found.entries()].map(([key,label])=>({key,label}))}
function archiveLanguageOptions(){const counts=new Map(),labels=new Map();projects.flatMap(project=>project.films).forEach(film=>filmLanguages(film).forEach(({key,label})=>{counts.set(key,(counts.get(key)||0)+1);if(!labels.has(key))labels.set(key,label)}));return [...counts].map(([key,count])=>({key,label:labels.get(key),count})).sort((a,b)=>b.count-a.count||a.label.localeCompare(b.label,"de",{sensitivity:"base"}))}
function renderCatalogLanguageFilters(){const options=archiveLanguageOptions(),available=new Set(options.map(option=>option.key));selectedCatalogLanguages=new Set([...selectedCatalogLanguages].filter(language=>available.has(language)));$("catalogLanguagesEmpty").hidden=options.length>0;$("catalogLanguageFilters").hidden=!options.length;$("catalogLanguageFilters").innerHTML=options.map(option=>`<label><input type="checkbox" value="${esc(option.key)}" ${selectedCatalogLanguages.has(option.key)?"checked":""}><span>${esc(option.label)}</span><small>${option.count}</small></label>`).join("")}
function filmCollectionNumber(film){const relevant=catalogPlaylistId==="all"?playlists:playlists.filter(playlist=>sameId(playlist.id,catalogPlaylistId));for(const playlist of relevant){const number=playlistNumber(playlist,film.id);if(number)return number}return ""}
function filmMatchesQuery(film,query){const q=String(query||"").trim().toLowerCase();return !q||[film.title,film.originalTitle,film.director,film.cast,film.genre,film.countries,String(film.year),...filmCopies(film).flatMap(copy=>[copy.title||copy.label||"",copy.languages,copy.resolution,copy.quality])].join(" ").toLowerCase().includes(q)}
function filteredFilms(){const q=els.searchInput.value;const films=catalogFilms().filter(f=>(activeGenre==="Alle"||(f.genre||"").split(",").map(x=>x.trim()).includes(activeGenre))&&(selectedCatalogLanguages.size===0||filmLanguages(f).some(language=>selectedCatalogLanguages.has(language.key)))&&filmMatchesQuery(f,q));const byTitle=(a,b)=>String(a.title||"").localeCompare(String(b.title||""),"de",{sensitivity:"base"}),byCollectionNumber=(a,b)=>{const aNumber=filmCollectionNumber(a),bNumber=filmCollectionNumber(b);if(!aNumber)return bNumber?1:byTitle(a,b);if(!bNumber)return -1;return aNumber.localeCompare(bNumber,"de",{numeric:true,sensitivity:"base"})||byTitle(a,b)},randomValue=film=>{const id=String(film.id);if(!catalogRandomOrder.has(id))catalogRandomOrder.set(id,Math.random());return catalogRandomOrder.get(id)};return films.sort((a,b)=>catalogSort==="random"?randomValue(a)-randomValue(b):catalogSort==="collection-number"?byCollectionNumber(a,b):catalogSort==="year-desc"?(Number(b.year)||0)-(Number(a.year)||0)||byTitle(a,b):catalogSort==="year-asc"?(Number(a.year)||9999)-(Number(b.year)||9999)||byTitle(a,b):catalogSort==="genre"?String(a.genre||"").localeCompare(String(b.genre||""),"de",{sensitivity:"base"})||byTitle(a,b):byTitle(a,b))}
function cover(film,mini=false){return film.cover?`<img class="${mini?"mini-poster":""}" src="${esc(film.cover)}" alt="" onerror="this.remove()">`:mini?`<span class="mini-poster" style="${posterStyle(film)}"></span>`:""}
function render(){const p=activeProject();if(!p)return;els.projectSelect.innerHTML=`<option value="all" ${catalogProjectId==="all"?"selected":""}>Alle Projekte</option>`+projects.map(x=>`<option value="${x.id}" ${x.id===catalogProjectId?"selected":""}>${esc(x.name)}</option>`).join("");els.projectList.innerHTML=projects.map(x=>`<div class="project-row ${x.id===p.id?"is-active":""}"><button class="project-item" type="button" data-project-id="${x.id}"><span>${esc(x.name)}</span><small>${x.films.length}</small></button><div class="project-row-menu-wrap"><button class="project-row-menu-button" type="button" data-project-row-menu="${x.id}" aria-label="Menü für ${esc(x.name)} öffnen" aria-expanded="false">⋮</button><div class="project-row-menu" data-project-row-popup="${x.id}" hidden><button class="project-delete-button" type="button" data-delete-project="${x.id}">Löschen</button></div></div></div>`).join("");els.projectHeading.textContent=catalogProjectId==="all"?"Alle Projekte":projects.find(x=>x.id===catalogProjectId)?.name||"Alle Projekte";els.machineProjectTitle.textContent=p.name;els.projectSummary.textContent=`${p.films.length} ${p.films.length===1?"Film":"Filme"} · ${p.description||"Ohne Beschreibung"}`;renderPlaylists();renderFilters();renderCatalog();renderTable();renderHero()}
function renderPlaylists(){const active=playlists.find(item=>item.id===activePlaylistId);els.playlistList.innerHTML=playlists.map(item=>`<div class="project-row ${item.id===activePlaylistId?"is-active":""}"><button class="project-item" type="button" data-playlist-id="${item.id}"><span>${esc(item.name)}</span><small>${item.filmIds?.length||0}</small></button><div class="project-row-menu-wrap"><button class="project-row-menu-button" type="button" data-playlist-row-menu="${item.id}" aria-label="Menü für ${esc(item.name)} öffnen" aria-expanded="false">⋮</button><div class="project-row-menu" data-playlist-row-popup="${item.id}" hidden><button type="button" data-delete-playlist="${item.id}">Löschen</button></div></div></div>`).join("");els.playlistTitle.textContent=active?.name||"Playlisten";els.playlistSummary.textContent=active?`${active.filmIds?.length||0} ${active.filmIds?.length===1?"Film":"Filme"} · ${active.description||"Ohne Beschreibung"}`:"Noch keine Playlist angelegt.";$("playlistEmptyTitle").textContent=active?"Diese Playlist ist noch leer.":"Filme für einen Abend zusammenstellen";$("playlistEmptyText").textContent=active?"Die Filmzuordnung folgt direkt aus dem Filmarchiv.":"Lege links deine erste Playlist an."}
function setArchiveSection(section){activeArchiveSection=section==="playlists"?"playlists":"projects";document.querySelectorAll("[data-archive-section]").forEach(button=>{const selected=button.dataset.archiveSection===activeArchiveSection;button.classList.toggle("is-active",selected);button.setAttribute("aria-selected",String(selected))});els.projectsSidebarPane.hidden=activeArchiveSection!=="projects";els.playlistsSidebarPane.hidden=activeArchiveSection!=="playlists";els.projectsContent.hidden=activeArchiveSection!=="projects";els.playlistsContent.hidden=activeArchiveSection!=="playlists";closeProjectMenu();closeProjectRowMenus()}
let genresExpanded=false,genreFiltersVisible=true,genreOverflowFrame;
function updateGenreOverflow(){cancelAnimationFrame(genreOverflowFrame);genreOverflowFrame=requestAnimationFrame(()=>{if(!genreFiltersVisible){els.genreToggle.hidden=true;return}els.genreFilters.classList.remove("is-expanded");const overflowing=els.genreFilters.scrollHeight>els.genreFilters.clientHeight+1;if(genresExpanded&&overflowing)els.genreFilters.classList.add("is-expanded");els.genreToggle.hidden=!overflowing;els.genreToggle.setAttribute("aria-expanded",String(genresExpanded&&overflowing));els.genreToggle.innerHTML=genresExpanded&&overflowing?'Weniger Genres <span aria-hidden="true">⌃</span>':'Mehr Genres <span aria-hidden="true">⌄</span>'})}
function setGenreVisibility(visible){genreFiltersVisible=visible;els.genreFilterRegion.classList.toggle("genres-hidden",!visible);els.genreVisibilityToggle.setAttribute("aria-pressed",String(visible));if(!visible){activeGenre="Alle";genresExpanded=false}renderFilters();renderCatalog()}
function renderFilters(){const available=genres(catalogFilms());if(!available.includes(activeGenre))activeGenre="Alle";els.genreFilters.innerHTML=available.map(g=>`<button class="chip ${g===activeGenre?"is-active":""}" type="button" data-genre="${esc(g)}">${esc(g)}</button>`).join("");updateGenreOverflow()}
let catalogAlignmentFrame;
function alignCatalogControls(){cancelAnimationFrame(catalogAlignmentFrame);catalogAlignmentFrame=requestAnimationFrame(()=>{const cards=[...els.filmGrid.children];if(!cards.length){els.catalogHeading.style.removeProperty("--catalog-right-inset");return}const gridRect=els.filmGrid.getBoundingClientRect(),firstTop=cards[0].getBoundingClientRect().top;const firstRow=cards.filter(card=>Math.abs(card.getBoundingClientRect().top-firstTop)<2);const rowRight=Math.max(...firstRow.map(card=>card.getBoundingClientRect().right));els.catalogHeading.style.setProperty("--catalog-right-inset",`${Math.max(0,gridRect.right-rowRight)}px`)})}
function renderCatalogMenu(){if(catalogPlaylistId!=="all"&&!playlists.some(item=>sameId(item.id,catalogPlaylistId)))catalogPlaylistId="all";$("catalogPlaylistSelect").innerHTML='<option value="all">Alle Playlisten</option>'+playlists.map(item=>`<option value="${esc(item.id)}" ${sameId(item.id,catalogPlaylistId)?"selected":""}>${esc(item.name)}</option>`).join("");$("catalogSortSelect").value=catalogSort;$("catalogOriginalTitleToggle").checked=showCatalogOriginalTitles;renderCatalogLanguageFilters()}
function directorShortName(name){const words=String(name||"").trim().split(/\s+/).filter(Boolean);return words.at(-1)||"Regie unbekannt"}
function compactDirectorNames(){els.filmGrid.querySelectorAll("[data-director-filter]").forEach(link=>{link.textContent=link.dataset.directorFilter;link.classList.remove("is-short");if(link.scrollWidth>link.clientWidth){link.textContent=directorShortName(link.dataset.directorFilter);link.classList.add("is-short")}})}
function filterByDirector(name){els.searchInput.value=name;renderCatalog();renderHero();els.searchInput.focus()}
function catalogDisplayTitle(film){return showCatalogOriginalTitles&&String(film.originalTitle||"").trim()?film.originalTitle:film.title}
function renderCatalog(){renderCatalogMenu();const films=filteredFilms();els.filmGrid.classList.toggle("is-searching",Boolean(els.searchInput.value.trim()));els.filmCount.textContent=`${films.length} ${films.length===1?"Titel":"Titel"}`;els.filmGrid.innerHTML=films.map(f=>{const collectionNumber=catalogSort==="collection-number"?filmCollectionNumber(f):"",director=String(f.director||"").trim();return `<article class="film-card"><button class="film-card-main" type="button" data-film-detail="${esc(f.id)}"><span class="poster" style="${posterStyle(f)}">${cover(f)}<span class="play-badge" aria-hidden="true">▶</span></span><span class="film-info"><strong>${esc(catalogDisplayTitle(f))}</strong></span></button><span class="film-meta"><span>${esc(f.year||"—")} ·</span>${director?`<button type="button" data-director-filter="${esc(director)}" title="Alle Filme von ${esc(director)}">${esc(director)}</button>`:`<span>Regie unbekannt</span>`}</span>${collectionNumber?`<small class="collection-number"># ${esc(collectionNumber)}</small>`:""}</article>`}).join("");els.filmGrid.querySelectorAll("[data-film-detail]").forEach(card=>card.addEventListener("click",()=>showDetail(card.dataset.filmDetail)));els.filmGrid.querySelectorAll("[data-director-filter]").forEach(link=>link.addEventListener("click",()=>filterByDirector(link.dataset.directorFilter)));els.emptyState.hidden=films.length>0;compactDirectorNames();alignCatalogControls()}
function setCatalogDrawer(open){$("catalogDrawer").classList.toggle("is-open",open);$("catalogBackdrop").classList.toggle("is-open",open);$("catalogDrawer").setAttribute("aria-hidden",String(!open));$("catalogMenuButton").setAttribute("aria-expanded",String(open));document.body.classList.toggle("catalog-drawer-open",open);if(open)setTimeout(()=>$("catalogDrawerClose").focus(),180)}
function renderHero(){}
function renderTable(){const p=activeProject(),films=p.films.filter(film=>filmMatchesQuery(film,els.searchInput.value));els.filmTableBody.innerHTML=films.length?films.map(f=>{const copies=filmCopies(f),primary=copies[0]||{};return `<tr><td><div class="title-cell film-drag-handle" draggable="true" data-drag-film-id="${esc(f.id)}" data-drag-project-id="${esc(p.id)}" title="${esc(f.title)} in ein anderes Projekt verschieben">${cover(f,true)}<strong>${esc(f.title)}</strong></div></td><td>${esc(f.year||"—")}</td><td>${esc(f.genre||"—")}</td><td class="link-cell" title="${esc(primary.link||"")}">${copies.length?`${copies.length} ${copies.length===1?"Fassung":"Fassungen"}`:"Keine Fassung"}</td><td><span class="status" data-status="${esc(primary.status||"nicht verfügbar")}">${esc(primary.status||"nicht verfügbar")}</span></td><td><button class="row-menu" type="button" data-edit-film="${esc(f.id)}" aria-label="${esc(f.title)} bearbeiten">•••</button></td></tr>`}).join(""):`<tr><td colspan="6" class="muted">${p.films.length?"Keine passenden Filme gefunden.":"Noch keine Filme in diesem Projekt."}</td></tr>`}
function projectDropRow(target){return target.closest?.(".project-row")?.querySelector("[data-project-id]")?.closest(".project-row")||null}
function clearProjectDropTargets(){document.querySelectorAll(".project-row.is-film-drop-target").forEach(row=>row.classList.remove("is-film-drop-target"))}
function clearFilmDropState(){clearProjectDropTargets();document.querySelectorAll(".film-drag-handle.is-dragging").forEach(handle=>handle.classList.remove("is-dragging"))}
function startFilmDrag(event){const handle=event.target.closest("[data-drag-film-id]");if(!handle)return;draggedFilmReference={filmId:handle.dataset.dragFilmId,projectId:handle.dataset.dragProjectId};handle.classList.add("is-dragging");event.dataTransfer.effectAllowed="move";event.dataTransfer.setData("text/plain",handle.dataset.dragFilmId);if(event.dataTransfer.setDragImage)event.dataTransfer.setDragImage(handle,24,24)}
function dragFilmOverProject(event){const row=projectDropRow(event.target),targetId=row?.querySelector("[data-project-id]")?.dataset.projectId;if(!draggedFilmReference||!targetId||sameId(targetId,draggedFilmReference.projectId))return;event.preventDefault();event.dataTransfer.dropEffect="move";clearProjectDropTargets();row.classList.add("is-film-drop-target")}
function leaveFilmProject(event){const row=projectDropRow(event.target);if(row&&!row.contains(event.relatedTarget))row.classList.remove("is-film-drop-target")}
function dropFilmOnProject(event){const row=projectDropRow(event.target),targetId=row?.querySelector("[data-project-id]")?.dataset.projectId,reference=draggedFilmReference;event.preventDefault();clearFilmDropState();draggedFilmReference=null;if(!reference||!targetId||sameId(targetId,reference.projectId))return;const source=projects.find(project=>sameId(project.id,reference.projectId)),target=projects.find(project=>sameId(project.id,targetId)),filmIndex=source?.films.findIndex(film=>sameId(film.id,reference.filmId))??-1;if(!source||!target||filmIndex<0)return;const [film]=source.films.splice(filmIndex,1);target.films.unshift(film);save();render();toast(`„${film.title}“ nach „${target.name}“ verschoben`)}
function setView(view){currentView=view;els.cinemaView.hidden=view!=="cinema";els.machineView.hidden=view!=="machine";document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("is-active",b.dataset.view===view));if(view==="machine"){els.searchInput.blur();setCatalogDrawer(false)}render()}
function selectProject(id){if(currentView==="cinema"){if(id!=="all"&&!projects.some(p=>p.id===id))return;catalogProjectId=id;activeGenre="Alle";render();return}if(!projects.some(p=>p.id===id))return;activeProjectId=id;activeGenre="Alle";save();render()}
function normalizeRuntime(value){if(value===""||value===null||value===undefined)return "";if(typeof value==="number"||/^\d+(?:\.\d+)?$/.test(String(value).trim())){const seconds=Math.round(Number(value)*60);const hours=Math.floor(seconds/3600);const minutes=Math.floor(seconds%3600/60);return `${hours}:${String(minutes).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`}const match=String(value).trim().match(/^(\d{1,3}):([0-5]\d):([0-5]\d)$/);return match?`${Number(match[1])}:${match[2]}:${match[3]}`:""}
function closeProjectRowMenus(){document.querySelectorAll("[data-project-row-popup],[data-playlist-row-popup]").forEach(menu=>{menu.hidden=true});document.querySelectorAll("[data-project-row-menu],[data-playlist-row-menu]").forEach(button=>button.setAttribute("aria-expanded","false"))}
function toggleProjectRowMenu(id){const menu=document.querySelector(`[data-project-row-popup="${CSS.escape(id)}"]`);const button=document.querySelector(`[data-project-row-menu="${CSS.escape(id)}"]`);if(!menu||!button)return;const willOpen=menu.hidden;closeProjectRowMenus();menu.hidden=!willOpen;button.setAttribute("aria-expanded",String(willOpen))}
function togglePlaylistRowMenu(id){const menu=document.querySelector(`[data-playlist-row-popup="${CSS.escape(id)}"]`);const button=document.querySelector(`[data-playlist-row-menu="${CSS.escape(id)}"]`);if(!menu||!button)return;const willOpen=menu.hidden;closeProjectRowMenus();menu.hidden=!willOpen;button.setAttribute("aria-expanded",String(willOpen))}
function deleteProject(id){const project=projects.find(item=>item.id===id);if(!project)return;if(projects.length===1){toast("Das letzte Projekt kann nicht gelöscht werden");return}if(!confirm(`Projekt „${project.name}“ mit ${project.films.length} ${project.films.length===1?"Film":"Filmen"} löschen?`))return;projects=projects.filter(item=>item.id!==id);if(activeProjectId===id)activeProjectId=projects[0].id;if(catalogProjectId===id)catalogProjectId="all";activeGenre="Alle";save();render();toast("Projekt gelöscht")}
let editingCopies=[];
let editingPlaylistIds=new Set();
let editingPlaylistNumbers=new Map();
function filmCopies(film){if(Array.isArray(film?.copies))return film.copies.map(copy=>({...copy,title:copy.title||copy.label||""}));return film?.link?[{id:uid("copy"),title:"Fassung 1",link:film.link,languages:"",resolution:"",quality:"",status:film.status||"verfügbar"}]:[]}
function setFilmTab(tab){const active=["general","copies","playlists"].includes(tab)?tab:"general";document.querySelectorAll("[data-film-tab]").forEach(button=>{const selected=button.dataset.filmTab===active;button.classList.toggle("is-active",selected);button.setAttribute("aria-selected",String(selected))});$("filmGeneralPanel").hidden=active!=="general";$("filmCopiesPanel").hidden=active!=="copies";$("filmPlaylistsPanel").hidden=active!=="playlists"}
function updateFilmPlaylistCount(){const checked=[$("filmPlaylistChecklist")].flatMap(root=>[...root.querySelectorAll('[data-playlist-check]:checked')]);$("filmPlaylistCount").textContent=checked.length}
function playlistNumber(playlist,filmId){return String((playlist.filmAssignments||[]).find(entry=>sameId(entry.filmId,filmId))?.collectionNumber||"")}
function renderFilmPlaylistChecklist(){$("filmPlaylistsEmpty").hidden=playlists.length>0;$("filmPlaylistChecklist").hidden=!playlists.length;$("filmPlaylistChecklist").innerHTML=playlists.map(playlist=>{const id=String(playlist.id),checked=editingPlaylistIds.has(id);return `<div class="film-playlist-option"><label class="playlist-check-main"><input data-playlist-check type="checkbox" value="${esc(id)}" ${checked?"checked":""}><span><strong>${esc(playlist.name)}</strong><small>${playlist.filmIds?.length||0} ${playlist.filmIds?.length===1?"Film":"Filme"}</small></span></label><label class="playlist-number-field"><span>Sammlungsnummer</span><input data-playlist-number maxlength="6" pattern="[A-Za-z0-9]{0,6}" inputmode="text" value="${esc(editingPlaylistNumbers.get(id)||"")}" placeholder="ABC123"></label></div>`}).join("");$("filmPlaylistChecklist").querySelectorAll("[data-playlist-check]").forEach(input=>input.addEventListener("change",updateFilmPlaylistCount));$("filmPlaylistChecklist").querySelectorAll("[data-playlist-number]").forEach(input=>input.addEventListener("input",()=>{input.value=input.value.replace(/[^A-Za-z0-9]/g,"").slice(0,6)}));updateFilmPlaylistCount()}
function readFilmPlaylistChecklist(){editingPlaylistIds=new Set();editingPlaylistNumbers=new Map();$("filmPlaylistChecklist").querySelectorAll(".film-playlist-option").forEach(row=>{const checkbox=row.querySelector("[data-playlist-check]"),number=row.querySelector("[data-playlist-number]").value.trim();if(checkbox.checked){editingPlaylistIds.add(String(checkbox.value));editingPlaylistNumbers.set(String(checkbox.value),number)}})}
function readCopyEditor(){editingCopies=[...$("filmCopiesList").querySelectorAll("[data-copy-id]")].map(row=>({id:row.dataset.copyId,title:row.querySelector('[data-copy-field="title"]').value.trim(),link:row.querySelector('[data-copy-field="link"]').value.trim(),languages:row.querySelector('[data-copy-field="languages"]').value.trim(),resolution:row.querySelector('[data-copy-field="resolution"]').value,quality:row.querySelector('[data-copy-field="quality"]').value,status:row.querySelector('[data-copy-field="status"]').value}))}
function renderCopyEditor(){$("filmCopyCount").textContent=editingCopies.length;$("filmCopiesEmpty").hidden=editingCopies.length>0;$("filmCopiesList").innerHTML=editingCopies.map((copy,index)=>`<section class="film-copy" data-copy-id="${esc(copy.id)}"><div class="film-copy-head"><strong>Fassung ${index+1}</strong><button type="button" data-remove-copy="${esc(copy.id)}" aria-label="Fassung ${index+1} entfernen">Entfernen</button></div><div class="copy-grid"><label>Quelle<input data-copy-field="title" maxlength="160" value="${esc(copy.title||copy.label||"")}" placeholder="z. B. Deutsche Kinofassung"></label><label>Sprache(n)<input data-copy-field="languages" maxlength="120" value="${esc(copy.languages||"")}" placeholder="Deutsch, Englisch"></label><label class="span-2">Link zum Film<input data-copy-field="link" type="url" value="${esc(copy.link||"")}" placeholder="https://… oder file:///…"></label><label>Auflösung<select data-copy-field="resolution"><option value="">Nicht angegeben</option>${["4K / UHD","1080p","720p","576p","480p","Andere"].map(value=>`<option ${copy.resolution===value?"selected":""}>${value}</option>`).join("")}</select></label><label>Qualität<select data-copy-field="quality"><option value="">Nicht bewertet</option>${["Hervorragend","Sehr gut","Gut","Akzeptabel","Schlecht"].map(value=>`<option ${copy.quality===value?"selected":""}>${value}</option>`).join("")}</select></label><label>Status<select data-copy-field="status"><option value="verfügbar" ${copy.status==="verfügbar"?"selected":""}>Verfügbar</option><option value="prüfen" ${copy.status==="prüfen"?"selected":""}>Link prüfen</option><option value="nicht verfügbar" ${copy.status==="nicht verfügbar"?"selected":""}>Nicht verfügbar</option></select></label></div></section>`).join("");$("filmCopiesList").querySelectorAll("[data-remove-copy]").forEach(button=>button.addEventListener("click",()=>{readCopyEditor();editingCopies=editingCopies.filter(copy=>!sameId(copy.id,button.dataset.removeCopy));renderCopyEditor()}))}
function addFilmCopy(){readCopyEditor();editingCopies.push({id:uid("copy"),title:`Fassung ${editingCopies.length+1}`,link:"",languages:"",resolution:"",quality:"",status:"verfügbar"});renderCopyEditor();setFilmTab("copies")}
function openFilmForm(id){const f=activeProject().films.find(x=>sameId(x.id,id)),filmId=f?.id||uid("film");$("filmDialogTitle").textContent=f?"Film bearbeiten":"Film anlegen";$("deleteFilmButton").hidden=!f;const fields={filmId,filmTmdbId:f?.tmdbId||"",filmTitle:f?.title||"",filmOriginalTitle:f?.originalTitle||"",filmYear:f?.year||"",filmRuntime:normalizeRuntime(f?.runtime),filmDirector:f?.director||"",filmCast:f?.cast||"",filmGenre:f?.genre||"",filmCountries:f?.countries||"",filmTrailer:f?.trailer||"",filmCover:f?.cover||"",filmRating:f?.rating||"",filmDescription:f?.description||""};Object.entries(fields).forEach(([fieldId,v])=>$(fieldId).value=v);editingCopies=filmCopies(f).map(copy=>({...copy,id:copy.id||uid("copy")}));editingPlaylistIds=new Set(playlists.filter(playlist=>(playlist.filmIds||[]).some(itemId=>sameId(itemId,filmId))).map(playlist=>String(playlist.id)));editingPlaylistNumbers=new Map(playlists.map(playlist=>[String(playlist.id),playlistNumber(playlist,filmId)]));renderCopyEditor();renderFilmPlaylistChecklist();setFilmTab("general");resetTmdbPanel(f);els.filmDialog.showModal()}
function saveFilm(){if(!$("filmTitle").value.trim())return;readCopyEditor();readFilmPlaylistChecklist();const copies=editingCopies.filter(copy=>copy.link||copy.title||copy.languages||copy.resolution||copy.quality);const primary=copies[0]||{};const data={id:$("filmId").value||uid("film"),tmdbId:$("filmTmdbId").value.trim(),title:$("filmTitle").value.trim(),originalTitle:$("filmOriginalTitle").value.trim(),year:Number($("filmYear").value)||"",runtime:normalizeRuntime($("filmRuntime").value),director:$("filmDirector").value.trim(),cast:$("filmCast").value.trim(),genre:$("filmGenre").value.trim(),countries:$("filmCountries").value.trim(),link:primary.link||"",copies,trailer:$("filmTrailer").value.trim(),cover:$("filmCover").value.trim(),status:primary.status||"nicht verfügbar",rating:$("filmRating").value.trim(),description:$("filmDescription").value.trim()};const p=activeProject(),i=p.films.findIndex(f=>sameId(f.id,data.id));if(i>=0)p.films[i]=data;else p.films.unshift(data);playlists.forEach(playlist=>{playlist.filmIds=(playlist.filmIds||[]).filter(itemId=>!sameId(itemId,data.id));playlist.filmAssignments=(playlist.filmAssignments||[]).filter(entry=>!sameId(entry.filmId,data.id));if(editingPlaylistIds.has(String(playlist.id))){playlist.filmIds.push(data.id);playlist.filmAssignments.push({filmId:data.id,collectionNumber:editingPlaylistNumbers.get(String(playlist.id))||""})}});save();render();toast(i>=0?"Film aktualisiert":"Film angelegt")}
function deleteFilm(){const id=$("filmId").value;if(!id||!confirm("Diesen Filmeintrag löschen?"))return;activeProject().films=activeProject().films.filter(f=>!sameId(f.id,id));playlists.forEach(playlist=>{playlist.filmIds=(playlist.filmIds||[]).filter(itemId=>!sameId(itemId,id));playlist.filmAssignments=(playlist.filmAssignments||[]).filter(entry=>!sameId(entry.filmId,id))});els.filmDialog.close();save();render();toast("Film gelöscht")}
function showDetail(id){const owner=projects.find(project=>project.films.some(film=>sameId(film.id,id)));if(!owner)return;const f=owner.films.find(film=>sameId(film.id,id)),copies=filmCopies(f);activeProjectId=owner.id;const copyActions=copies.map((copy,index)=>copy.link?`<a class="copy-action" href="${esc(copy.link)}" target="_blank" rel="noopener noreferrer"><span>▶ ${esc(copy.title||copy.label||`Fassung ${index+1}`)}</span><small>${esc([copy.languages,copy.resolution,copy.quality].filter(Boolean).join(" · ")||"Film öffnen")}</small></a>`:"").join("");$("detailContent").innerHTML=`<div class="detail-layout"><div class="detail-poster" style="${posterStyle(f)}">${cover(f)}<span class="poster-fallback"><strong>${esc(f.originalTitle||f.title)}</strong></span></div><div class="detail-body"><button class="dialog-close" style="float:right" type="button" data-close-detail aria-label="Schließen">×</button><p class="eyebrow">${esc(f.genre||"Film")}</p><h2>${esc(f.originalTitle||f.title)}</h2><div class="detail-meta">${esc([f.year,normalizeRuntime(f.runtime),f.rating,f.director].filter(Boolean).join(" · "))}</div>${f.countries?`<p class="detail-countries"><strong>Länder</strong> ${esc(f.countries)}</p>`:""}<p>${esc(f.description||"Keine Beschreibung hinterlegt.")}</p>${f.cast?`<p class="detail-cast"><strong>Mit</strong> ${esc(f.cast)}</p>`:""}${copyActions?`<div class="detail-copies"><strong>Meine Fassungen</strong>${copyActions}</div>`:""}<div class="detail-actions">${!copyActions?`<button disabled>Keine Fassung hinterlegt</button>`:""}${f.trailer?`<a class="secondary-action" href="${esc(f.trailer)}" target="_blank" rel="noopener noreferrer">Trailer ansehen</a>`:""}<button class="secondary-action" type="button" data-edit-from-detail="${esc(f.id)}">Bearbeiten</button></div></div></div>`;if(!els.detailDialog.open)els.detailDialog.showModal()}
function createProject(){const name=$("projectName").value.trim();if(!name)return;const p={id:uid("projekt"),name,description:$("projectDescription").value.trim(),createdAt:new Date().toISOString(),films:[]};projects.push(p);activeProjectId=p.id;save();render();toast("Projekt angelegt")}
function createPlaylist(){const name=$("playlistName").value.trim();if(!name)return;const playlist={id:uid("playlist"),name,description:$("playlistDescription").value.trim(),createdAt:new Date().toISOString(),filmIds:[]};playlists.push(playlist);activePlaylistId=playlist.id;save();render();setArchiveSection("playlists");toast("Playlist angelegt")}
function selectPlaylist(id){if(!playlists.some(item=>item.id===id))return;activePlaylistId=id;save();render();setArchiveSection("playlists")}
function deletePlaylist(id){const playlist=playlists.find(item=>item.id===id);if(!playlist||!confirm(`Playlist „${playlist.name}“ löschen?`))return;playlists=playlists.filter(item=>item.id!==id);if(activePlaylistId===id)activePlaylistId=playlists[0]?.id||"";save();render();setArchiveSection("playlists");toast("Playlist gelöscht")}
function exportProject(){const p=activeProject();const payload={format:"videothek-project",version:1,exportedAt:new Date().toISOString(),project:p};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${p.name.toLowerCase().replace(/[^a-z0-9äöüß]+/gi,"-")||"videothek-projekt"}.videothek.json`;a.click();URL.revokeObjectURL(a.href);toast("Projekt exportiert")}
async function importProject(file){try{const data=JSON.parse(await file.text());const p=["videothek-project","filmmap-project"].includes(data?.format)?data.project:data;if(!p||typeof p.name!=="string"||!Array.isArray(p.films))throw new Error();const imported={...p,id:uid("projekt"),name:`${p.name} (Import)`,films:p.films.map(f=>({...f,id:uid("film")}))};projects.push(imported);activeProjectId=imported.id;save();render();toast("Projekt importiert")}catch{toast("Diese Datei ist kein gültiges Videothek-Projekt")}}
async function importGoogleLibrary(file){try{const text=await file.text();const extension=file.name.split(".").pop().toLowerCase();const type=extension==="json"||file.type.includes("json")?"json":"csv";const result=VideothekImport.parseLibrary(text,type);if(!result.films.length)throw new Error("Keine Filmeinträge gefunden");const baseName=file.name.replace(/\.(csv|json)$/i,"").trim()||"Google-Bibliothek";const imported={id:uid("projekt"),name:`${baseName} · Google`,description:`Aus ${file.name} importierte Google-TV-/YouTube-Bibliothek.`,createdAt:new Date().toISOString(),source:{provider:"Google TV / YouTube",fileName:file.name,importedAt:new Date().toISOString(),format:type},films:result.films.map(f=>({...f,id:uid("film")}))};projects.push(imported);activeProjectId=imported.id;activeGenre="Alle";save();render();const duplicateNote=result.duplicates?` · ${result.duplicates} Dubletten übersprungen`:"";toast(`${result.films.length} Filme importiert${duplicateNote}`)}catch(error){toast(error instanceof SyntaxError?"Die JSON-Datei konnte nicht gelesen werden":"Keine gültige Google-Filmliste gefunden")}}
async function importAnyFile(file){if(file.name.toLowerCase().endsWith(".json")){try{const data=JSON.parse(await file.text());if(["videothek-project","filmmap-project"].includes(data?.format)||(data?.name&&Array.isArray(data?.films))){await importProject(file);return}}catch{toast("Die JSON-Datei konnte nicht gelesen werden");return}}await importGoogleLibrary(file)}
let pastedCandidates=[];
function openPasteImport(){$("pasteProjectName").value="Meine Google-Filme";$("pasteSource").value="";$("pasteResultSummary").textContent="";$("pastePreview").innerHTML="";$("pastePreviewFieldset").hidden=true;$("confirmPasteButton").disabled=true;pastedCandidates=[];$("pasteDialog").showModal();setTimeout(()=>$("pasteSource").focus(),0)}
function analyzePasted(){const result=VideothekImport.parsePastedLibrary($("pasteSource").value);pastedCandidates=result.films;$("pasteResultSummary").textContent=result.films.length?`${result.films.length} mögliche Titel erkannt`:"Keine Titel erkannt";$("pastePreviewFieldset").hidden=!result.films.length;$("confirmPasteButton").disabled=!result.films.length;$("pastePreview").innerHTML=result.films.map((film,index)=>`<label><input type="checkbox" data-paste-index="${index}" checked><span><strong>${esc(film.title)}</strong><small>${esc(film.link||"Kein direkter Link erkannt")}</small></span></label>`).join("")}
function importPasted(){const selected=[...document.querySelectorAll("[data-paste-index]:checked")].map(input=>pastedCandidates[Number(input.dataset.pasteIndex)]).filter(Boolean);if(!selected.length){toast("Bitte mindestens einen Titel auswählen");return}const name=$("pasteProjectName").value.trim()||"Meine Google-Filme";const project={id:uid("projekt"),name,description:"Aus dem kopierten Inhalt der Google-TV-/YouTube-Bibliothek importiert.",createdAt:new Date().toISOString(),source:{provider:"Google TV / YouTube",importedAt:new Date().toISOString(),format:"clipboard"},films:selected.map(f=>({...f,id:uid("film")}))};projects.push(project);activeProjectId=project.id;activeGenre="Alle";save();render();$("pasteDialog").close();toast(`${selected.length} Titel als Projekt importiert`)}
let tmdbSearchResults=[];
function resetTmdbPanel(film){tmdbSearchResults=[];$("tmdbResults").innerHTML="";$("tmdbResults").hidden=true;$("tmdbTokenInput").value=tmdbToken;$("tmdbTokenRow").hidden=Boolean(tmdbToken);$("tmdbStatus").textContent=film?.tmdbId?`Mit TMDB ${film.tmdbId} verknüpft.`:""}
function tmdbRuntime(minutes){const total=Math.max(0,Number(minutes)||0)*60;return `${Math.floor(total/3600)}:${String(Math.floor(total%3600/60)).padStart(2,"0")}:00`}
async function fetchTmdb(path,params={}){if(!tmdbToken)throw new Error("token-missing");const url=new URL(`${TMDB_API_URL}${path}`);Object.entries(params).forEach(([key,value])=>{if(value!==""&&value!==undefined&&value!==null)url.searchParams.set(key,String(value))});const response=await fetch(url,{headers:{Accept:"application/json",Authorization:`Bearer ${tmdbToken}`}});if(!response.ok)throw new Error(`tmdb-${response.status}`);return response.json()}
function renderTmdbResults(results){tmdbSearchResults=results;$("tmdbResults").hidden=!results.length;$("tmdbResults").innerHTML=results.map((film,index)=>{const year=String(film.release_date||"").slice(0,4)||"—";const poster=film.poster_path?`<img src="${TMDB_IMAGE_BASE_URL}/w92${esc(film.poster_path)}" alt="">`:`<span class="tmdb-result-placeholder" aria-hidden="true"></span>`;return `<button type="button" class="tmdb-result" data-tmdb-result="${index}">${poster}<span><strong>${esc(film.title)}</strong><small>${esc(year)}${film.original_title&&film.original_title!==film.title?` · ${esc(film.original_title)}`:""}</small><em>${esc(film.overview||"Keine Beschreibung verfügbar.")}</em></span><b>Daten übernehmen</b></button>`}).join("");$("tmdbResults").querySelectorAll("[data-tmdb-result]").forEach(button=>button.addEventListener("click",()=>applyTmdbResult(tmdbSearchResults[Number(button.dataset.tmdbResult)])))}
async function searchTmdb(){const query=$("filmTitle").value.trim();if(!tmdbToken){$("tmdbTokenRow").hidden=false;$("tmdbTokenInput").focus();$("tmdbStatus").textContent="Bitte zuerst den TMDB API Read Access Token hinterlegen.";return}if(!query){$("tmdbStatus").textContent="Bitte zuerst einen Filmtitel eingeben.";$("filmTitle").focus();return}$("tmdbSearchButton").disabled=true;$("tmdbStatus").textContent="TMDB wird durchsucht …";$("tmdbResults").hidden=true;try{const payload=await fetchTmdb("/search/movie",{query,language:"de-DE",include_adult:"false",page:1});const results=(payload.results||[]).slice(0,8);renderTmdbResults(results);$("tmdbStatus").textContent=results.length?`${results.length} Treffer gefunden. Bitte den passenden Film auswählen.`:"Kein passender Film gefunden."}catch(error){$("tmdbStatus").textContent=error.message==="tmdb-401"?"Der TMDB-Token wurde nicht akzeptiert.":"TMDB konnte gerade nicht erreicht werden.";if(error.message==="tmdb-401")$("tmdbTokenRow").hidden=false}finally{$("tmdbSearchButton").disabled=false}}
function getGermanRating(details){const releases=(details.release_dates?.results||[]).find(item=>item.iso_3166_1==="DE")?.release_dates||[];const certification=releases.map(item=>String(item.certification||"").trim()).find(Boolean);return certification?`FSK ${certification.replace(/^FSK\s*/i,"")}`:""}
function getYoutubeTrailer(details){const videos=details.videos?.results||[];const trailer=videos.find(video=>video.site==="YouTube"&&video.type==="Trailer"&&video.official&&video.iso_639_1==="de")||videos.find(video=>video.site==="YouTube"&&video.type==="Trailer"&&video.official)||videos.find(video=>video.site==="YouTube"&&video.type==="Trailer");return trailer?.key?`https://www.youtube.com/watch?v=${encodeURIComponent(trailer.key)}`:""}
async function applyTmdbResult(result){if(!result?.id)return;$("tmdbStatus").textContent="Filminformationen werden geladen …";$("tmdbResults").querySelectorAll("button").forEach(button=>button.disabled=true);try{const details=await fetchTmdb(`/movie/${encodeURIComponent(result.id)}`,{language:"de-DE",append_to_response:"credits,videos,release_dates"});const director=(details.credits?.crew||[]).find(person=>person.job==="Director")?.name||"";const cast=(details.credits?.cast||[]).slice(0,16).map(person=>person.name).filter(Boolean).join(", ");const values={filmTmdbId:String(details.id),filmTitle:details.title||result.title||"",filmOriginalTitle:details.original_title||details.title||result.title||"",filmYear:String(details.release_date||"").slice(0,4),filmRuntime:tmdbRuntime(details.runtime),filmDirector:director,filmGenre:(details.genres||[]).map(genre=>genre.name).join(", "),filmCountries:(details.production_countries||[]).map(country=>country.name).filter(Boolean).join(", "),filmTrailer:getYoutubeTrailer(details),filmCover:details.poster_path?`${TMDB_IMAGE_BASE_URL}/w500${details.poster_path}`:"",filmRating:getGermanRating(details),filmDescription:details.overview||""};$("filmCast").value=cast;Object.entries(values).forEach(([id,value])=>{if(value)$(id).value=value});$("tmdbStatus").textContent=`Daten für „${details.title||result.title}“ übernommen. Deine Fassungen bleiben erhalten.`;$("tmdbResults").hidden=true}catch{$("tmdbStatus").textContent="Die Filmdetails konnten nicht geladen werden.";$("tmdbResults").querySelectorAll("button").forEach(button=>button.disabled=false)}}
function readTimemapTmdbToken(){return new Promise(resolve=>{if(!window.indexedDB){resolve("");return}const request=indexedDB.open("timemap-local-db",1);request.onerror=()=>resolve("");request.onupgradeneeded=()=>{request.transaction.abort();resolve("")};request.onsuccess=()=>{const db=request.result;if(!db.objectStoreNames.contains("appState")){db.close();resolve("");return}const transaction=db.transaction("appState","readonly");const getRequest=transaction.objectStore("appState").get("primary");getRequest.onerror=()=>{db.close();resolve("")};getRequest.onsuccess=()=>{const token=String(getRequest.result?.state?.tmdbApiToken||"").trim();db.close();resolve(token)}}})}
async function initializeTmdbToken(){if(tmdbToken)return;const timemapToken=await readTimemapTmdbToken();if(!timemapToken)return;tmdbToken=timemapToken;localStorage.setItem(TMDB_TOKEN_KEY,tmdbToken)}
let toastTimer;function toast(msg){els.toast.textContent=msg;els.toast.classList.add("is-visible");clearTimeout(toastTimer);toastTimer=setTimeout(()=>els.toast.classList.remove("is-visible"),2600)}
function closeProjectMenu(){$("projectMenu").hidden=true;$("projectMenuButton").setAttribute("aria-expanded","false")}
document.addEventListener("click",e=>{const t=e.target.closest("button");if(!e.target.closest(".project-menu-wrap"))closeProjectMenu();if(!e.target.closest(".project-row-menu-wrap"))closeProjectRowMenus();if(!t)return;if(t.dataset.view)setView(t.dataset.view);if(t.hasAttribute("data-open-machine"))setView("machine");if(t.dataset.archiveSection)setArchiveSection(t.dataset.archiveSection);if(t.dataset.projectId)selectProject(t.dataset.projectId);if(t.dataset.playlistId)selectPlaylist(t.dataset.playlistId);if(t.dataset.projectRowMenu)toggleProjectRowMenu(t.dataset.projectRowMenu);if(t.dataset.playlistRowMenu)togglePlaylistRowMenu(t.dataset.playlistRowMenu);if(t.dataset.deleteProject)deleteProject(t.dataset.deleteProject);if(t.dataset.deletePlaylist)deletePlaylist(t.dataset.deletePlaylist);if(t.dataset.genre){activeGenre=t.dataset.genre;render()}if(t.dataset.editFilm)openFilmForm(t.dataset.editFilm);if(t.hasAttribute("data-close-detail"))els.detailDialog.close();if(t.dataset.editFromDetail){els.detailDialog.close();setView("machine");setArchiveSection("projects");openFilmForm(t.dataset.editFromDetail)}});
els.projectSelect.addEventListener("change",e=>selectProject(e.target.value));els.searchInput.addEventListener("input",()=>{if(currentView!=="cinema")setView("cinema");else{renderCatalog();renderHero()}});$("addFilmButton").addEventListener("click",()=>openFilmForm());$("filmForm").addEventListener("submit",e=>{if(e.submitter?.value==="default")saveFilm()});$("deleteFilmButton").addEventListener("click",deleteFilm);$("addProjectButton").addEventListener("click",()=>{$("projectName").value="";$("projectDescription").value="";els.projectDialog.showModal()});$("projectForm").addEventListener("submit",e=>{if(e.submitter?.value==="default")createProject()});$("addPlaylistButton").addEventListener("click",()=>{$("playlistName").value="";$("playlistDescription").value="";els.playlistDialog.showModal()});$("playlistForm").addEventListener("submit",e=>{if(e.submitter?.value==="default")createPlaylist()});$("projectMenuButton").addEventListener("click",()=>{const willOpen=$("projectMenu").hidden;$ ("projectMenu").hidden=!willOpen;$("projectMenuButton").setAttribute("aria-expanded",String(willOpen))});$("exportButton").addEventListener("click",()=>{closeProjectMenu();exportProject()});$("importButton").addEventListener("click",()=>{closeProjectMenu();$("importInput").click()});$("importInput").addEventListener("change",e=>{if(e.target.files[0])importAnyFile(e.target.files[0]);e.target.value=""});$("pasteImportButton").addEventListener("click",()=>{closeProjectMenu();openPasteImport()});$("analyzePasteButton").addEventListener("click",analyzePasted);$("confirmPasteButton").addEventListener("click",importPasted);document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeProjectMenu();closeProjectRowMenus()}});window.addEventListener("resize",alignCatalogControls);
$("catalogMenuButton").addEventListener("click",()=>setCatalogDrawer(!$("catalogDrawer").classList.contains("is-open")));
$("catalogDrawerClose").addEventListener("click",()=>setCatalogDrawer(false));
$("catalogBackdrop").addEventListener("click",()=>setCatalogDrawer(false));
$("catalogPlaylistSelect").addEventListener("change",event=>{catalogPlaylistId=event.target.value;activeGenre="Alle";render()});
$("catalogSortSelect").addEventListener("change",event=>{catalogSort=event.target.value;renderCatalog()});
$("catalogOriginalTitleToggle").addEventListener("change",event=>{showCatalogOriginalTitles=event.target.checked;renderCatalog()});
$("catalogLanguageFilters").addEventListener("change",event=>{if(!event.target.matches('input[type="checkbox"]'))return;selectedCatalogLanguages=new Set([...$("catalogLanguageFilters").querySelectorAll('input:checked')].map(input=>input.value));render()});
document.addEventListener("keydown",event=>{if(event.key==="Escape"&&$("catalogDrawer").classList.contains("is-open"))setCatalogDrawer(false)});
els.genreToggle.addEventListener("click",()=>{genresExpanded=!genresExpanded;updateGenreOverflow()});
els.genreVisibilityToggle.addEventListener("click",()=>setGenreVisibility(!genreFiltersVisible));
$("tmdbSearchButton").addEventListener("click",searchTmdb);
$("tmdbTokenSaveButton").addEventListener("click",()=>{const token=$("tmdbTokenInput").value.trim();if(!token){$("tmdbStatus").textContent="Bitte einen TMDB API Read Access Token eingeben.";return}tmdbToken=token;localStorage.setItem(TMDB_TOKEN_KEY,tmdbToken);$("tmdbTokenRow").hidden=true;$("tmdbStatus").textContent="Token lokal gespeichert. Die Suche kann jetzt beginnen.";searchTmdb()});
document.querySelectorAll("[data-film-tab]").forEach(button=>button.addEventListener("click",()=>setFilmTab(button.dataset.filmTab)));
$("addFilmCopyButton").addEventListener("click",addFilmCopy);
els.filmTableBody.addEventListener("dragstart",startFilmDrag);
els.filmTableBody.addEventListener("dragend",()=>{draggedFilmReference=null;clearFilmDropState()});
els.projectList.addEventListener("dragover",dragFilmOverProject);
els.projectList.addEventListener("dragleave",leaveFilmProject);
els.projectList.addEventListener("drop",dropFilmOnProject);
window.addEventListener("resize",()=>{updateGenreOverflow();compactDirectorNames()});
// Die globale Suche wirkt in der jeweils geöffneten Ansicht, ohne diese zu wechseln.
els.searchInput.addEventListener("input",event=>{if(currentView==="cinema"){renderCatalog();renderHero()}else renderTable();event.stopImmediatePropagation()},{capture:true});
function registerWebMCP(){const ctx=document.modelContext;if(!ctx?.registerTool)return;const add=(tool)=>Promise.resolve(ctx.registerTool(tool)).catch(()=>{});add({name:"list_videothek_projects",title:"Videothek-Projekte auflisten",description:"Listet die vorhandenen Videothek-Projekte und ihre Filmzahlen auf.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>projects.map(p=>({id:p.id,name:p.name,filmCount:p.films.length}))});add({name:"create_videothek_project",title:"Videothek-Projekt anlegen",description:"Legt ein neues leeres Videothek-Projekt an und macht es zum aktiven Projekt.",inputSchema:{type:"object",properties:{name:{type:"string",minLength:1},description:{type:"string"}},required:["name"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:({name,description=""})=>{if(typeof name!=="string"||!name.trim())throw new Error("Ein Projektname ist erforderlich.");const p={id:uid("projekt"),name:name.trim(),description:String(description),createdAt:new Date().toISOString(),films:[]};projects.push(p);activeProjectId=p.id;save();render();return{id:p.id,name:p.name}}});add({name:"add_film_reference",title:"Filmverweis hinzufügen",description:"Fügt dem aktiven Projekt einen Film mit Metadaten und externem Speicherlink hinzu. Es wird keine Filmdatei gespeichert.",inputSchema:{type:"object",properties:{title:{type:"string",minLength:1},link:{type:"string"},year:{type:"integer"},genre:{type:"string"},description:{type:"string"}},required:["title","link"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:(input)=>{if(typeof input.title!=="string"||!input.title.trim()||typeof input.link!=="string")throw new Error("Titel und Link sind erforderlich.");const f={id:uid("film"),title:input.title.trim(),link:input.link.trim(),year:input.year||"",genre:input.genre||"",description:input.description||"",runtime:"",director:"",cover:"",trailer:"",status:"verfügbar",rating:""};activeProject().films.unshift(f);save();render();return{id:f.id,projectId:activeProjectId}}})}
initializeTmdbToken();registerWebMCP();render();setArchiveSection(activeArchiveSection);

