window.SCHOLA_PSE_DATA = {
    "format":  "schola-periodic-table",
    "version":  1,
    "language":  "de",
    "source":  {
                   "name":  "PubChem Periodic Table",
                   "url":  "https://pubchem.ncbi.nlm.nih.gov/rest/pug/periodictable/JSON",
                   "retrieved":  "2026-08-14"
               },
    "elements":  [
                     {
                         "number":  1,
                         "symbol":  "H",
                         "name":  "Wasserstoff",
                         "mass":  "1.0080",
                         "period":  1,
                         "group":  1,
                         "category":  "nonmetal",
                         "categoryName":  "Nichtmetall",
                         "state":  "gasförmig",
                         "gridRow":  2,
                         "gridColumn":  1
                     },
                     {
                         "number":  2,
                         "symbol":  "He",
                         "name":  "Helium",
                         "mass":  "4.00260",
                         "period":  1,
                         "group":  18,
                         "category":  "noble",
                         "categoryName":  "Edelgas",
                         "state":  "gasförmig",
                         "gridRow":  2,
                         "gridColumn":  18
                     },
                     {
                         "number":  3,
                         "symbol":  "Li",
                         "name":  "Lithium",
                         "mass":  "7.0",
                         "period":  2,
                         "group":  1,
                         "category":  "alkali",
                         "categoryName":  "Alkalimetall",
                         "state":  "fest",
                         "gridRow":  3,
                         "gridColumn":  1
                     },
                     {
                         "number":  4,
                         "symbol":  "Be",
                         "name":  "Beryllium",
                         "mass":  "9.012183",
                         "period":  2,
                         "group":  2,
                         "category":  "alkaline",
                         "categoryName":  "Erdalkalimetall",
                         "state":  "fest",
                         "gridRow":  3,
                         "gridColumn":  2
                     },
                     {
                         "number":  5,
                         "symbol":  "B",
                         "name":  "Bor",
                         "mass":  "10.81",
                         "period":  2,
                         "group":  13,
                         "category":  "metalloid",
                         "categoryName":  "Halbmetall",
                         "state":  "fest",
                         "gridRow":  3,
                         "gridColumn":  13
                     },
                     {
                         "number":  6,
                         "symbol":  "C",
                         "name":  "Kohlenstoff",
                         "mass":  "12.011",
                         "period":  2,
                         "group":  14,
                         "category":  "nonmetal",
                         "categoryName":  "Nichtmetall",
                         "state":  "fest",
                         "gridRow":  3,
                         "gridColumn":  14
                     },
                     {
                         "number":  7,
                         "symbol":  "N",
                         "name":  "Stickstoff",
                         "mass":  "14.007",
                         "period":  2,
                         "group":  15,
                         "category":  "nonmetal",
                         "categoryName":  "Nichtmetall",
                         "state":  "gasförmig",
                         "gridRow":  3,
                         "gridColumn":  15
                     },
                     {
                         "number":  8,
                         "symbol":  "O",
                         "name":  "Sauerstoff",
                         "mass":  "15.999",
                         "period":  2,
                         "group":  16,
                         "category":  "nonmetal",
                         "categoryName":  "Nichtmetall",
                         "state":  "gasförmig",
                         "gridRow":  3,
                         "gridColumn":  16
                     },
                     {
                         "number":  9,
                         "symbol":  "F",
                         "name":  "Fluor",
                         "mass":  "18.99840316",
                         "period":  2,
                         "group":  17,
                         "category":  "halogen",
                         "categoryName":  "Halogen",
                         "state":  "gasförmig",
                         "gridRow":  3,
                         "gridColumn":  17
                     },
                     {
                         "number":  10,
                         "symbol":  "Ne",
                         "name":  "Neon",
                         "mass":  "20.180",
                         "period":  2,
                         "group":  18,
                         "category":  "noble",
                         "categoryName":  "Edelgas",
                         "state":  "gasförmig",
                         "gridRow":  3,
                         "gridColumn":  18
                     },
                     {
                         "number":  11,
                         "symbol":  "Na",
                         "name":  "Natrium",
                         "mass":  "22.9897693",
                         "period":  3,
                         "group":  1,
                         "category":  "alkali",
                         "categoryName":  "Alkalimetall",
                         "state":  "fest",
                         "gridRow":  4,
                         "gridColumn":  1
                     },
                     {
                         "number":  12,
                         "symbol":  "Mg",
                         "name":  "Magnesium",
                         "mass":  "24.305",
                         "period":  3,
                         "group":  2,
                         "category":  "alkaline",
                         "categoryName":  "Erdalkalimetall",
                         "state":  "fest",
                         "gridRow":  4,
                         "gridColumn":  2
                     },
                     {
                         "number":  13,
                         "symbol":  "Al",
                         "name":  "Aluminium",
                         "mass":  "26.981538",
                         "period":  3,
                         "group":  13,
                         "category":  "post-transition",
                         "categoryName":  "Metall",
                         "state":  "fest",
                         "gridRow":  4,
                         "gridColumn":  13
                     },
                     {
                         "number":  14,
                         "symbol":  "Si",
                         "name":  "Silicium",
                         "mass":  "28.085",
                         "period":  3,
                         "group":  14,
                         "category":  "metalloid",
                         "categoryName":  "Halbmetall",
                         "state":  "fest",
                         "gridRow":  4,
                         "gridColumn":  14
                     },
                     {
                         "number":  15,
                         "symbol":  "P",
                         "name":  "Phosphor",
                         "mass":  "30.97376200",
                         "period":  3,
                         "group":  15,
                         "category":  "nonmetal",
                         "categoryName":  "Nichtmetall",
                         "state":  "fest",
                         "gridRow":  4,
                         "gridColumn":  15
                     },
                     {
                         "number":  16,
                         "symbol":  "S",
                         "name":  "Schwefel",
                         "mass":  "32.07",
                         "period":  3,
                         "group":  16,
                         "category":  "nonmetal",
                         "categoryName":  "Nichtmetall",
                         "state":  "fest",
                         "gridRow":  4,
                         "gridColumn":  16
                     },
                     {
                         "number":  17,
                         "symbol":  "Cl",
                         "name":  "Chlor",
                         "mass":  "35.45",
                         "period":  3,
                         "group":  17,
                         "category":  "halogen",
                         "categoryName":  "Halogen",
                         "state":  "gasförmig",
                         "gridRow":  4,
                         "gridColumn":  17
                     },
                     {
                         "number":  18,
                         "symbol":  "Ar",
                         "name":  "Argon",
                         "mass":  "39.9",
                         "period":  3,
                         "group":  18,
                         "category":  "noble",
                         "categoryName":  "Edelgas",
                         "state":  "gasförmig",
                         "gridRow":  4,
                         "gridColumn":  18
                     },
                     {
                         "number":  19,
                         "symbol":  "K",
                         "name":  "Kalium",
                         "mass":  "39.0983",
                         "period":  4,
                         "group":  1,
                         "category":  "alkali",
                         "categoryName":  "Alkalimetall",
                         "state":  "fest",
                         "gridRow":  5,
                         "gridColumn":  1
                     },
                     {
                         "number":  20,
                         "symbol":  "Ca",
                         "name":  "Calcium",
                         "mass":  "40.08",
                         "period":  4,
                         "group":  2,
                         "category":  "alkaline",
                         "categoryName":  "Erdalkalimetall",
                         "state":  "fest",
                         "gridRow":  5,
                         "gridColumn":  2
                     },
                     {
                         "number":  21,
                         "symbol":  "Sc",
                         "name":  "Scandium",
                         "mass":  "44.95591",
                         "period":  4,
                         "group":  3,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  5,
                         "gridColumn":  3
                     },
                     {
                         "number":  22,
                         "symbol":  "Ti",
                         "name":  "Titan",
                         "mass":  "47.867",
                         "period":  4,
                         "group":  4,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  5,
                         "gridColumn":  4
                     },
                     {
                         "number":  23,
                         "symbol":  "V",
                         "name":  "Vanadium",
                         "mass":  "50.9415",
                         "period":  4,
                         "group":  5,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  5,
                         "gridColumn":  5
                     },
                     {
                         "number":  24,
                         "symbol":  "Cr",
                         "name":  "Chrom",
                         "mass":  "51.996",
                         "period":  4,
                         "group":  6,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  5,
                         "gridColumn":  6
                     },
                     {
                         "number":  25,
                         "symbol":  "Mn",
                         "name":  "Mangan",
                         "mass":  "54.93804",
                         "period":  4,
                         "group":  7,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  5,
                         "gridColumn":  7
                     },
                     {
                         "number":  26,
                         "symbol":  "Fe",
                         "name":  "Eisen",
                         "mass":  "55.84",
                         "period":  4,
                         "group":  8,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  5,
                         "gridColumn":  8
                     },
                     {
                         "number":  27,
                         "symbol":  "Co",
                         "name":  "Cobalt",
                         "mass":  "58.93319",
                         "period":  4,
                         "group":  9,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  5,
                         "gridColumn":  9
                     },
                     {
                         "number":  28,
                         "symbol":  "Ni",
                         "name":  "Nickel",
                         "mass":  "58.693",
                         "period":  4,
                         "group":  10,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  5,
                         "gridColumn":  10
                     },
                     {
                         "number":  29,
                         "symbol":  "Cu",
                         "name":  "Kupfer",
                         "mass":  "63.55",
                         "period":  4,
                         "group":  11,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  5,
                         "gridColumn":  11
                     },
                     {
                         "number":  30,
                         "symbol":  "Zn",
                         "name":  "Zink",
                         "mass":  "65.4",
                         "period":  4,
                         "group":  12,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  5,
                         "gridColumn":  12
                     },
                     {
                         "number":  31,
                         "symbol":  "Ga",
                         "name":  "Gallium",
                         "mass":  "69.723",
                         "period":  4,
                         "group":  13,
                         "category":  "post-transition",
                         "categoryName":  "Metall",
                         "state":  "fest",
                         "gridRow":  5,
                         "gridColumn":  13
                     },
                     {
                         "number":  32,
                         "symbol":  "Ge",
                         "name":  "Germanium",
                         "mass":  "72.63",
                         "period":  4,
                         "group":  14,
                         "category":  "metalloid",
                         "categoryName":  "Halbmetall",
                         "state":  "fest",
                         "gridRow":  5,
                         "gridColumn":  14
                     },
                     {
                         "number":  33,
                         "symbol":  "As",
                         "name":  "Arsen",
                         "mass":  "74.92159",
                         "period":  4,
                         "group":  15,
                         "category":  "metalloid",
                         "categoryName":  "Halbmetall",
                         "state":  "fest",
                         "gridRow":  5,
                         "gridColumn":  15
                     },
                     {
                         "number":  34,
                         "symbol":  "Se",
                         "name":  "Selen",
                         "mass":  "78.97",
                         "period":  4,
                         "group":  16,
                         "category":  "nonmetal",
                         "categoryName":  "Nichtmetall",
                         "state":  "fest",
                         "gridRow":  5,
                         "gridColumn":  16
                     },
                     {
                         "number":  35,
                         "symbol":  "Br",
                         "name":  "Brom",
                         "mass":  "79.90",
                         "period":  4,
                         "group":  17,
                         "category":  "halogen",
                         "categoryName":  "Halogen",
                         "state":  "flüssig",
                         "gridRow":  5,
                         "gridColumn":  17
                     },
                     {
                         "number":  36,
                         "symbol":  "Kr",
                         "name":  "Krypton",
                         "mass":  "83.80",
                         "period":  4,
                         "group":  18,
                         "category":  "noble",
                         "categoryName":  "Edelgas",
                         "state":  "gasförmig",
                         "gridRow":  5,
                         "gridColumn":  18
                     },
                     {
                         "number":  37,
                         "symbol":  "Rb",
                         "name":  "Rubidium",
                         "mass":  "85.468",
                         "period":  5,
                         "group":  1,
                         "category":  "alkali",
                         "categoryName":  "Alkalimetall",
                         "state":  "fest",
                         "gridRow":  6,
                         "gridColumn":  1
                     },
                     {
                         "number":  38,
                         "symbol":  "Sr",
                         "name":  "Strontium",
                         "mass":  "87.62",
                         "period":  5,
                         "group":  2,
                         "category":  "alkaline",
                         "categoryName":  "Erdalkalimetall",
                         "state":  "fest",
                         "gridRow":  6,
                         "gridColumn":  2
                     },
                     {
                         "number":  39,
                         "symbol":  "Y",
                         "name":  "Yttrium",
                         "mass":  "88.90584",
                         "period":  5,
                         "group":  3,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  6,
                         "gridColumn":  3
                     },
                     {
                         "number":  40,
                         "symbol":  "Zr",
                         "name":  "Zirconium",
                         "mass":  "91.22",
                         "period":  5,
                         "group":  4,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  6,
                         "gridColumn":  4
                     },
                     {
                         "number":  41,
                         "symbol":  "Nb",
                         "name":  "Niob",
                         "mass":  "92.90637",
                         "period":  5,
                         "group":  5,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  6,
                         "gridColumn":  5
                     },
                     {
                         "number":  42,
                         "symbol":  "Mo",
                         "name":  "Molybdän",
                         "mass":  "95.95",
                         "period":  5,
                         "group":  6,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  6,
                         "gridColumn":  6
                     },
                     {
                         "number":  43,
                         "symbol":  "Tc",
                         "name":  "Technetium",
                         "mass":  "96.90636",
                         "period":  5,
                         "group":  7,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  6,
                         "gridColumn":  7
                     },
                     {
                         "number":  44,
                         "symbol":  "Ru",
                         "name":  "Ruthenium",
                         "mass":  "101.1",
                         "period":  5,
                         "group":  8,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  6,
                         "gridColumn":  8
                     },
                     {
                         "number":  45,
                         "symbol":  "Rh",
                         "name":  "Rhodium",
                         "mass":  "102.9055",
                         "period":  5,
                         "group":  9,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  6,
                         "gridColumn":  9
                     },
                     {
                         "number":  46,
                         "symbol":  "Pd",
                         "name":  "Palladium",
                         "mass":  "106.42",
                         "period":  5,
                         "group":  10,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  6,
                         "gridColumn":  10
                     },
                     {
                         "number":  47,
                         "symbol":  "Ag",
                         "name":  "Silber",
                         "mass":  "107.868",
                         "period":  5,
                         "group":  11,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  6,
                         "gridColumn":  11
                     },
                     {
                         "number":  48,
                         "symbol":  "Cd",
                         "name":  "Cadmium",
                         "mass":  "112.41",
                         "period":  5,
                         "group":  12,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  6,
                         "gridColumn":  12
                     },
                     {
                         "number":  49,
                         "symbol":  "In",
                         "name":  "Indium",
                         "mass":  "114.818",
                         "period":  5,
                         "group":  13,
                         "category":  "post-transition",
                         "categoryName":  "Metall",
                         "state":  "fest",
                         "gridRow":  6,
                         "gridColumn":  13
                     },
                     {
                         "number":  50,
                         "symbol":  "Sn",
                         "name":  "Zinn",
                         "mass":  "118.71",
                         "period":  5,
                         "group":  14,
                         "category":  "post-transition",
                         "categoryName":  "Metall",
                         "state":  "fest",
                         "gridRow":  6,
                         "gridColumn":  14
                     },
                     {
                         "number":  51,
                         "symbol":  "Sb",
                         "name":  "Antimon",
                         "mass":  "121.760",
                         "period":  5,
                         "group":  15,
                         "category":  "metalloid",
                         "categoryName":  "Halbmetall",
                         "state":  "fest",
                         "gridRow":  6,
                         "gridColumn":  15
                     },
                     {
                         "number":  52,
                         "symbol":  "Te",
                         "name":  "Tellur",
                         "mass":  "127.6",
                         "period":  5,
                         "group":  16,
                         "category":  "metalloid",
                         "categoryName":  "Halbmetall",
                         "state":  "fest",
                         "gridRow":  6,
                         "gridColumn":  16
                     },
                     {
                         "number":  53,
                         "symbol":  "I",
                         "name":  "Iod",
                         "mass":  "126.9045",
                         "period":  5,
                         "group":  17,
                         "category":  "halogen",
                         "categoryName":  "Halogen",
                         "state":  "fest",
                         "gridRow":  6,
                         "gridColumn":  17
                     },
                     {
                         "number":  54,
                         "symbol":  "Xe",
                         "name":  "Xenon",
                         "mass":  "131.29",
                         "period":  5,
                         "group":  18,
                         "category":  "noble",
                         "categoryName":  "Edelgas",
                         "state":  "gasförmig",
                         "gridRow":  6,
                         "gridColumn":  18
                     },
                     {
                         "number":  55,
                         "symbol":  "Cs",
                         "name":  "Cäsium",
                         "mass":  "132.9054520",
                         "period":  6,
                         "group":  1,
                         "category":  "alkali",
                         "categoryName":  "Alkalimetall",
                         "state":  "fest",
                         "gridRow":  7,
                         "gridColumn":  1
                     },
                     {
                         "number":  56,
                         "symbol":  "Ba",
                         "name":  "Barium",
                         "mass":  "137.33",
                         "period":  6,
                         "group":  2,
                         "category":  "alkaline",
                         "categoryName":  "Erdalkalimetall",
                         "state":  "fest",
                         "gridRow":  7,
                         "gridColumn":  2
                     },
                     {
                         "number":  57,
                         "symbol":  "La",
                         "name":  "Lanthan",
                         "mass":  "138.9055",
                         "period":  6,
                         "group":  null,
                         "category":  "lanthanide",
                         "categoryName":  "Lanthanoid",
                         "state":  "fest",
                         "gridRow":  10,
                         "gridColumn":  3
                     },
                     {
                         "number":  58,
                         "symbol":  "Ce",
                         "name":  "Cer",
                         "mass":  "140.116",
                         "period":  6,
                         "group":  null,
                         "category":  "lanthanide",
                         "categoryName":  "Lanthanoid",
                         "state":  "fest",
                         "gridRow":  10,
                         "gridColumn":  4
                     },
                     {
                         "number":  59,
                         "symbol":  "Pr",
                         "name":  "Praseodym",
                         "mass":  "140.90766",
                         "period":  6,
                         "group":  null,
                         "category":  "lanthanide",
                         "categoryName":  "Lanthanoid",
                         "state":  "fest",
                         "gridRow":  10,
                         "gridColumn":  5
                     },
                     {
                         "number":  60,
                         "symbol":  "Nd",
                         "name":  "Neodym",
                         "mass":  "144.24",
                         "period":  6,
                         "group":  null,
                         "category":  "lanthanide",
                         "categoryName":  "Lanthanoid",
                         "state":  "fest",
                         "gridRow":  10,
                         "gridColumn":  6
                     },
                     {
                         "number":  61,
                         "symbol":  "Pm",
                         "name":  "Promethium",
                         "mass":  "144.91276",
                         "period":  6,
                         "group":  null,
                         "category":  "lanthanide",
                         "categoryName":  "Lanthanoid",
                         "state":  "fest",
                         "gridRow":  10,
                         "gridColumn":  7
                     },
                     {
                         "number":  62,
                         "symbol":  "Sm",
                         "name":  "Samarium",
                         "mass":  "150.4",
                         "period":  6,
                         "group":  null,
                         "category":  "lanthanide",
                         "categoryName":  "Lanthanoid",
                         "state":  "fest",
                         "gridRow":  10,
                         "gridColumn":  8
                     },
                     {
                         "number":  63,
                         "symbol":  "Eu",
                         "name":  "Europium",
                         "mass":  "151.964",
                         "period":  6,
                         "group":  null,
                         "category":  "lanthanide",
                         "categoryName":  "Lanthanoid",
                         "state":  "fest",
                         "gridRow":  10,
                         "gridColumn":  9
                     },
                     {
                         "number":  64,
                         "symbol":  "Gd",
                         "name":  "Gadolinium",
                         "mass":  "157.25",
                         "period":  6,
                         "group":  null,
                         "category":  "lanthanide",
                         "categoryName":  "Lanthanoid",
                         "state":  "fest",
                         "gridRow":  10,
                         "gridColumn":  10
                     },
                     {
                         "number":  65,
                         "symbol":  "Tb",
                         "name":  "Terbium",
                         "mass":  "158.92535",
                         "period":  6,
                         "group":  null,
                         "category":  "lanthanide",
                         "categoryName":  "Lanthanoid",
                         "state":  "fest",
                         "gridRow":  10,
                         "gridColumn":  11
                     },
                     {
                         "number":  66,
                         "symbol":  "Dy",
                         "name":  "Dysprosium",
                         "mass":  "162.500",
                         "period":  6,
                         "group":  null,
                         "category":  "lanthanide",
                         "categoryName":  "Lanthanoid",
                         "state":  "fest",
                         "gridRow":  10,
                         "gridColumn":  12
                     },
                     {
                         "number":  67,
                         "symbol":  "Ho",
                         "name":  "Holmium",
                         "mass":  "164.93033",
                         "period":  6,
                         "group":  null,
                         "category":  "lanthanide",
                         "categoryName":  "Lanthanoid",
                         "state":  "fest",
                         "gridRow":  10,
                         "gridColumn":  13
                     },
                     {
                         "number":  68,
                         "symbol":  "Er",
                         "name":  "Erbium",
                         "mass":  "167.26",
                         "period":  6,
                         "group":  null,
                         "category":  "lanthanide",
                         "categoryName":  "Lanthanoid",
                         "state":  "fest",
                         "gridRow":  10,
                         "gridColumn":  14
                     },
                     {
                         "number":  69,
                         "symbol":  "Tm",
                         "name":  "Thulium",
                         "mass":  "168.93422",
                         "period":  6,
                         "group":  null,
                         "category":  "lanthanide",
                         "categoryName":  "Lanthanoid",
                         "state":  "fest",
                         "gridRow":  10,
                         "gridColumn":  15
                     },
                     {
                         "number":  70,
                         "symbol":  "Yb",
                         "name":  "Ytterbium",
                         "mass":  "173.05",
                         "period":  6,
                         "group":  null,
                         "category":  "lanthanide",
                         "categoryName":  "Lanthanoid",
                         "state":  "fest",
                         "gridRow":  10,
                         "gridColumn":  16
                     },
                     {
                         "number":  71,
                         "symbol":  "Lu",
                         "name":  "Lutetium",
                         "mass":  "174.9667",
                         "period":  6,
                         "group":  null,
                         "category":  "lanthanide",
                         "categoryName":  "Lanthanoid",
                         "state":  "fest",
                         "gridRow":  10,
                         "gridColumn":  17
                     },
                     {
                         "number":  72,
                         "symbol":  "Hf",
                         "name":  "Hafnium",
                         "mass":  "178.49",
                         "period":  6,
                         "group":  4,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  7,
                         "gridColumn":  4
                     },
                     {
                         "number":  73,
                         "symbol":  "Ta",
                         "name":  "Tantal",
                         "mass":  "180.9479",
                         "period":  6,
                         "group":  5,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  7,
                         "gridColumn":  5
                     },
                     {
                         "number":  74,
                         "symbol":  "W",
                         "name":  "Wolfram",
                         "mass":  "183.84",
                         "period":  6,
                         "group":  6,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  7,
                         "gridColumn":  6
                     },
                     {
                         "number":  75,
                         "symbol":  "Re",
                         "name":  "Rhenium",
                         "mass":  "186.207",
                         "period":  6,
                         "group":  7,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  7,
                         "gridColumn":  7
                     },
                     {
                         "number":  76,
                         "symbol":  "Os",
                         "name":  "Osmium",
                         "mass":  "190.2",
                         "period":  6,
                         "group":  8,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  7,
                         "gridColumn":  8
                     },
                     {
                         "number":  77,
                         "symbol":  "Ir",
                         "name":  "Iridium",
                         "mass":  "192.22",
                         "period":  6,
                         "group":  9,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  7,
                         "gridColumn":  9
                     },
                     {
                         "number":  78,
                         "symbol":  "Pt",
                         "name":  "Platin",
                         "mass":  "195.08",
                         "period":  6,
                         "group":  10,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  7,
                         "gridColumn":  10
                     },
                     {
                         "number":  79,
                         "symbol":  "Au",
                         "name":  "Gold",
                         "mass":  "196.96657",
                         "period":  6,
                         "group":  11,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  7,
                         "gridColumn":  11
                     },
                     {
                         "number":  80,
                         "symbol":  "Hg",
                         "name":  "Quecksilber",
                         "mass":  "200.59",
                         "period":  6,
                         "group":  12,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "flüssig",
                         "gridRow":  7,
                         "gridColumn":  12
                     },
                     {
                         "number":  81,
                         "symbol":  "Tl",
                         "name":  "Thallium",
                         "mass":  "204.383",
                         "period":  6,
                         "group":  13,
                         "category":  "post-transition",
                         "categoryName":  "Metall",
                         "state":  "fest",
                         "gridRow":  7,
                         "gridColumn":  13
                     },
                     {
                         "number":  82,
                         "symbol":  "Pb",
                         "name":  "Blei",
                         "mass":  "207",
                         "period":  6,
                         "group":  14,
                         "category":  "post-transition",
                         "categoryName":  "Metall",
                         "state":  "fest",
                         "gridRow":  7,
                         "gridColumn":  14
                     },
                     {
                         "number":  83,
                         "symbol":  "Bi",
                         "name":  "Bismut",
                         "mass":  "208.98040",
                         "period":  6,
                         "group":  15,
                         "category":  "post-transition",
                         "categoryName":  "Metall",
                         "state":  "fest",
                         "gridRow":  7,
                         "gridColumn":  15
                     },
                     {
                         "number":  84,
                         "symbol":  "Po",
                         "name":  "Polonium",
                         "mass":  "208.98243",
                         "period":  6,
                         "group":  16,
                         "category":  "metalloid",
                         "categoryName":  "Halbmetall",
                         "state":  "fest",
                         "gridRow":  7,
                         "gridColumn":  16
                     },
                     {
                         "number":  85,
                         "symbol":  "At",
                         "name":  "Astat",
                         "mass":  "209.98715",
                         "period":  6,
                         "group":  17,
                         "category":  "halogen",
                         "categoryName":  "Halogen",
                         "state":  "fest",
                         "gridRow":  7,
                         "gridColumn":  17
                     },
                     {
                         "number":  86,
                         "symbol":  "Rn",
                         "name":  "Radon",
                         "mass":  "222.01758",
                         "period":  6,
                         "group":  18,
                         "category":  "noble",
                         "categoryName":  "Edelgas",
                         "state":  "gasförmig",
                         "gridRow":  7,
                         "gridColumn":  18
                     },
                     {
                         "number":  87,
                         "symbol":  "Fr",
                         "name":  "Francium",
                         "mass":  "223.01973",
                         "period":  7,
                         "group":  1,
                         "category":  "alkali",
                         "categoryName":  "Alkalimetall",
                         "state":  "fest",
                         "gridRow":  8,
                         "gridColumn":  1
                     },
                     {
                         "number":  88,
                         "symbol":  "Ra",
                         "name":  "Radium",
                         "mass":  "226.02541",
                         "period":  7,
                         "group":  2,
                         "category":  "alkaline",
                         "categoryName":  "Erdalkalimetall",
                         "state":  "fest",
                         "gridRow":  8,
                         "gridColumn":  2
                     },
                     {
                         "number":  89,
                         "symbol":  "Ac",
                         "name":  "Actinium",
                         "mass":  "227.02775",
                         "period":  7,
                         "group":  null,
                         "category":  "actinide",
                         "categoryName":  "Actinoid",
                         "state":  "fest",
                         "gridRow":  11,
                         "gridColumn":  3
                     },
                     {
                         "number":  90,
                         "symbol":  "Th",
                         "name":  "Thorium",
                         "mass":  "232.038",
                         "period":  7,
                         "group":  null,
                         "category":  "actinide",
                         "categoryName":  "Actinoid",
                         "state":  "fest",
                         "gridRow":  11,
                         "gridColumn":  4
                     },
                     {
                         "number":  91,
                         "symbol":  "Pa",
                         "name":  "Protactinium",
                         "mass":  "231.03588",
                         "period":  7,
                         "group":  null,
                         "category":  "actinide",
                         "categoryName":  "Actinoid",
                         "state":  "fest",
                         "gridRow":  11,
                         "gridColumn":  5
                     },
                     {
                         "number":  92,
                         "symbol":  "U",
                         "name":  "Uran",
                         "mass":  "238.0289",
                         "period":  7,
                         "group":  null,
                         "category":  "actinide",
                         "categoryName":  "Actinoid",
                         "state":  "fest",
                         "gridRow":  11,
                         "gridColumn":  6
                     },
                     {
                         "number":  93,
                         "symbol":  "Np",
                         "name":  "Neptunium",
                         "mass":  "237.048172",
                         "period":  7,
                         "group":  null,
                         "category":  "actinide",
                         "categoryName":  "Actinoid",
                         "state":  "fest",
                         "gridRow":  11,
                         "gridColumn":  7
                     },
                     {
                         "number":  94,
                         "symbol":  "Pu",
                         "name":  "Plutonium",
                         "mass":  "244.06420",
                         "period":  7,
                         "group":  null,
                         "category":  "actinide",
                         "categoryName":  "Actinoid",
                         "state":  "fest",
                         "gridRow":  11,
                         "gridColumn":  8
                     },
                     {
                         "number":  95,
                         "symbol":  "Am",
                         "name":  "Americium",
                         "mass":  "243.061380",
                         "period":  7,
                         "group":  null,
                         "category":  "actinide",
                         "categoryName":  "Actinoid",
                         "state":  "fest",
                         "gridRow":  11,
                         "gridColumn":  9
                     },
                     {
                         "number":  96,
                         "symbol":  "Cm",
                         "name":  "Curium",
                         "mass":  "247.07035",
                         "period":  7,
                         "group":  null,
                         "category":  "actinide",
                         "categoryName":  "Actinoid",
                         "state":  "fest",
                         "gridRow":  11,
                         "gridColumn":  10
                     },
                     {
                         "number":  97,
                         "symbol":  "Bk",
                         "name":  "Berkelium",
                         "mass":  "247.07031",
                         "period":  7,
                         "group":  null,
                         "category":  "actinide",
                         "categoryName":  "Actinoid",
                         "state":  "fest",
                         "gridRow":  11,
                         "gridColumn":  11
                     },
                     {
                         "number":  98,
                         "symbol":  "Cf",
                         "name":  "Californium",
                         "mass":  "251.07959",
                         "period":  7,
                         "group":  null,
                         "category":  "actinide",
                         "categoryName":  "Actinoid",
                         "state":  "fest",
                         "gridRow":  11,
                         "gridColumn":  12
                     },
                     {
                         "number":  99,
                         "symbol":  "Es",
                         "name":  "Einsteinium",
                         "mass":  "252.0830",
                         "period":  7,
                         "group":  null,
                         "category":  "actinide",
                         "categoryName":  "Actinoid",
                         "state":  "fest",
                         "gridRow":  11,
                         "gridColumn":  13
                     },
                     {
                         "number":  100,
                         "symbol":  "Fm",
                         "name":  "Fermium",
                         "mass":  "257.09511",
                         "period":  7,
                         "group":  null,
                         "category":  "actinide",
                         "categoryName":  "Actinoid",
                         "state":  "fest",
                         "gridRow":  11,
                         "gridColumn":  14
                     },
                     {
                         "number":  101,
                         "symbol":  "Md",
                         "name":  "Mendelevium",
                         "mass":  "258.09843",
                         "period":  7,
                         "group":  null,
                         "category":  "actinide",
                         "categoryName":  "Actinoid",
                         "state":  "fest",
                         "gridRow":  11,
                         "gridColumn":  15
                     },
                     {
                         "number":  102,
                         "symbol":  "No",
                         "name":  "Nobelium",
                         "mass":  "259.10100",
                         "period":  7,
                         "group":  null,
                         "category":  "actinide",
                         "categoryName":  "Actinoid",
                         "state":  "fest",
                         "gridRow":  11,
                         "gridColumn":  16
                     },
                     {
                         "number":  103,
                         "symbol":  "Lr",
                         "name":  "Lawrencium",
                         "mass":  "266.120",
                         "period":  7,
                         "group":  null,
                         "category":  "actinide",
                         "categoryName":  "Actinoid",
                         "state":  "fest",
                         "gridRow":  11,
                         "gridColumn":  17
                     },
                     {
                         "number":  104,
                         "symbol":  "Rf",
                         "name":  "Rutherfordium",
                         "mass":  "267.122",
                         "period":  7,
                         "group":  4,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  8,
                         "gridColumn":  4
                     },
                     {
                         "number":  105,
                         "symbol":  "Db",
                         "name":  "Dubnium",
                         "mass":  "268.126",
                         "period":  7,
                         "group":  5,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  8,
                         "gridColumn":  5
                     },
                     {
                         "number":  106,
                         "symbol":  "Sg",
                         "name":  "Seaborgium",
                         "mass":  "269.128",
                         "period":  7,
                         "group":  6,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  8,
                         "gridColumn":  6
                     },
                     {
                         "number":  107,
                         "symbol":  "Bh",
                         "name":  "Bohrium",
                         "mass":  "270.133",
                         "period":  7,
                         "group":  7,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  8,
                         "gridColumn":  7
                     },
                     {
                         "number":  108,
                         "symbol":  "Hs",
                         "name":  "Hassium",
                         "mass":  "269.1336",
                         "period":  7,
                         "group":  8,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  8,
                         "gridColumn":  8
                     },
                     {
                         "number":  109,
                         "symbol":  "Mt",
                         "name":  "Meitnerium",
                         "mass":  "277.154",
                         "period":  7,
                         "group":  9,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "fest",
                         "gridRow":  8,
                         "gridColumn":  9
                     },
                     {
                         "number":  110,
                         "symbol":  "Ds",
                         "name":  "Darmstadtium",
                         "mass":  "282.166",
                         "period":  7,
                         "group":  10,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "unbekannt",
                         "gridRow":  8,
                         "gridColumn":  10
                     },
                     {
                         "number":  111,
                         "symbol":  "Rg",
                         "name":  "Röntgenium",
                         "mass":  "282.169",
                         "period":  7,
                         "group":  11,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "unbekannt",
                         "gridRow":  8,
                         "gridColumn":  11
                     },
                     {
                         "number":  112,
                         "symbol":  "Cn",
                         "name":  "Copernicium",
                         "mass":  "286.179",
                         "period":  7,
                         "group":  12,
                         "category":  "transition",
                         "categoryName":  "Übergangsmetall",
                         "state":  "unbekannt",
                         "gridRow":  8,
                         "gridColumn":  12
                     },
                     {
                         "number":  113,
                         "symbol":  "Nh",
                         "name":  "Nihonium",
                         "mass":  "286.182",
                         "period":  7,
                         "group":  13,
                         "category":  "post-transition",
                         "categoryName":  "Metall",
                         "state":  "unbekannt",
                         "gridRow":  8,
                         "gridColumn":  13
                     },
                     {
                         "number":  114,
                         "symbol":  "Fl",
                         "name":  "Flerovium",
                         "mass":  "290.192",
                         "period":  7,
                         "group":  14,
                         "category":  "post-transition",
                         "categoryName":  "Metall",
                         "state":  "unbekannt",
                         "gridRow":  8,
                         "gridColumn":  14
                     },
                     {
                         "number":  115,
                         "symbol":  "Mc",
                         "name":  "Moscovium",
                         "mass":  "290.196",
                         "period":  7,
                         "group":  15,
                         "category":  "post-transition",
                         "categoryName":  "Metall",
                         "state":  "unbekannt",
                         "gridRow":  8,
                         "gridColumn":  15
                     },
                     {
                         "number":  116,
                         "symbol":  "Lv",
                         "name":  "Livermorium",
                         "mass":  "293.205",
                         "period":  7,
                         "group":  16,
                         "category":  "post-transition",
                         "categoryName":  "Metall",
                         "state":  "unbekannt",
                         "gridRow":  8,
                         "gridColumn":  16
                     },
                     {
                         "number":  117,
                         "symbol":  "Ts",
                         "name":  "Tenness",
                         "mass":  "294.211",
                         "period":  7,
                         "group":  17,
                         "category":  "halogen",
                         "categoryName":  "Halogen",
                         "state":  "unbekannt",
                         "gridRow":  8,
                         "gridColumn":  17
                     },
                     {
                         "number":  118,
                         "symbol":  "Og",
                         "name":  "Oganesson",
                         "mass":  "295.216",
                         "period":  7,
                         "group":  18,
                         "category":  "noble",
                         "categoryName":  "Edelgas",
                         "state":  "unbekannt",
                         "gridRow":  8,
                         "gridColumn":  18
                     }
                 ]
};
