(()=>{
const canvas=document.querySelector('#dnaCanvas'),ctx=canvas.getContext('2d'),select=document.querySelector('#viewMode'),toggle=document.querySelector('#rotationButton'),note=document.querySelector('#modeNote'),headerTitle=document.querySelector('#activeViewTitle'),viewLegend=document.querySelector('#viewLegend');
const sequence=[['A','T'],['G','C'],['T','A'],['C','G'],['A','T'],['G','C'],['C','G'],['T','A'],['A','T'],['C','G'],['G','C'],['T','A'],['G','C'],['A','T'],['C','G'],['T','A'],['A','T'],['G','C'],['C','G'],['A','T']],baseColors={A:'#d97862',T:'#d5ad49',G:'#588e78',C:'#6c8fb2'},atom={C:'#4f625d',N:'#557da0',O:'#cf695b',P:'#d69245'};
const copy={schematic:['Doppelhelix','Die reduzierte Darstellung zeigt die Gesamtform der DNA und die beiden gewundenen Rückgräte.'],bonds:['Basen & Wasserstoffbrücken','Adenin paart mit Thymin über zwei, Guanin mit Cytosin über drei schematisch dargestellte Wasserstoffbrücken.'],molecular:['Kugel-Stab-Modell','Desoxyribose und Phosphat wechseln sich im Rückgrat ab. Die Basen zeigen ihre schweren Atome; Wasserstoff ist wie in üblichen Strukturmodellen implizit. Positionen und Bindungswinkel sind didaktisch angenähert.'],spacefill:['Raumerfüllendes Modell','Die größeren Kugeln nähern die Van-der-Waals-Räume der Atome an. Desoxyribose und Phosphat bleiben als wechselnde Rückgratbausteine unterscheidbar; Wasserstoff ist nicht einzeln gezeichnet.']};
const baseLegend=[['#d97862','Adenin (A)','Purine · freie Base C₅H₅N₅'],['#d5ad49','Thymin (T)','Pyrimidin · freie Base C₅H₆N₂O₂'],['#588e78','Guanin (G)','Purine · freie Base C₅H₅N₅O'],['#6c8fb2','Cytosin (C)','Pyrimidin · freie Base C₄H₅N₃O']];
const atomLegend=[['#4f625d','Kohlenstoff (C)','Gerüst von Zucker und Basen','atom'],['#557da0','Stickstoff (N)','Bestandteil der Basen','atom'],['#cf695b','Sauerstoff (O)','Zucker, Phosphat und Basen','atom'],['#d69245','Phosphor (P)','Phosphatgruppen des Rückgrats','atom']];
const legends={schematic:[['#3f777b','Zucker-Phosphat-Rückgräte','Die beiden äußeren Stränge'],...baseLegend],bonds:[['#3f777b','Zucker-Phosphat-Rückgräte','Die beiden äußeren Stränge'],...baseLegend,['#43534f','Wasserstoffbrücken','A–T: 2 · G–C: 3','dashed']],molecular:[['#4f625d','2′-Desoxyribose','Fünfgliedriger Ring aus C und O','sugar'],['#d69245','Phosphat','Verbindet benachbarte Zucker','atom'],...atomLegend,...baseLegend],spacefill:[['#4f625d','2′-Desoxyribose','Fünfgliedriger Ring aus C und O','sugar'],['#d69245','Phosphat','Verbindet benachbarte Zucker','atom'],...atomLegend,...baseLegend]};
let width=0,height=0,dpr=1,yaw=-.34,zoom=1,auto=true,last=performance.now(),drag=null,pointers=new Map(),pinchDistance=0;const grooveAngle=144*Math.PI/180,twist=2*Math.PI/10.5,rise=32,radius=112;
function resize(){const r=canvas.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);width=r.width;height=r.height;canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
function camera(p){const c=Math.cos(yaw),s=Math.sin(yaw);return{x:p.x*c+p.z*s,y:p.y,z:-p.x*s+p.z*c}}
function project(p){const focal=820,depth=Math.max(380,focal+p.z),fit=Math.min(width/430,Math.max(.2,(height-84)/760)),scale=focal/depth*fit*zoom;return{x:width*.5+p.x*scale,y:height*.5+p.y*scale,z:p.z,scale}}
function model(){return sequence.map((pair,i)=>{const y=(i-(sequence.length-1)/2)*rise,a=i*twist,b=a+grooveAngle;return{pair,y,a,b,left:{x:Math.cos(a)*radius,y,z:Math.sin(a)*radius},right:{x:Math.cos(b)*radius,y,z:Math.sin(b)*radius}}})}
function primitives(mode){const data=model(),out=[],line=(a,b,color,w=2,dash=[])=>{const x=camera(a),y=camera(b);out.push({kind:'line',z:(x.z+y.z)/2,a:x,b:y,color,w,dash})},sphere=(p,r,color,label='')=>{const q=camera(p);out.push({kind:'sphere',z:q.z,p:q,r,color,label})},middle=(a,b)=>({x:(a.x+b.x)/2,y:(a.y+b.y)/2,z:(a.z+b.z)/2}),baseAtoms={A:['C','C','C','C','C','N','N','N','N','N'],T:['C','C','C','C','C','N','N','O','O'],G:['C','C','C','C','C','N','N','N','N','N','O'],C:['C','C','C','C','N','N','N','O']};
const drawBase=(center,angle,base)=>{const atoms=baseAtoms[base],tangent={x:-Math.sin(angle),z:Math.cos(angle)},purine=base==='A'||base==='G',points=atoms.map((element,k)=>{const ring=k<6?0:1,index=k<6?k:k-6,count=k<6?6:atoms.length-6,a=index*2*Math.PI/Math.max(3,count),offset=purine?(ring?10:-8):0;return{element,p:{x:center.x+tangent.x*(offset+Math.cos(a)*10),y:center.y+Math.sin(a)*10,z:center.z+tangent.z*(offset+Math.cos(a)*10)}}});for(let k=0;k<points.length;k++){const next=k+1<points.length?points[k+1]:null;if(next&&!(k===5&&purine)&&mode!=='spacefill')line(points[k].p,next.p,'#596661',1.5);sphere(points[k].p,mode==='spacefill'?9:5.2,atom[points[k].element])}sphere(center,mode==='spacefill'?11:8,baseColors[base],base)};
for(let i=1;i<data.length;i++){for(const side of ['left','right']){const a=data[i-1][side],b=data[i][side];if(mode==='molecular'||mode==='spacefill'){const ph=middle(a,b);line(a,ph,'#76837e',mode==='spacefill'?4:2.5);line(ph,b,'#76837e',mode==='spacefill'?4:2.5);sphere(ph,mode==='spacefill'?17:9,atom.P,'P')}else line(a,b,side==='left'?'#3f777b':'#275e67',mode==='schematic'?10:4)}}
data.forEach((p,i)=>{const [l,r]=p.pair,mid={x:(p.left.x+p.right.x)/2,y:p.y,z:(p.left.z+p.right.z)/2},inner=(start)=>({x:start.x+(mid.x-start.x)*.72,y:p.y,z:start.z+(mid.z-start.z)*.72}),il=inner(p.left),ir=inner(p.right);
if(mode==='schematic'){line(p.left,mid,baseColors[l],7);line(mid,p.right,baseColors[r],7);return}
if(mode==='bonds'){line(p.left,il,baseColors[l],6);line(ir,p.right,baseColors[r],6);sphere(il,13,baseColors[l],l);sphere(ir,13,baseColors[r],r);const n=l==='G'||l==='C'?3:2;for(let j=0;j<n;j++){const o=(j-(n-1)/2)*7;line({...il,y:p.y+o},{...ir,y:p.y+o},'#43534f',1.5,[4,4])}return}
for(const [start,end,base,angle] of [[p.left,il,l,p.a],[p.right,ir,r,p.b]]){const tangent={x:-Math.sin(angle),z:Math.cos(angle)},ring=Array.from({length:5},(_,k)=>{const q=angle+k*2*Math.PI/5-Math.PI/2;return{x:start.x+tangent.x*Math.cos(q)*13,y:p.y+Math.sin(q)*13,z:start.z+tangent.z*Math.cos(q)*13}});for(let k=0;k<5;k++){if(mode!=='spacefill')line(ring[k],ring[(k+1)%5],'#6e756f',2.3);sphere(ring[k],mode==='spacefill'?14:7,k===0?atom.O:atom.C)}if(mode!=='spacefill')line(ring[2],end,'#586762',2.2);drawBase(end,angle,base)}
if(mode!=='spacefill'){const n=l==='G'||l==='C'?3:2;for(let j=0;j<n;j++){const o=(j-(n-1)/2)*6;line({...il,y:p.y+o},{...ir,y:p.y+o},'#586762',1.25,[3,4])}}
});return out}
function draw(o){ctx.save();if(o.kind==='line'){const a=project(o.a),b=project(o.b),s=(a.scale+b.scale)/2;ctx.strokeStyle=o.color;ctx.lineWidth=Math.max(.7,o.w*s);ctx.lineCap='round';ctx.setLineDash(o.dash.map(v=>v*s));ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}else{const p=project(o.p),r=Math.max(1.6,o.r*p.scale),g=ctx.createRadialGradient(p.x-r*.34,p.y-r*.36,r*.08,p.x,p.y,r);g.addColorStop(0,'#fff');g.addColorStop(.25,o.color);g.addColorStop(1,o.color);ctx.fillStyle=g;ctx.strokeStyle='rgba(33,54,51,.25)';ctx.lineWidth=.8;ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();ctx.stroke();if(o.label&&r>8){ctx.fillStyle='#fff';ctx.font=`700 ${Math.max(8,r*.75)}px Arial`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(o.label,p.x,p.y)}}ctx.restore()}
function frame(time){ctx.clearRect(0,0,width,height);if(auto&&!drag)yaw+=(time-last)*.00016;last=time;primitives(select.value).sort((a,b)=>b.z-a.z).forEach(draw);requestAnimationFrame(frame)}
function applyMode(){const mode=select.value,c=copy[mode];headerTitle.textContent=c[0];note.textContent=c[1];viewLegend.innerHTML=legends[mode].map(([color,name,description,type=''])=>`<div class="legend-item"><i class="legend-mark ${type}" style="--mark:${color}"></i><span><strong>${name}</strong><small>${description}</small></span></div>`).join('')}
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1)drag={x:e.clientX,yaw};else{const p=[...pointers.values()];pinchDistance=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y)}});canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1&&drag)yaw=drag.yaw-(e.clientX-drag.x)*.008;else if(pointers.size===2){const p=[...pointers.values()],d=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);if(pinchDistance)zoom=Math.max(.62,Math.min(1.7,zoom*d/pinchDistance));pinchDistance=d}});function release(e){pointers.delete(e.pointerId);drag=null;pinchDistance=0}canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.62,Math.min(1.7,zoom*(e.deltaY>0?.92:1.08)))},{passive:false});toggle.onclick=()=>{auto=!auto;toggle.setAttribute('aria-pressed',String(auto))};select.onchange=applyMode;new ResizeObserver(resize).observe(canvas);resize();applyMode();requestAnimationFrame(frame);
})();
