const STORAGE_KEY = "schola-klassensprecher-wahl-v1";
const steps = [
  ["info","Aufgabe"],["principles","Grundsätze"],["leader","Wahlleitung"],["candidates","Kandidierende"],
  ["ballots","Wahlzettel"],["speaker","Sprecher"],["deputy","Stellvertretung"],["result","Ergebnis"]
];
const initialState = () => ({step:0,maxStep:0,boardMode:false,className:"",classSize:0,presentStudents:0,leader:"",secretary:"",leaderConfirmed:false,openVotingApproved:false,candidates:[],ballotCount:0,speaker:{counts:{},runoff:false,runoffIds:[],runoffCounts:{},winner:null,withdrawn:[]},deputy:{counts:{},runoff:false,runoffIds:[],runoffCounts:{},winner:null,withdrawn:[]},accepted:{speaker:false,deputy:false}});
let state = loadState();
const $ = s => document.querySelector(s);
const esc = value => String(value ?? "").replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const uid = () => (crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`);

function loadState(){try{return {...initialState(),...JSON.parse(localStorage.getItem(STORAGE_KEY)||"null")}}catch{return initialState()}}
function syncBoardMode(){document.body.classList.toggle("board-mode",!!state.boardMode);$("#boardModeButton").setAttribute("aria-pressed",String(!!state.boardMode));$("#boardModeButton").textContent=state.boardMode?"Tafelmodus beenden":"Tafelmodus"}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$("#saveState").textContent="Gespeichert";setTimeout(()=>$("#saveState").textContent="Automatisch gespeichert",900);renderSummary()}
function activeCandidates(role){const withdrawn=state[role]?.withdrawn||[];return state.candidates.filter(c=>c.accepted&&!withdrawn.includes(c.id)&&(role!=="deputy"||c.id!==state.speaker.winner))}
function winnerName(id){return state.candidates.find(c=>c.id===id)?.name||"–"}
function resultFor(role){const vote=state[role];const counts=vote.runoff?vote.runoffCounts:vote.counts;const ids=vote.runoff?vote.runoffIds:activeCandidates(role).map(c=>c.id);const ranked=ids.map(id=>[id,Number(counts[id]||0)]).sort((a,b)=>b[1]-a[1]);const valid=ranked.reduce((n,x)=>n+x[1],0),invalid=Number(counts.__invalid||0),cast=valid+invalid;return {ranked,valid,invalid,cast,total:valid,tie:ranked.length>1&&ranked[0][1]===ranked[1][1],over:cast>state.ballotCount}}
function updateAutomaticWinner(role){const vote=state[role],res=resultFor(role);if(res.over||!res.ranked.length){vote.winner=null;return}const top=res.ranked[0],countingComplete=res.cast===state.presentStudents,secured=top&&top[1]>state.presentStudents/2;vote.winner=!res.tie&&top[1]>0&&(countingComplete||secured)?top[0]:(vote.runoff&&vote.runoffIds.length===1?vote.runoffIds[0]:null);if(role==="speaker"&&state.deputy.winner===vote.winner)state.deputy.winner=null}
function majorityKind(role){const vote=state[role],res=resultFor(role),winner=vote.winner;if(!winner)return"";const counts=vote.runoff?vote.runoffCounts:vote.counts,winnerVotes=Number(counts[winner]||0);if(res.tie)return"Losentscheid bei Stimmengleichheit";if(res.valid===0)return"ohne Gegenkandidatur";if(winnerVotes===res.valid)return"einstimmig";if(winnerVotes*3>=res.valid*2)return"qualifizierte Mehrheit (mind. ⅔)";if(winnerVotes>res.valid/2)return"absolute Mehrheit";return"einfache Mehrheit"}
function hasQuorum(){return state.classSize>0&&state.presentStudents<=state.classSize&&state.presentStudents>=state.classSize/2}
function canAdvance(){if(state.step===2)return !!state.className.trim()&&!!state.leader.trim()&&!!state.secretary.trim()&&state.leaderConfirmed&&hasQuorum();if(state.step===3)return activeCandidates("speaker").length>=2;if(state.step===5)return !!state.speaker.winner&&!resultFor("speaker").over;if(state.step===6)return !!state.deputy.winner&&!resultFor("deputy").over;if(state.step===7)return state.accepted.speaker&&state.accepted.deputy;return true}

function renderNav(){const nav=$("#stepNav");nav.innerHTML=steps.map((s,i)=>`<button type="button" class="step-button ${i===state.step?"active":""} ${i<state.step?"done":""}" data-step="${i}" ${i===state.step?'aria-current="step"':""} ${i>state.maxStep?"disabled":""}><span>${i<state.step?"✓":String(i+1).padStart(2,"0")}</span><b>${s[1]}</b></button>`).join("");nav.querySelectorAll("[data-step]").forEach(b=>b.onclick=()=>{state.step=Number(b.dataset.step);save();render()})}
function panelHead(kicker,title,text){return `<header class="panel-head"><span class="eyebrow">${kicker}</span><h2>${title}</h2><p>${text}</p></header>`}
function render(){renderNav();const renderers=[renderInfo,renderPrinciples,renderLeader,renderCandidates,renderBallots,()=>renderVote("speaker"),()=>renderVote("deputy"),renderResult];$("#stepPanel").innerHTML=renderers[state.step]();bindPanel();const finished=state.step===7&&state.accepted.speaker&&state.accepted.deputy;$("#backButton").disabled=state.step===0;$("#nextButton").textContent=finished?"Abgeschlossen":state.step===7?"Wahl abschließen":"Weiter";$("#nextButton").disabled=finished||!canAdvance();const over=(state.step===5&&resultFor("speaker").over)||(state.step===6&&resultFor("deputy").over);$("#flowHint").textContent=finished?"Die Wahl ist abgeschlossen. Das Protokoll kann jetzt gedruckt werden.":canAdvance()?"":(over?"Mehr Stimmen als anwesende Wahlberechtigte: Bitte Zählstand korrigieren.":({2:"Bitte Wahlausschuss und Anwesenheit vollständig eintragen und die Bestellung bestätigen.",3:"Mindestens zwei angenommene Kandidaturen erforderlich.",5:"Eindeutige höchste Stimmenzahl oder abgeschlossene Stichwahl erforderlich.",6:"Eindeutige höchste Stimmenzahl oder Losentscheid erforderlich.",7:"Beide Gewählten müssen die Wahl annehmen."}[state.step]||""));renderSummary()}
function renderInfo(){return panelHead("Schritt 1","Eine Stimme für die Klasse","Klassensprecherinnen und Klassensprecher vertreten die Interessen ihrer Klasse. Sie bringen Anliegen ein und wirken als gewählte Schülervertretung auch in schulischen Gremien mit.")+`<div class="info-grid"><section class="info-card"><h3>Interessen vertreten</h3><p>Sie sammeln Anliegen, Wünsche und Probleme aus der Klasse und vertreten diese gegenüber Lehrkräften und Schule.</p></section><section class="info-card"><h3>In Konferenzen mitwirken</h3><p>Sie vertreten die Schülerinnen und Schüler im Rahmen der gesetzlichen Mitwirkungsrechte, etwa in Klassenkonferenzen.</p></section><section class="info-card"><h3>Vermitteln</h3><p>Sie können zwischen Klasse und Lehrkräften vermitteln, Informationen weitergeben und gemeinsame Lösungen unterstützen.</p></section><section class="info-card"><h3>Verantwortung übernehmen</h3><p>Das Amt ist kein Beliebtheitspreis: Zuhören, Zuverlässigkeit, Fairness und Mut zur eigenen Stimme sind wichtig.</p></section></div><a class="source-link" href="https://www.landesrecht-mv.de/bsmv/document/jlr-NNLMV000070FBNN00000000264" target="_blank" rel="noreferrer">Schulgesetz M-V, § 81 Abs. 2 öffnen ↗</a>`}
function renderPrinciples(){const cards=[["Allgemein","Alle Schülerinnen und Schüler der Klasse dürfen wählen und kandidieren. Die Klassenlehrkraft ist nicht wahlberechtigt."],["Frei","Niemand darf zu einer bestimmten Wahlentscheidung gedrängt werden."],["Gleich","Jede Person hat genau eine Stimme; jede Stimme zählt gleich viel."],["Geheim","Die Wahl ist grundsätzlich geheim. Offen per Handzeichen darf nur gewählt werden, wenn alle anwesenden Wahlberechtigten zustimmen."]];return panelHead("Schritt 2","Grundsätze für eine faire Wahl","Die Schulmitwirkungsverordnung Mecklenburg-Vorpommern regelt Wahlberechtigung, Wahlform, Wahlausschuss und Ergebnisermittlung verbindlich.")+`<div class="principle-grid">${cards.map((c,i)=>`<section class="principle-card"><span class="candidate-index">${i+1}</span><h3>${c[0]}</h3><p>${c[1]}</p></section>`).join("")}</div><a class="source-link" href="https://www.regierung-mv.de/static/Regierungsportal/Justizministerium/Inhalte/Rechtliches/GVOBI.M-V/Dateien/2015/GVO_2015-16.pdf#page=8" target="_blank" rel="noreferrer">Schulmitwirkungsverordnung M-V, §§ 2–5 öffnen ↗</a>`}
function renderLeader(){const quorum=hasQuorum(),entered=state.classSize>0&&state.presentStudents>=0,percent=state.classSize?Math.round(state.presentStudents/state.classSize*100):0;return panelHead("Schritt 3","Wahlausschuss und Wahlberechtigung","Der Wahlausschuss besteht mindestens aus Wahlleitung und Schriftführung. Kandidierende dürfen ihm nicht angehören. Für diese Wahlversammlung muss mindestens die Hälfte der Wahlberechtigten anwesend sein.")+`<div class="field-grid form-card"><label class="field"><span>Klasse</span><input id="className" value="${esc(state.className)}" placeholder="z. B. 7b"></label><label class="field"><span>Name der Wahlleitung</span><input id="leader" value="${esc(state.leader)}" placeholder="Vor- und Nachname"></label><label class="field"><span>Name der Schriftführung</span><input id="secretary" value="${esc(state.secretary)}" placeholder="Vor- und Nachname"></label><label class="field"><span>Klassenstärke / Wahlberechtigte</span><input id="classSize" type="number" min="1" max="100" value="${state.classSize||""}" placeholder="z. B. 28"></label><label class="field"><span>Anwesende Wahlberechtigte</span><input id="presentStudents" type="number" min="0" max="${state.classSize||100}" value="${state.presentStudents||""}" placeholder="z. B. 24"></label><div class="quorum-status ${quorum?"quorum-ok":"quorum-missing"}"><strong>${quorum?"Wahl zulässig":"Wahl noch nicht zulässig"}</strong><span>${entered?`${state.presentStudents} von ${state.classSize} anwesend (${percent} %).`:"Wahlberechtigte und Anwesenheit eintragen."} Erforderlich ist mindestens die Hälfte.</span></div><label class="leader-choice wide"><input id="leaderConfirmed" type="checkbox" ${state.leaderConfirmed?"checked":""}><span>Wahlleitung und Schriftführung wurden durch Zuruf bestellt.</span></label></div>`}
function renderCandidates(){return panelHead("Schritt 4","Wer stellt sich zur Wahl?","Vorschläge können aus der Klasse oder von den Schülerinnen und Schülern selbst kommen. Eine Kandidatur zählt erst nach Zustimmung. Wer möchte, kann seine Bereitschaft mündlich ganz kurz begründen.")+`<div class="candidate-form candidate-name-form"><label class="field"><span>Name</span><input id="newName" placeholder="Name der Person"></label><button id="addCandidate" class="primary" type="button">Hinzufügen</button></div><div class="candidate-list">${state.candidates.length?state.candidates.map((c,i)=>`<div class="candidate-row candidate-name-row" data-id="${c.id}"><span class="candidate-index">${i+1}</span><input class="candidate-name" value="${esc(c.name)}" aria-label="Name"><label class="accept-check"><input class="candidate-accepted" type="checkbox" ${c.accepted?"checked":""}> Kandidatur angenommen</label><button class="icon-button remove-candidate" type="button" aria-label="Kandidatur entfernen">×</button></div>`).join(""):`<p class="empty-card">Noch keine Kandidierenden eingetragen.</p>`}</div>`}
function renderBallots(){const candidates=activeCandidates("speaker");return panelHead("Schritt 5","Wahlform festlegen",`Die Wahl ist grundsätzlich geheim. Eine offene Abstimmung ist nur zulässig, wenn alle ${state.presentStudents} anwesenden Wahlberechtigten zustimmen.`)+`<div class="ballot-setup"><section class="form-card attendance-card"><span class="eyebrow">Wahlform</span><strong>${state.openVotingApproved?"Offene Abstimmung":"Geheime Wahl"}</strong><label class="leader-choice voting-consent"><input id="openVotingApproved" type="checkbox" ${state.openVotingApproved?"checked":""}><span>Alle anwesenden Wahlberechtigten stimmen einer offenen Abstimmung per Handzeichen zu.</span></label><div class="button-row"><button id="printSpeaker" class="primary" type="button">Wahlzettel drucken</button></div></section><section class="ballot-preview"><h3>Klassensprecher-Wahl · ${esc(state.className||"Klasse")}</h3><p>Eine Stimme · Bitte genau einen Namen ankreuzen.</p><ul>${candidates.map(c=>`<li>○ &nbsp; ${esc(c.name)}</li>`).join("")}</ul></section></div>`}
function runoffIdsFor(res){if(res.cast!==state.presentStudents||!res.tie||!res.ranked.length)return[];const top=res.ranked[0][1];return res.ranked.filter(x=>x[1]===top&&top>0).map(x=>x[0])}
function rowState(id,index,res,vote){if(res.over)return"over-count";if(vote.winner===id)return"leading";if(!res.tie&&res.ranked[0]?.[0]===id&&res.ranked[0][1]>0)return"front-runner";if(runoffIdsFor(res).includes(id))return"runoff-candidate";if(res.cast<state.presentStudents&&res.tie&&res.ranked[0]?.[1]>0&&res.ranked[0][1]===Number((vote.runoff?vote.runoffCounts:vote.counts)[id]||0))return"current-tie";return""}
function rowBadge(id,res,vote){if(res.over)return`<span class="status-badge status-error">Zu viele Stimmen</span>`;if(vote.winner===id)return`<span class="status-badge status-success">Gewählt</span>`;if(!res.tie&&res.ranked[0]?.[0]===id&&res.ranked[0][1]>0)return`<span class="status-badge status-front">Liegt vorn</span>`;if(runoffIdsFor(res).includes(id))return`<span class="status-badge status-runoff">Stichwahl</span>`;if(res.cast<state.presentStudents&&res.tie&&res.ranked[0]?.[1]>0&&res.ranked[0][1]===Number((vote.runoff?vote.runoffCounts:vote.counts)[id]||0))return`<span class="status-badge status-neutral">Gleichauf</span>`;return""}
function renderVote(role){const label=role==="speaker"?"Klassensprecher":"Stellvertretung",vote=state[role],candidates=activeCandidates(role),ids=vote.runoff?vote.runoffIds:candidates.map(c=>c.id),counts=vote.runoff?vote.runoffCounts:vote.counts,res=resultFor(role);return panelHead(role==="speaker"?"Schritt 6":"Schritt 7",`${label} auszählen`,vote.runoff?"Stichwahl: Zählen Sie die Stimmen der verbliebenen Kandidierenden. Eine Kandidatur kann vor der Stichwahl zurückgezogen werden.":"Tippen Sie für jede Stimme einmal auf Plus. Eine offene Abstimmung ist möglich; auf Wunsch kann ein Wahlzettel gedruckt werden.")+`<div class="button-row vote-print-actions"><button class="secondary print-current-ballot" data-role="${role}" type="button">${vote.runoff?"Stichwahlzettel":"Wahlzettel"} drucken</button></div>${res.over?`<p class="count-error count-error-top">Zu viele Stimmen: Es wurden mehr Stimmen als anwesende Schülerinnen und Schüler gezählt. Bitte korrigieren Sie die Auszählung.</p>`:""}<div class="count-list">${ids.map((id,i)=>{const c=state.candidates.find(x=>x.id===id);return `<div class="count-row ${rowState(id,i,res,vote)}"><div class="count-name"><strong>${esc(c?.name)}</strong>${rowBadge(id,res,vote)}</div><div class="counter"><button data-count="${role}" data-id="${id}" data-delta="-1" aria-label="Eine Stimme abziehen">−</button><output>${Number(counts[id]||0)}</output><button data-count="${role}" data-id="${id}" data-delta="1" aria-label="Eine Stimme hinzufügen">+</button></div>${vote.runoff?`<button class="quiet withdraw-candidate" data-role="${role}" data-id="${id}" type="button">Kandidatur zurückziehen</button>`:""}</div>`}).join("")}<div class="count-row invalid-row ${res.over?"over-count":""}"><div class="count-name"><strong>Ungültige Stimme</strong>${res.over?`<span class="status-badge status-error">Zu viele Stimmen</span>`:""}</div><div class="counter"><button data-count="${role}" data-id="__invalid" data-delta="-1" aria-label="Eine ungültige Stimme abziehen">−</button><output>${res.invalid}</output><button data-count="${role}" data-id="__invalid" data-delta="1" aria-label="Eine ungültige Stimme hinzufügen">+</button></div></div></div><div class="vote-summary ${res.over?"over-summary":""}" aria-live="polite"><span class="metric"><strong>${res.valid}</strong> gültig</span><span class="metric"><strong>${res.invalid}</strong> ungültig</span><span class="metric"><strong>${res.cast} / ${state.presentStudents}</strong> abgegeben</span>${vote.winner?`<span class="metric result-metric">Ergebnis: <strong>${esc(winnerName(vote.winner))}</strong><em>· ${esc(majorityKind(role))}</em></span>`:""}</div>${res.over?"":renderRunoff(role,res)}`}
function renderRunoff(role,res){const vote=state[role];if(vote.runoff&&vote.runoffIds.length===1)return `<section class="runoff-box"><p>Die anderen Kandidaturen wurden zurückgezogen. Die verbleibende Person ist gewählt.</p></section>`;if(vote.runoff&&res.tie&&res.cast>0)return `<section class="runoff-box"><p>Auch die Stichwahl ist unentschieden. Nun entscheidet das von der Wahlleitung zu ziehende Los.</p><div class="button-row"><button class="primary random-winner" data-role="${role}">Los ziehen</button><button class="secondary cancel-runoff" data-role="${role}">Zur ersten Auszählung</button></div></section>`;if(vote.runoff)return `<section class="runoff-box"><p>Die Stichwahl läuft. Wer die meisten gültigen Stimmen erhält, ist gewählt.</p><button class="secondary cancel-runoff" data-role="${role}">Zur ersten Auszählung</button></section>`;if(res.tie&&runoffIdsFor(res).length>=2)return `<section class="runoff-box"><p>Die gelb markierten Kandidierenden haben gleich viele Stimmen und treten zur Stichwahl an.</p><button class="primary start-runoff" data-role="${role}">Stichwahl starten</button></section>`;return ""}
function renderResult(){const s=winnerName(state.speaker.winner),d=winnerName(state.deputy.winner),done=state.accepted.speaker&&state.accepted.deputy;return panelHead("Schritt 8","Wahl annehmen und erklären","Zum Abschluss werden beide Gewählten gefragt, ob sie die Wahl annehmen. Danach kann die Wahlleitung das Ergebnis erklären und eine kurze oder vollständige Protokollform ausdrucken.")+`<div class="result-stack"><section class="result-card"><span class="role">Klassensprecher</span><h3>${esc(s)}</h3><p>Gewählt im ersten Wahlgang oder in der Stichwahl.</p><label class="acceptance"><input data-accept="speaker" type="checkbox" ${state.accepted.speaker?"checked":""}> ${esc(s)} nimmt die Wahl an.</label></section><section class="result-card"><span class="role">Stellvertretung</span><h3>${esc(d)}</h3><p>Gewählt aus den übrigen Kandidierenden.</p><label class="acceptance"><input data-accept="deputy" type="checkbox" ${state.accepted.deputy?"checked":""}> ${esc(d)} nimmt die Wahl an.</label></section></div><p class="notice">Hinweis: Die Namensliste der anwesenden Wahlberechtigten zur Wahlniederschrift nehmen.</p>${done?`<p class="declaration">Damit erkläre ich <strong>${esc(s)}</strong> zum Klassensprecher / zur Klassensprecherin und <strong>${esc(d)}</strong> zur Stellvertretung der Klasse <strong>${esc(state.className)}</strong>. Herzlichen Glückwunsch!</p><div class="button-row protocol-actions"><button class="primary print-protocol" data-protocol="short" type="button">Kurzprotokoll drucken</button><button class="secondary print-protocol" data-protocol="long" type="button">Langprotokoll drucken</button></div>`:""}`}

function bindPanel(){const inputSave=(sel,key,transform=v=>v)=>{const el=$(sel);if(el)el.oninput=()=>{state[key]=transform(el.type==="checkbox"?el.checked:el.value);save();$("#nextButton").disabled=!canAdvance()}};inputSave("#className","className");inputSave("#leader","leader");inputSave("#secretary","secretary");inputSave("#leaderConfirmed","leaderConfirmed");inputSave("#openVotingApproved","openVotingApproved");const bindAttendance=(sel,key)=>{const el=$(sel);if(!el)return;el.oninput=()=>{state[key]=Math.max(0,Math.min(100,Number(el.value)||0));state.presentStudents=Math.min(state.presentStudents,state.classSize||100);state.ballotCount=state.presentStudents;save();$("#nextButton").disabled=!canAdvance()};el.onchange=render};bindAttendance("#classSize","classSize");bindAttendance("#presentStudents","presentStudents");
  $("#addCandidate")?.addEventListener("click",()=>{const name=$("#newName").value.trim();if(!name){$("#newName").focus();return}state.candidates.push({id:uid(),name,accepted:true});save();render()});
  $("#newName")?.addEventListener("keydown",e=>{if(e.key==="Enter")$("#addCandidate").click()});
  document.querySelectorAll(".candidate-row").forEach(row=>{const c=state.candidates.find(x=>x.id===row.dataset.id);row.querySelector(".candidate-name").onchange=e=>{c.name=e.target.value.trim();save()};row.querySelector(".candidate-accepted").onchange=e=>{c.accepted=e.target.checked;save();render()};row.querySelector(".remove-candidate").onclick=()=>{state.candidates=state.candidates.filter(x=>x.id!==c.id);save();render()}});
  $("#printSpeaker")?.addEventListener("click",()=>printBallots("speaker"));$("#printDeputy")?.addEventListener("click",()=>printBallots("deputy"));
  document.querySelectorAll("[data-count]").forEach(b=>b.onclick=()=>{const role=b.dataset.count,vote=state[role],bucket=vote.runoff?vote.runoffCounts:vote.counts,id=b.dataset.id;bucket[id]=Math.max(0,Number(bucket[id]||0)+Number(b.dataset.delta));updateAutomaticWinner(role);save();render()});
  document.querySelectorAll(".start-runoff").forEach(b=>b.onclick=()=>{const role=b.dataset.role,res=resultFor(role);state[role].runoff=true;state[role].runoffIds=runoffIdsFor(res);state[role].runoffCounts={};state[role].winner=null;save();render()});
  document.querySelectorAll(".cancel-runoff").forEach(b=>b.onclick=()=>{Object.assign(state[b.dataset.role],{runoff:false,runoffIds:[],runoffCounts:{},winner:null});save();render()});
  document.querySelectorAll(".random-winner").forEach(b=>b.onclick=()=>{const ids=state[b.dataset.role].runoffIds;state[b.dataset.role].winner=ids[Math.floor(Math.random()*ids.length)];save();render()});
  document.querySelectorAll(".print-current-ballot").forEach(b=>b.onclick=()=>printBallots(b.dataset.role,state[b.dataset.role].runoff,true));
  document.querySelectorAll(".withdraw-candidate").forEach(b=>b.onclick=()=>{const role=b.dataset.role,vote=state[role],id=b.dataset.id;if(!confirm(`${winnerName(id)} zieht die Kandidatur für diese Wahl zurück?`))return;vote.withdrawn=vote.withdrawn||[];if(!vote.withdrawn.includes(id))vote.withdrawn.push(id);vote.runoffIds=vote.runoffIds.filter(x=>x!==id);delete vote.runoffCounts[id];updateAutomaticWinner(role);save();render()});
  document.querySelectorAll(".print-protocol").forEach(b=>b.onclick=()=>printProtocol(b.dataset.protocol));
  document.querySelectorAll("[data-accept]").forEach(b=>b.onchange=()=>{state.accepted[b.dataset.accept]=b.checked;save();render()})
}
function ballotLayout(candidateCount){const layouts=[{amount:12,columns:3,optionColumns:1},{amount:10,columns:2,optionColumns:2},{amount:9,columns:3,optionColumns:1},{amount:8,columns:2,optionColumns:2},{amount:6,columns:2,optionColumns:2},{amount:4,columns:2,optionColumns:2},{amount:2,columns:2,optionColumns:2}];for(const layout of layouts){const pageRows=Math.ceil(layout.amount/layout.columns),optionRows=Math.ceil(candidateCount/layout.optionColumns),requiredMm=18+optionRows*5,availableMm=(283-(pageRows-1)*3)/pageRows;if(requiredMm<=availableMm)return layout}return layouts.at(-1)}
function printBallots(role,runoff=false,compact=false){const vote=state[role],roleName=role==="speaker"?"Klassensprecher-Wahl":"Wahl der Stellvertretung",ids=runoff?vote.runoffIds:activeCandidates(role).map(c=>c.id),candidates=ids.map(id=>state.candidates.find(c=>c.id===id)).filter(Boolean),count=state.ballotCount,layout=ballotLayout(candidates.length),perPage=layout.amount,isCompact=perPage>=6,layoutClass=layout.columns===3?"layout-3col":"layout-2col",ballots=Array.from({length:count},()=>`<article class="print-ballot ${isCompact?"compact-ballot":""}"><h1>${runoff?"Stichwahl · ":""}${roleName}</h1><p>Klasse ${esc(state.className)} · Eine Stimme</p><ul>${candidates.map(c=>`<li><i></i>${esc(c.name)}</li>`).join("")}</ul></article>`);const pages=[];for(let i=0;i<ballots.length;i+=perPage)pages.push(`<section class="print-page ${isCompact?"compact-page ":""}${layoutClass} slots-${perPage}">${ballots.slice(i,i+perPage).join("")}</section>`);$("#printArea").innerHTML=pages.join("");window.print()}
function protocolTable(role,counts,title,ids){const ranked=ids.map(id=>[id,Number(counts[id]||0)]).sort((a,b)=>b[1]-a[1]),invalid=Number(counts.__invalid||0),cast=ranked.reduce((n,x)=>n+x[1],0)+invalid;return `<h2>${title}</h2><table><thead><tr><th>Kandidatur</th><th>Stimmen</th></tr></thead><tbody>${ranked.map(x=>`<tr><td>${esc(winnerName(x[0]))}</td><td>${x[1]}</td></tr>`).join("")}<tr><td>Ungültige Stimmen</td><td>${invalid}</td></tr><tr><th>Abgegebene Stimmen</th><th>${cast}</th></tr></tbody></table>`}
function protocolRows(role){const vote=state[role],label=role==="speaker"?"Klassensprecherwahl":"Wahl der Stellvertretung",firstIds=state.candidates.filter(c=>c.accepted&&(role!=="deputy"||c.id!==state.speaker.winner)).map(c=>c.id);return protocolTable(role,vote.counts,label+" · erster Wahlgang",firstIds)+(vote.runoff?protocolTable(role,vote.runoffCounts,label+" · Stichwahl",vote.runoffIds):"")}
function shortProtocolResult(role){const vote=state[role],res=resultFor(role),winner=vote.winner,winnerVotes=Number((vote.runoff?vote.runoffCounts:vote.counts)[winner]||0),candidateCount=role==="speaker"?state.candidates.filter(c=>c.accepted).length:state.candidates.filter(c=>c.accepted&&c.id!==state.speaker.winner).length,label=role==="speaker"?"Klassensprecher/in":"Stellvertretung";return `<section class="short-result"><span>${label}</span><h2>${esc(winnerName(winner))}</h2><dl><div><dt>Kandidierende</dt><dd>${candidateCount}</dd></div><div><dt>Stimmenergebnis</dt><dd>${winnerVotes} von ${res.valid} gültigen Stimmen</dd></div><div><dt>Mehrheitsart</dt><dd>${esc(majorityKind(role))}</dd></div></dl></section>`}
function printProtocol(form="long"){const date=new Intl.DateTimeFormat("de-DE",{dateStyle:"long"}).format(new Date()),isShort=form==="short",details=isShort?`<p class="protocol-caveat">Kurzfassung zur Übersicht – die vollständige Wahlniederschrift ist die Langform.</p><div class="short-results">${shortProtocolResult("speaker")}${shortProtocolResult("deputy")}</div>`:`${protocolRows("speaker")}${protocolRows("deputy")}`,result=isShort?"":`<section class="protocol-result"><p>Gewählt und die Wahl angenommen:</p><p><strong>Klassensprecher/in:</strong> ${esc(winnerName(state.speaker.winner))} · ${esc(majorityKind("speaker"))}</p><p><strong>Stellvertretung:</strong> ${esc(winnerName(state.deputy.winner))} · ${esc(majorityKind("deputy"))}</p></section>`;$("#printArea").innerHTML=`<article class="protocol ${isShort?"protocol-short":"protocol-long"}"><header><span>Schola · ${isShort?"Kurzfassung":"Wahlniederschrift"}</span><h1>Protokoll der Klassensprecher-Wahl</h1></header><dl><div><dt>Klasse</dt><dd>${esc(state.className)}</dd></div><div><dt>Datum</dt><dd>${date}</dd></div><div><dt>Wahlleitung</dt><dd>${esc(state.leader)}</dd></div><div><dt>Schriftführung</dt><dd>${esc(state.secretary)}</dd></div><div><dt>Wahlberechtigte</dt><dd>${state.classSize}</dd></div><div><dt>Anwesende Wahlberechtigte</dt><dd>${state.presentStudents}</dd></div><div><dt>Wahlform</dt><dd>${state.openVotingApproved?"offen, einstimmig zugestimmt":"geheim"}</dd></div></dl>${details}<section class="protocol-closing">${result}<div class="signature"><span>Ort, Datum</span><span>Wahlleitung: ${esc(state.leader)}</span><span>Schriftführung: ${esc(state.secretary)}</span></div></section></article>`;window.print()}
function renderSummary(){const names={0:"Information",1:"Wahlgrundsätze",2:"Wahl vorbereiten",3:"Kandidaturen",4:"Wahlzettel",5:"Sprecherwahl",6:"Wahl der Stellvertretung",7:"Wahlabschluss"};$("#summaryTitle").textContent=names[state.step];$("#summaryClass").textContent=state.className||"–";$("#summaryLeader").textContent=state.leader||"–";$("#summarySecretary").textContent=state.secretary||"–";$("#summaryQuorum").textContent=state.classSize?`${state.presentStudents}/${state.classSize} · ${hasQuorum()?"ja":"nein"}`:"–";$("#summaryCandidates").textContent=activeCandidates("speaker").length;$("#summarySpeaker").textContent=winnerName(state.speaker.winner);$("#summaryDeputy").textContent=winnerName(state.deputy.winner)}
$("#backButton").onclick=()=>{if(state.step>0){state.step--;save();render()}};$("#nextButton").onclick=()=>{if(!canAdvance())return;if(state.step<7){state.maxStep=Math.max(state.maxStep,state.step+1);state.step++;save();render()}else{$("#flowHint").textContent="Die Wahl ist vollständig dokumentiert."}};$("#boardModeButton").onclick=()=>{state.boardMode=!state.boardMode;syncBoardMode();save()};$("#resetButton").onclick=()=>{if(confirm("Die aktuelle Wahl und alle Zählstände wirklich löschen?")){state=initialState();localStorage.removeItem(STORAGE_KEY);syncBoardMode();render()}};syncBoardMode();render();
