(() => {
  'use strict';
  const TYPES=[['people','Bevölkerung / Volk','V','#47707a'],['electorate','Wahlkörper','W','#47707a'],['assembly','Vertretungskörper','Vk','#b38a35'],['parliament','Parlament / Kammer','P','#b38a35'],['head','Staatsoberhaupt','S','#8b5a72'],['government','Regierung / Regierungschef','R','#c76842'],['administration','Verwaltung / Ressort','A','#c76842'],['court','Gericht / Verfassungsgericht','G','#557060'],['control','Kontroll- oder Wahlorgan','K','#557060'],['council','Rat / Versammlung','Rt','#7b6c48'],['office','Amt / Einzelorgan','A','#8b5a72'],['territory','Territoriale Einheit','T','#527b65'],['other','Sonstige Institution','?','#65736e']];
  const RELATIONS={
    'Besetzung und Legitimation':['wählt','ernennt','nominiert','schlägt vor','bestätigt','bestellt','entsendet','beruft'],
    'Kontrolle und Verantwortung':['kontrolliert','beaufsichtigt','prüft','genehmigt','muss berichten an','ist verantwortlich gegenüber','kann beanstanden'],
    'Amtsbeendigung':['kann abberufen','kann entlassen','kann abwählen','kann auflösen','kann Amtsenthebung einleiten','kann Amtsenthebung beschließen'],
    'Gesetzgebung':['besitzt Gesetzesinitiative gegenüber','beschließt','muss zustimmen','kann widersprechen','besitzt Vetorecht gegenüber','kann Veto überstimmen','fertigt aus','verkündet'],
    'Exekutive und Hierarchie':['leitet','weist an','untersteht','gehört an','führt aus','delegiert Kompetenz an','übt Kompetenz gemeinsam aus'],
    'Gerichtliche Beziehungen':['prüft Entscheidung von','kann Entscheidung aufheben','prüft Verfassungsmäßigkeit','ist Rechtsmittelinstanz für'],
    'Territoriale Beziehungen':['ist Teil von','besteht aus','ist vertreten in','entsendet in','besitzt Autonomie gegenüber','unterliegt Aufsicht durch','teilt Kompetenz mit']
  };
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`;
  const blank=()=>({version:1,title:'Mein Staatsmodell',mode:'basic',elements:[],relations:[],groups:[],view:{}});
  let model=load(), selected=null, pending=null, drag=null, saveTimer;
  const els={canvas:$('#canvas'),nodes:$('#nodeLayer'),groups:$('#groupLayer'),edges:$('#edges'),empty:$('#emptyState'),nodeForm:$('#nodeInspector'),edgeForm:$('#edgeInspector'),groupForm:$('#groupInspector')};
  function load(){try{const data=JSON.parse(localStorage.getItem('schola-staatsbaukasten-v1'));return data?.version===1?data:blank()}catch{return blank()}}
  function save(){clearTimeout(saveTimer);$('#saveState').textContent='Wird gespeichert …';saveTimer=setTimeout(()=>{localStorage.setItem('schola-staatsbaukasten-v1',JSON.stringify(model));$('#saveState').textContent='Automatisch gespeichert'},250)}
  function init(){
    $('#elementPalette').innerHTML=TYPES.map(t=>`<button class="palette-item" draggable="true" data-type="${t[0]}" style="--type-color:${t[3]}"><span class="type-icon">${t[2]}</span><span>${t[1]}</span></button>`).join('');
    const options=TYPES.map(t=>`<option value="${t[0]}">${t[1]}</option>`).join('');els.nodeForm.elements.type.innerHTML=options;
    const relOptions=Object.entries(RELATIONS).map(([c,rs])=>`<optgroup label="${c}">${rs.map(r=>`<option>${r}</option>`).join('')}</optgroup>`).join('');els.edgeForm.elements.relation.innerHTML=relOptions;
    $('#relationCategory').innerHTML=Object.keys(RELATIONS).map(c=>`<option>${c}</option>`).join('');fillRelationTypes();
    bind();$('#modelTitle').value=model.title;setMode(model.mode,false);render();
  }
  function bind(){
    $$('.palette-item').forEach(b=>{b.addEventListener('click',()=>addNode(b.dataset.type));b.addEventListener('dragstart',e=>e.dataTransfer.setData('text/type',b.dataset.type))});
    els.canvas.addEventListener('dragover',e=>e.preventDefault());els.canvas.addEventListener('drop',e=>{e.preventDefault();const type=e.dataTransfer.getData('text/type');if(type){const p=point(e);addNode(type,p.x,p.y)}});
    els.canvas.addEventListener('pointerdown',e=>{if(e.target===els.canvas){select(null)}});els.canvas.addEventListener('pointermove',move);els.canvas.addEventListener('pointerup',endDrag);
    $$('.mode-switch button').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('#modelTitle').oninput=e=>{model.title=e.target.value;save()};
    $('#addGroupButton').onclick=()=>{model.groups.push({id:uid('group'),label:'Institutionelle Ebene',x:60,y:60,w:360,h:240});select({kind:'group',id:model.groups.at(-1).id});render();save()};
    $('#relationCategory').onchange=fillRelationTypes;$('#confirmRelation').onclick=e=>{e.preventDefault();confirmRelation()};
    $('#relationDialog').addEventListener('close',()=>{if(pending){pending=null;renderEdges()}});
    [els.nodeForm,els.edgeForm,els.groupForm].forEach(f=>f.addEventListener('input',updateFromInspector));$$('[data-delete]').forEach(b=>b.onclick=()=>removeSelected());
    $('#newButton').onclick=()=>{if(confirm('Das aktuelle Modell löschen und neu beginnen?')){model=blank();selected=null;$('#modelTitle').value=model.title;setMode('basic',false);render();save()}};
    $('#exportButton').onclick=exportModel;$('#importButton').onclick=()=>$('#importInput').click();$('#importInput').onchange=importModel;
    $('#dataButton').onclick=()=>{$('#dataPreview').textContent=JSON.stringify(model,null,2);$('#dataDialog').showModal()};$('#fitButton').onclick=fit;
    window.addEventListener('resize',renderEdges);document.addEventListener('keydown',e=>{if((e.key==='Delete'||e.key==='Backspace')&&selected&&!/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))removeSelected()});
  }
  function addNode(type,x,y){const rect=els.canvas.getBoundingClientRect();const t=TYPES.find(t=>t[0]===type);model.elements.push({id:uid('element'),type,label:t[1].split(' / ')[0],properties:{},visual:{x:x??Math.max(100,rect.width/2+(Math.random()-.5)*120),y:y??Math.max(80,rect.height/2+(Math.random()-.5)*120)}});selected={kind:'node',id:model.elements.at(-1).id};render();save()}
  function point(e){const r=els.canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
  function startNodeDrag(e,id){if(e.target.classList.contains('port'))return;select({kind:'node',id});const n=model.elements.find(n=>n.id===id);drag={kind:'node',id,dx:point(e).x-n.visual.x,dy:point(e).y-n.visual.y};e.currentTarget.setPointerCapture(e.pointerId)}
  function startConnect(e,id){e.stopPropagation();const p=point(e);pending={source:id,x:p.x,y:p.y};drag={kind:'connect'};renderEdges();e.currentTarget.setPointerCapture(e.pointerId)}
  function move(e){if(!drag)return;const p=point(e);if(drag.kind==='node'){const n=model.elements.find(n=>n.id===drag.id);n.visual.x=Math.max(75,Math.min(els.canvas.clientWidth-75,p.x-drag.dx));n.visual.y=Math.max(35,Math.min(els.canvas.clientHeight-35,p.y-drag.dy));renderNodes();renderEdges()}else if(drag.kind==='group'){const g=model.groups.find(g=>g.id===drag.id);g.x=p.x-drag.dx;g.y=p.y-drag.dy;renderGroups()}else if(drag.kind==='connect'){pending.x=p.x;pending.y=p.y;renderEdges()}}
  function endDrag(e){if(!drag)return;if(drag.kind==='connect'){const target=e.target.closest('.node')?.dataset.id;if(target&&target!==pending.source){pending.target=target;openRelation()}else pending=null;renderEdges()}save();drag=null}
  function openRelation(){const s=model.elements.find(n=>n.id===pending.source),t=model.elements.find(n=>n.id===pending.target);$('#relationSentence').textContent=`${s.label} → … → ${t.label}`;$('#relationDialog').showModal()}
  function fillRelationTypes(){const list=RELATIONS[$('#relationCategory').value]||[];$('#relationType').innerHTML=list.map(r=>`<option>${r}</option>`).join('')}
  function confirmRelation(){model.relations.push({id:uid('relation'),source:pending.source,target:pending.target,type:$('#relationType').value,category:$('#relationCategory').value,properties:{},visual:{}});selected={kind:'edge',id:model.relations.at(-1).id};pending=null;$('#relationDialog').close();render();save()}
  function render(){renderGroups();renderNodes();renderEdges();renderInspector();els.empty.hidden=model.elements.length>0;$('#nodeCount').textContent=model.elements.length;$('#edgeCount').textContent=model.relations.length}
  function renderNodes(){els.nodes.innerHTML=model.elements.map(n=>{const t=TYPES.find(t=>t[0]===n.type)||TYPES.at(-1);return `<article class="node ${selected?.kind==='node'&&selected.id===n.id?'selected':''}" data-id="${n.id}" style="left:${n.visual.x}px;top:${n.visual.y}px;--type-color:${t[3]}" tabindex="0"><span class="node-type">${esc(t[1])}</span><strong class="node-label">${esc(n.label)}</strong><button class="port" aria-label="Beziehung von ${esc(n.label)} aus erstellen" title="Verbindung ziehen"></button></article>`}).join('');
    $$('.node').forEach(n=>{n.onpointerdown=e=>startNodeDrag(e,n.dataset.id);n.onclick=e=>{e.stopPropagation();select({kind:'node',id:n.dataset.id})};n.querySelector('.port').onpointerdown=e=>startConnect(e,n.dataset.id)});
  }
  function renderGroups(){els.groups.innerHTML=model.groups.map(g=>`<div class="group ${selected?.kind==='group'&&selected.id===g.id?'selected':''}" data-id="${g.id}" style="left:${g.x}px;top:${g.y}px;width:${g.w}px;height:${g.h}px"><span>${esc(g.label)}</span></div>`).join('');$$('.group').forEach(el=>{el.onpointerdown=e=>{select({kind:'group',id:el.dataset.id});const g=model.groups.find(g=>g.id===el.dataset.id),p=point(e);drag={kind:'group',id:g.id,dx:p.x-g.x,dy:p.y-g.y};el.setPointerCapture(e.pointerId)};el.onclick=e=>{e.stopPropagation();select({kind:'group',id:el.dataset.id})}})}
  function renderEdges(){const curves=model.relations.map(r=>{const s=model.elements.find(n=>n.id===r.source),t=model.elements.find(n=>n.id===r.target);if(!s||!t)return'';const dx=t.visual.x-s.visual.x,dy=t.visual.y-s.visual.y,len=Math.hypot(dx,dy)||1,a={x:s.visual.x+dx/len*78,y:s.visual.y+dy/len*38},b={x:t.visual.x-dx/len*82,y:t.visual.y-dy/len*40},mx=(a.x+b.x)/2,my=(a.y+b.y)/2-8,path=`M ${a.x} ${a.y} Q ${mx} ${my-14} ${b.x} ${b.y}`,sel=selected?.kind==='edge'&&selected.id===r.id;return `<path class="edge-hit" data-id="${r.id}" d="${path}"/><path class="edge-path ${sel?'edge-selected':''}" d="${path}"/><text class="edge-label" x="${mx}" y="${my}" text-anchor="middle">${esc(r.type)}</text>`}).join('');const draft=pending?`<path class="drag-line" d="M ${model.elements.find(n=>n.id===pending.source)?.visual.x||0} ${model.elements.find(n=>n.id===pending.source)?.visual.y||0} L ${pending.x} ${pending.y}"/>`:'';els.edges.innerHTML=curves+draft;$$('.edge-hit').forEach(p=>p.onclick=e=>{e.stopPropagation();select({kind:'edge',id:p.dataset.id})})}
  function select(s){selected=s;render()}
  function renderInspector(){const forms=[els.nodeForm,els.edgeForm,els.groupForm];forms.forEach(f=>f.hidden=true);$('#inspectorEmpty').hidden=!!selected;if(!selected)return;const obj=getSelected();if(!obj){selected=null;return renderInspector()}const form=selected.kind==='node'?els.nodeForm:selected.kind==='edge'?els.edgeForm:els.groupForm;form.hidden=false;$('#inspectorTitle').textContent=selected.kind==='node'?'Element':selected.kind==='edge'?'Beziehung':'Institutionelle Ebene';if(selected.kind==='node'){form.elements.label.value=obj.label;form.elements.type.value=obj.type;['level','branch','term','members','structure'].forEach(k=>form.elements[k].value=obj.properties[k]||'');form.elements.independent.checked=!!obj.properties.independent}else if(selected.kind==='edge'){form.elements.relation.value=obj.type;['decision','majority','conditions'].forEach(k=>form.elements[k].value=obj.properties[k]||'');const s=model.elements.find(n=>n.id===obj.source),t=model.elements.find(n=>n.id===obj.target);$('#edgeStatement').textContent=`${s?.label} → ${obj.type} → ${t?.label}`}else form.elements.label.value=obj.label}
  function updateFromInspector(e){if(!selected)return;const obj=getSelected(),name=e.target.name;if(selected.kind==='node'){if(name==='label'||name==='type')obj[name]=e.target.value;else obj.properties[name]=e.target.type==='checkbox'?e.target.checked:e.target.value}else if(selected.kind==='edge'){if(name==='relation')obj.type=e.target.value;else obj.properties[name]=e.target.value}else obj.label=e.target.value;renderNodes();renderGroups();renderEdges();renderInspector();save()}
  function getSelected(){return selected?.kind==='node'?model.elements.find(x=>x.id===selected.id):selected?.kind==='edge'?model.relations.find(x=>x.id===selected.id):model.groups.find(x=>x.id===selected.id)}
  function removeSelected(){if(!selected)return;if(selected.kind==='node'){model.elements=model.elements.filter(x=>x.id!==selected.id);model.relations=model.relations.filter(x=>x.source!==selected.id&&x.target!==selected.id)}else if(selected.kind==='edge')model.relations=model.relations.filter(x=>x.id!==selected.id);else model.groups=model.groups.filter(x=>x.id!==selected.id);selected=null;render();save()}
  function setMode(mode,persist=true){model.mode=mode;$$('.mode-switch button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$$('.advanced-fields').forEach(x=>x.hidden=mode!=='advanced');if(persist)save()}
  function exportModel(){const blob=new Blob([JSON.stringify(model,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(model.title||'staatsmodell').toLowerCase().replace(/[^a-z0-9äöüß]+/gi,'-')+'.staatsmodell.json';a.click();URL.revokeObjectURL(a.href)}
  function importModel(e){const file=e.target.files[0];if(!file)return;file.text().then(text=>{const data=JSON.parse(text);if(data.version!==1||!Array.isArray(data.elements)||!Array.isArray(data.relations))throw Error();model=data;selected=null;$('#modelTitle').value=model.title;setMode(model.mode,false);render();save()}).catch(()=>alert('Diese Datei enthält kein gültiges Staatsmodell.'));e.target.value=''}
  function fit(){if(!model.elements.length)return;const xs=model.elements.map(n=>n.visual.x),ys=model.elements.map(n=>n.visual.y),cx=(Math.min(...xs)+Math.max(...xs))/2,cy=(Math.min(...ys)+Math.max(...ys))/2,dx=els.canvas.clientWidth/2-cx,dy=els.canvas.clientHeight/2-cy;model.elements.forEach(n=>{n.visual.x+=dx;n.visual.y+=dy});render();save()}
  function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  init();
})();
