(() => {
  'use strict';
  const TYPES=[['people','Bevölkerung / Volk','V','#47707a'],['electorate','Wahlkörper','W','#47707a'],['assembly','Vertretungskörper','Vk','#b38a35'],['parliament','Parlament / Kammer','P','#b38a35'],['head','Staatsoberhaupt','S','#8b5a72'],['government','Regierung / Regierungschef','R','#c76842'],['administration','Verwaltung / Ressort','A','#c76842'],['court','Gericht / Verfassungsgericht','G','#557060'],['control','Kontroll- oder Wahlorgan','K','#557060'],['council','Rat / Versammlung','Rt','#7b6c48'],['office','Amt / Einzelorgan','A','#8b5a72'],['territory','Territoriale Einheit','T','#527b65'],['other','Sonstige Institution','?','#65736e']];
  const TYPE_INFO={
    people:['Bezeichnet die Menschen, von denen politische Herrschaft ausgeht oder auf die sie sich bezieht.','Nutze diesen Typ für das Volk als Träger von Souveränität. Wahlberechtigte können davon getrennt als Wahlkörper modelliert werden.','Staatsvolk, Bürgerschaft, Untertanen eines historischen Gemeinwesens'],
    electorate:['Umfasst die Personen oder Gremien, die an einer bestimmten Wahl beteiligt sind.','Modelliere damit präzise, wer ein Organ wählt – besonders wenn Wahlkörper und Gesamtbevölkerung nicht identisch sind.','Wahlberechtigte, Wahlmännerkollegium, Fürstenkollegium'],
    assembly:['Ein aus mehreren Personen bestehendes Organ, das Gruppen oder Interessen vertritt.','Geeignet für Vertretungen, die nicht genauer als Parlament oder Kammer bestimmt werden sollen.','Nationalversammlung, Ständeversammlung, Volkskongress'],
    parliament:['Ein kollegiales Vertretungsorgan mit Aufgaben insbesondere in Gesetzgebung, Kontrolle und politischer Willensbildung.','Mehrere Kammern werden als getrennte Elemente angelegt und über ihre Beziehungen modelliert.','Bundestag, Senat, Unterhaus, Bundesrat'],
    head:['Das oberste repräsentative Amt eines Staates; seine politische Macht kann sehr unterschiedlich sein.','Eigenschaften wie Amtszeit oder monarchische Struktur gehören an das Element, Wahl oder Ernennung an die Beziehung.','Bundespräsident, Monarchin, Präsident'],
    government:['Das politische Leitungsorgan der Exekutive oder die Person an seiner Spitze.','Regierung und Regierungschef können gemeinsam oder als getrennte Elemente modelliert werden, wenn ihre Beziehungen wichtig sind.','Kabinett, Ministerrat, Bundeskanzler, Premierministerin'],
    administration:['Organe, die politische Entscheidungen vorbereiten, konkretisieren oder ausführen.','Nutze diesen Typ für nachgeordnete Exekutivstrukturen; Weisungs- und Aufsichtsverhältnisse werden als Beziehungen dargestellt.','Ministerium, Behörde, Ressortleitung, Präfektur'],
    court:['Ein unabhängiges oder institutionell abgegrenztes Organ zur Rechtsprechung und rechtlichen Prüfung.','Spezielle Zuständigkeiten wie Verfassungsprüfung werden als Eigenschaft oder Beziehung erfasst.','Verfassungsgericht, Supreme Court, Verwaltungsgericht'],
    control:['Ein spezialisiertes Organ für Aufsicht, Prüfung, Wahlen oder institutionelle Kontrolle.','Verwende es, wenn die besondere Kontroll- oder Verfahrensfunktion wichtiger ist als eine Zuordnung zu den drei Gewalten.','Rechnungshof, Wahlkommission, Ombudsstelle'],
    council:['Ein kollegiales Beratungs-, Entscheidungs- oder Koordinationsorgan.','Der Typ eignet sich für institutionell eigenständige Räte, die weder Parlament noch Regierung sind.','Staatsrat, Kronrat, Ältestenrat, Revolutionsrat'],
    office:['Ein einzelnes Amt oder Organ, das keiner spezielleren Kategorie entspricht.','Benenne die konkrete Funktion frei und bilde Besetzung, Unterstellung oder Verantwortung über Beziehungen ab.','Gouverneur, Reichskanzler, Hoher Kommissar'],
    territory:['Eine räumlich abgegrenzte politische Körperschaft oder staatliche Ebene.','Territoriale Zugehörigkeit, Autonomie und Kompetenzteilung werden als gerichtete Beziehungen modelliert.','Gliedstaat, Provinz, Region, Kommune'],
    other:['Eine Institution, die sich fachlich keiner vorhandenen Grundkategorie sinnvoll zuordnen lässt.','Nutze diesen offenen Typ sparsam und benenne das Element so präzise, dass seine institutionelle Rolle verständlich bleibt.','Historisches Sonderorgan, religiöse Autorität, informelles Machtzentrum']
  };
  const RELATIONS={
    'Besetzung und Legitimation':['wählt','ernennt','nominiert','schlägt vor','bestätigt','bestellt','entsendet','beruft'],
    'Kontrolle und Verantwortung':['kontrolliert','beaufsichtigt','prüft','genehmigt','muss berichten an','ist verantwortlich gegenüber','kann beanstanden'],
    'Amtsbeendigung':['kann abberufen','kann entlassen','kann abwählen','kann auflösen','kann Amtsenthebung einleiten','kann Amtsenthebung beschließen'],
    'Gesetzgebung':['besitzt Gesetzesinitiative gegenüber','beschließt','muss zustimmen','kann widersprechen','besitzt Vetorecht gegenüber','kann Veto überstimmen','fertigt aus','verkündet'],
    'Exekutive und Hierarchie':['leitet','weist an','untersteht','gehört an','führt aus','delegiert Kompetenz an','übt Kompetenz gemeinsam aus'],
    'Gerichtliche Beziehungen':['prüft Entscheidung von','kann Entscheidung aufheben','prüft Verfassungsmäßigkeit','ist Rechtsmittelinstanz für'],
    'Territoriale Beziehungen':['ist Teil von','besteht aus','ist vertreten in','entsendet in','besitzt Autonomie gegenüber','unterliegt Aufsicht durch','teilt Kompetenz mit']
  };
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`;
  const blank=()=>({version:1,title:'Mein Staatsmodell',mode:'basic',elements:[],relations:[],groups:[],view:{}});
  let model=load(), selected=null, pending=null, drag=null, guides=[], saveTimer;
  const els={canvas:$('#canvas'),viewport:$('#canvasViewport'),nodes:$('#nodeLayer'),groups:$('#groupLayer'),edges:$('#edges'),guides:$('#guides'),empty:$('#emptyState'),paletteInfo:$('#paletteInspector'),nodeForm:$('#nodeInspector'),edgeForm:$('#edgeInspector'),groupForm:$('#groupInspector')};
  function load(){try{const data=JSON.parse(localStorage.getItem('schola-staatsbaukasten-v1'));return data?.version===1?data:blank()}catch{return blank()}}
  function save(){clearTimeout(saveTimer);remember();$('#saveState').textContent='Wird gespeichert …';saveTimer=setTimeout(()=>{try{localStorage.setItem('schola-staatsbaukasten-v1',JSON.stringify(model));$('#saveState').textContent='Lokal gespeichert'}catch{$('#saveState').textContent='Speicher voll – bitte exportieren'}},250)}
  function init(){
    $('#elementPalette').innerHTML=TYPES.map(t=>`<button class="palette-item" draggable="true" data-type="${t[0]}" style="--type-color:${t[3]}"><span class="type-icon">${t[2]}</span><span>${t[1]}</span></button>`).join('');
    const options=TYPES.map(t=>`<option value="${t[0]}">${t[1]}</option>`).join('');els.nodeForm.elements.type.innerHTML=options;
    const relOptions=Object.entries(RELATIONS).map(([c,rs])=>`<optgroup label="${c}">${rs.map(r=>`<option>${r}</option>`).join('')}</optgroup>`).join('');els.edgeForm.elements.relation.innerHTML=relOptions;
    $('#relationCategory').innerHTML=Object.keys(RELATIONS).map(c=>`<option>${c}</option>`).join('');fillRelationTypes();
    bind();$('#modelTitle').value=model.title;setMode(model.mode,false);setZoom(model.view?.zoom||1,false);render();
  }
  function bind(){
    const menu=$('#sideMenu'),overlay=$('#menuOverlay'),menuButton=$('#menuButton');
    const setMenu=open=>{menu.classList.toggle('is-open',open);menu.setAttribute('aria-hidden',String(!open));menu.inert=!open;overlay.hidden=!open;menuButton.setAttribute('aria-expanded',String(open))};
    menuButton.onclick=()=>setMenu(true);$('#menuCloseButton').onclick=()=>setMenu(false);overlay.onclick=()=>setMenu(false);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.classList.contains('is-open'))setMenu(false)});
    const canvasCenter=()=>{const r=els.canvas.getBoundingClientRect();return{clientX:r.left+r.width/2,clientY:r.top+r.height/2}};
    $('#zoomOutButton').onclick=()=>setZoom(currentZoom()-.1,true,canvasCenter());$('#zoomInButton').onclick=()=>setZoom(currentZoom()+.1,true,canvasCenter());els.canvas.addEventListener('wheel',e=>{e.preventDefault();setZoom(currentZoom()+(e.deltaY<0?.1:-.1),true,e)},{passive:false});
    $$('.palette-item').forEach(b=>{b.addEventListener('click',()=>select({kind:'palette',id:b.dataset.type}));b.addEventListener('dragstart',e=>{e.dataTransfer.effectAllowed='copy';e.dataTransfer.setData('text/type',b.dataset.type)})});
    els.canvas.addEventListener('dragover',e=>{e.preventDefault();e.dataTransfer.dropEffect='copy'});els.canvas.addEventListener('drop',e=>{e.preventDefault();const type=e.dataTransfer.getData('text/type');if(type){const p=point(e);addNode(type,p.x,p.y)}});
    els.canvas.addEventListener('pointerdown',e=>{if(e.button===1){e.preventDefault();e.stopPropagation();drag={kind:'pan',startX:e.clientX,startY:e.clientY,originX:model.view?.panX||0,originY:model.view?.panY||0};els.canvas.classList.add('is-panning');els.canvas.setPointerCapture(e.pointerId);return}if(e.target===els.canvas||e.target===els.viewport){if(pending){pending=null;renderEdges()}select(null)}},true);els.canvas.addEventListener('pointermove',move);els.canvas.addEventListener('pointerup',endDrag);els.canvas.addEventListener('pointercancel',endDrag);els.canvas.addEventListener('auxclick',e=>{if(e.button===1)e.preventDefault()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&pending){pending=null;renderEdges()}});
    $$('.mode-switch button').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('#modelTitle').oninput=e=>{model.title=e.target.value;save()};
    $('#addGroupButton').onclick=()=>{model.groups.push({id:uid('group'),label:'Institutionelle Ebene',kind:'level',x:60,y:60,w:720,h:280});select({kind:'group',id:model.groups.at(-1).id});render();save()};
    $('#relationCategory').onchange=fillRelationTypes;$('#confirmRelation').onclick=e=>{e.preventDefault();confirmRelation()};
    $('#relationDialog').addEventListener('close',()=>{if(pending){pending=null;renderEdges()}});
    [els.nodeForm,els.edgeForm,els.groupForm].forEach(f=>f.addEventListener('input',updateFromInspector));$$('[data-delete]').forEach(b=>b.onclick=()=>removeSelected());
    $$('[data-layout]').forEach(b=>b.onclick=()=>arrangeGroup(b.dataset.layout));
    $('#newButton').onclick=()=>{if(confirm('Das aktuelle Modell löschen und neu beginnen?')){model=blank();selected=null;$('#modelTitle').value=model.title;setMode('basic',false);setZoom(1,false);render();save()}};
    $('#viewButton').onclick=toggleDiagramView;$('#exportButton').onclick=openExport;$('#exportSvgButton').onclick=exportSvg;$('#printPdfButton').onclick=printPdf;$('#exportJsonButton').onclick=exportModel;$('#importButton').onclick=()=>$('#importInput').click();$('#importInput').onchange=importModel;
    $('#dataButton').onclick=()=>{$('#dataPreview').textContent=JSON.stringify(model,null,2);$('#dataDialog').showModal()};$('#fitButton').onclick=fit;
    window.addEventListener('resize',renderEdges);document.addEventListener('keydown',e=>{if((e.key==='Delete'||e.key==='Backspace')&&selected&&!/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))removeSelected()});
  }
  function addNode(type,x,y){const rect=els.canvas.getBoundingClientRect(),zoom=currentZoom(),panX=model.view?.panX||0,panY=model.view?.panY||0;const t=TYPES.find(t=>t[0]===type);model.elements.push({id:uid('element'),type,label:t[1].split(' / ')[0],properties:{},visual:{x:x??Math.max(100,(rect.width/2-panX)/zoom+(Math.random()-.5)*120),y:y??Math.max(80,(rect.height/2-panY)/zoom+(Math.random()-.5)*120)}});const node=model.elements.at(-1);assignNodeToArea(node);selected={kind:'node',id:node.id};render();save()}
  function currentZoom(){return model.view?.zoom||1}
  function applyView(){const zoom=currentZoom(),panX=model.view?.panX||0,panY=model.view?.panY||0;els.viewport.style.width='4000px';els.viewport.style.height='3000px';els.viewport.style.transform=`translate(${panX}px,${panY}px) scale(${zoom})`;$('#zoomValue').value=`${Math.round(zoom*100)} %`}
  function setZoom(value,persist=true,anchor=null){const oldZoom=currentZoom(),zoom=Math.max(.1,Math.min(2.5,Math.round(value*100)/100));model.view=model.view||{};if(anchor&&zoom!==oldZoom){const r=els.canvas.getBoundingClientRect(),localX=anchor.clientX-r.left,localY=anchor.clientY-r.top,panX=model.view.panX||0,panY=model.view.panY||0,worldX=(localX-panX)/oldZoom,worldY=(localY-panY)/oldZoom;model.view.panX=localX-worldX*zoom;model.view.panY=localY-worldY*zoom}model.view.zoom=zoom;applyView();if(persist)save()}
  function point(e){const r=els.canvas.getBoundingClientRect(),zoom=currentZoom(),panX=model.view?.panX||0,panY=model.view?.panY||0;return{x:(e.clientX-r.left-panX)/zoom,y:(e.clientY-r.top-panY)/zoom}}
  function startNodeDrag(e,id){selected={kind:'node',id};$$('.node').forEach(el=>el.classList.toggle('selected',el.dataset.id===id));renderInspector();renderEdges();const n=model.elements.find(n=>n.id===id);if(n.parentId)return;drag={kind:'node',id,dx:point(e).x-n.visual.x,dy:point(e).y-n.visual.y};e.currentTarget.setPointerCapture(e.pointerId)}
  function startConnect(e,id,chosenPort){e.preventDefault();e.stopPropagation();const p=point(e),port=chosenPort||DiagramGeometry.snapPort(nodeBox(model.elements.find(n=>n.id===id)),DiagramGeometry.nearestPort(nodeBox(model.elements.find(n=>n.id===id)),p)),at=DiagramGeometry.anchor(nodeBox(model.elements.find(n=>n.id===id)),port);if(pending){if(id!==pending.source){pending.target=id;pending.targetPort=port;pending.x=at.x;pending.y=at.y;openRelation()}else{pending=null;renderEdges()}return}pending={source:id,sourcePort:port,startX:at.x,startY:at.y,x:at.x,y:at.y};renderEdges()}
  function startNodeInteraction(e,id){if(e.button!==0)return;if(hoverPort?.id===id)startConnect(e,id,hoverPort.port);else{if(pending){pending=null;renderEdges()}startNodeDrag(e,id)}}
  function showConnectionTool(e){const id=e.currentTarget.dataset.id;if(hoverNodeId!==id){hoverNodeId=id;renderEndpointHandles()}}
  function move(e){if(drag?.kind==='corner'){const r=model.relations.find(x=>x.id===drag.id),p=DiagramGeometry.magneticPoint(point(e),[drag.points[drag.index-1],drag.points[drag.index+1]],currentZoom());r.visual=r.visual||{};r.visual.manualRoute=drag.points.map((v,i)=>i===drag.index?p:{...v});r.visual.freeRoute=true;renderEdges();return}if(drag?.kind==='segment'){const p=point(e),r=model.relations.find(x=>x.id===drag.id);r.visual=r.visual||{};r.visual.manualRoute=DiagramGeometry.moveSegment(drag.points,drag.index,p[drag.axis]-drag.start);renderEdges();return}if(drag?.kind==='endpoint'){const r=model.relations.find(x=>x.id===drag.id),n=model.elements.find(x=>x.id===r[drag.end]);r.visual=r.visual||{};r.visual[drag.end+'Port']=DiagramGeometry.snapPort(nodeBox(n),DiagramGeometry.nearestPort(nodeBox(n),point(e)));renderEdges();return}if(!drag){const p=point(e);const previous=hoverPort,previousNode=hoverNodeId;hoverPort=findHoverPort(p);hoverNodeId=hoverPort?.id||null;if(pending){const at=hoverPort?.point||p;pending.x=at.x;pending.y=at.y;renderEdges()}else if(previous?.id!==hoverPort?.id||previous?.port.side!==hoverPort?.port.side||previous?.port.t!==hoverPort?.port.t||previousNode!==hoverNodeId)renderEndpointHandles();return}if(drag.kind==='pan'){model.view.panX=drag.originX+e.clientX-drag.startX;model.view.panY=drag.originY+e.clientY-drag.startY;applyView();return}if(drag.kind==='edge-label'){const r=model.relations.find(x=>x.id===drag.id);r.visual=r.visual||{};r.visual.labelPosition=Math.max(.02,Math.min(.98,DiagramGeometry.project(routeRelation(r),point(e))));const p=pointOnRoute(routeRelation(r),r.visual.labelPosition),label=[...$$('.edge-label')].find(x=>x.dataset.id===r.id);if(label){label.setAttribute('x',p.x);label.setAttribute('y',p.y-7)}els.edgeForm.elements.labelPosition.value=r.visual.labelPosition;return}const p=point(e);if(drag.kind==='node'){const n=model.elements.find(n=>n.id===drag.id),snapped=snapPosition(n,Math.max(75,Math.min(3925,p.x-drag.dx)),Math.max(35,Math.min(2965,p.y-drag.dy)));n.visual.x=snapped.x;n.visual.y=snapped.y;updateNodePositions();renderEdges()}else if(drag.kind==='group'){const g=model.groups.find(g=>g.id===drag.id),nx=p.x-drag.dx,ny=p.y-drag.dy,shiftX=nx-drag.lastX,shiftY=ny-drag.lastY;g.x=nx;g.y=ny;drag.lastX=nx;drag.lastY=ny;const ids=descendantGroupIds(g.id);model.groups.filter(x=>x.id!==g.id&&ids.includes(x.id)).forEach(x=>{x.x+=shiftX;x.y+=shiftY});model.elements.filter(n=>!n.parentId&&ids.includes(n.groupId)).forEach(n=>{n.visual.x+=shiftX;n.visual.y+=shiftY});updateGroupPositions();updateNodePositions();renderEdges()}else if(drag.kind==='group-resize'){const g=model.groups.find(g=>g.id===drag.id);g.w=Math.max(180,p.x-g.x);g.h=Math.max(100,p.y-g.y);updateGroupPositions()}}
  function endDrag(){if(!drag)return;if(drag.kind==='pan')els.canvas.classList.remove('is-panning');if(drag.kind==='node'){const n=model.elements.find(n=>n.id===drag.id);if(n)assignNodeToArea(n)}guides=[];renderGuides();save();drag=null;renderInspector()}
  function openRelation(){const s=model.elements.find(n=>n.id===pending.source),t=model.elements.find(n=>n.id===pending.target);$('#relationSentence').textContent=`${s.label} → … → ${t.label}`;$('#relationDialog').showModal()}
  function fillRelationTypes(){const list=RELATIONS[$('#relationCategory').value]||[];$('#relationType').innerHTML=list.map(r=>`<option>${r}</option>`).join('')}
  function confirmRelation(){if(!pending?.target)return;model.relations.push({id:uid('relation'),source:pending.source,target:pending.target,type:$('#relationType').value,category:$('#relationCategory').value,properties:{},visual:{sourcePort:pending.sourcePort,targetPort:pending.targetPort}});selected={kind:'edge',id:model.relations.at(-1).id};pending=null;$('#relationDialog').close();render();save()}
  function render(){renderGroups();renderNodes();renderEdges();renderInspector();els.empty.hidden=model.elements.length>0;$('#nodeCount').textContent=model.elements.length;$('#edgeCount').textContent=model.relations.length}
  function childrenOf(id){return model.elements.filter(n=>n.parentId===id)}
  function nodeSize(n){const children=childrenOf(n.id),width=Math.max(150,Number(n.visual.width)||180,...children.map(c=>nodeSize(c).w+28)),lines=wrapLabel(n.label,width-24);return{w:width,ownH:Math.max(Number(n.visual.height)||54,lines.length*19+24),h:Math.max(Number(n.visual.height)||54,lines.length*19+24)+(children.length?children.reduce((sum,c)=>sum+nodeSize(c).h+10,0)+12:0)}}
  function nodePosition(n){if(!n.parentId)return{x:n.visual.x,y:n.visual.y};const parent=model.elements.find(p=>p.id===n.parentId);if(!parent)return{x:n.visual.x,y:n.visual.y};const pp=nodePosition(parent),ps=nodeSize(parent),siblings=childrenOf(parent.id),index=siblings.findIndex(c=>c.id===n.id),head=Math.max(Number(parent.visual.height)||54,wrapLabel(parent.label,ps.w-24).length*19+24);return{x:pp.x,y:pp.y-ps.h/2+head+12+siblings.slice(0,index).reduce((sum,c)=>sum+nodeSize(c).h+10,0)+nodeSize(n).h/2}}
  function assignNodeToArea(n){if(n.parentId)return;const p=nodePosition(n),matches=model.groups.filter(g=>p.x>=g.x&&p.x<=g.x+g.w&&p.y>=g.y&&p.y<=g.y+g.h).sort((a,b)=>a.w*a.h-b.w*b.h);n.groupId=matches[0]?.id||''}
  function snapPosition(n,x,y){const threshold=8/currentZoom(),others=model.elements.filter(o=>o.id!==n.id&&!o.parentId),xs=others.map(o=>nodePosition(o).x),ys=others.map(o=>nodePosition(o).y),nearX=xs.reduce((best,v)=>Math.abs(v-x)<Math.abs(best-x)?v:best,Infinity),nearY=ys.reduce((best,v)=>Math.abs(v-y)<Math.abs(best-y)?v:best,Infinity);guides=[];if(Number.isFinite(nearX)&&Math.abs(nearX-x)<=threshold){x=nearX;guides.push({axis:'x',value:x})}if(Number.isFinite(nearY)&&Math.abs(nearY-y)<=threshold){y=nearY;guides.push({axis:'y',value:y})}renderGuides();return{x,y}}
  function renderGuides(){els.guides.innerHTML=guides.map(g=>g.axis==='x'?`<path class="alignment-guide" d="M ${g.value} 0 V 3000"/>`:`<path class="alignment-guide" d="M 0 ${g.value} H 4000"/>`).join('')}
  function descendantGroupIds(id){const ids=[id];model.groups.filter(g=>g.parentGroupId===id).forEach(g=>ids.push(...descendantGroupIds(g.id)));return ids}
  function arrangeGroup(mode){if(selected?.kind!=='group')return;const g=model.groups.find(x=>x.id===selected.id),nodes=model.elements.filter(n=>!n.parentId&&n.groupId===g.id);if(!g||!nodes.length)return;const cols=mode==='vertical'?1:mode==='horizontal'?nodes.length:Math.max(1,Math.ceil(Math.sqrt(nodes.length))),rows=Math.ceil(nodes.length/cols),cw=Math.max(...nodes.map(n=>nodeSize(n).w))+44,ch=Math.max(...nodes.map(n=>nodeSize(n).h))+56;g.w=Math.max(g.w,cols*cw+32);g.h=Math.max(g.h,rows*ch+48);nodes.forEach((n,i)=>{n.visual.x=g.x+16+cw*(i%cols+.5);n.visual.y=g.y+40+ch*(Math.floor(i/cols)+.5)});render();save()}
  function renderNodes(){els.nodes.innerHTML=[...model.elements].sort((a,b)=>nodeDepth(a)-nodeDepth(b)).map(n=>{const t=TYPES.find(t=>t[0]===n.type)||TYPES.at(-1),p=nodePosition(n),size=nodeSize(n),children=childrenOf(n.id);return `<article class="node ${selected?.kind==='node'&&selected.id===n.id?'selected':''} ${n.parentId?'is-child':''} ${children.length?'has-children':''}" data-id="${n.id}" style="left:${p.x}px;top:${p.y}px;width:${size.w}px;height:${size.h}px;min-height:0;--node-header-height:${size.ownH||54}px;--type-color:${t[3]}" tabindex="0" aria-label="${esc(n.label)}"><strong class="node-label">${wrapLabel(n.label,size.w-24).map(esc).join("<br>")}</strong></article>`}).join('');
    $$('.node').forEach(n=>{n.onpointermove=showConnectionTool;n.onpointerleave=()=>{};n.onpointerdown=e=>startNodeInteraction(e,n.dataset.id);n.onclick=e=>{e.stopPropagation();if(!pending)select({kind:'node',id:n.dataset.id})}});
  }
  function updateNodePositions(){$$('.node').forEach(el=>{const n=model.elements.find(x=>x.id===el.dataset.id);if(!n)return;const p=nodePosition(n);el.style.left=`${p.x}px`;el.style.top=`${p.y}px`})}
  function renderGroups(){els.groups.innerHTML=model.groups.map(g=>`<div class="group ${selected?.kind==='group'&&selected.id===g.id?'selected':''}" data-id="${g.id}" data-kind="${g.kind||'level'}" style="left:${g.x}px;top:${g.y}px;width:${g.w}px;height:${g.h}px"><span>${esc(g.label)}</span><button class="group-resize-handle" type="button" aria-label="Bereichsgröße ändern"></button></div>`).join('');$$('.group').forEach(el=>{el.onpointerdown=e=>{if(e.target.classList.contains('group-resize-handle'))return;selected={kind:'group',id:el.dataset.id};$$('.group').forEach(g=>g.classList.toggle('selected',g===el));renderInspector();renderEdges();const g=model.groups.find(g=>g.id===el.dataset.id),p=point(e);drag={kind:'group',id:g.id,dx:p.x-g.x,dy:p.y-g.y,lastX:g.x,lastY:g.y};el.setPointerCapture(e.pointerId)};el.querySelector('.group-resize-handle').onpointerdown=e=>{e.preventDefault();e.stopPropagation();const g=model.groups.find(g=>g.id===el.dataset.id);selected={kind:'group',id:g.id};drag={kind:'group-resize',id:g.id};e.currentTarget.setPointerCapture(e.pointerId)};el.onclick=e=>{e.stopPropagation();select({kind:'group',id:el.dataset.id})}})}
  function updateGroupPositions(){$$('.group').forEach(el=>{const g=model.groups.find(x=>x.id===el.dataset.id);if(!g)return;el.style.left=`${g.x}px`;el.style.top=`${g.y}px`;el.style.width=`${g.w}px`;el.style.height=`${g.h}px`})}
  function segmentHits(a,b,rect){if(a.x===b.x)return a.x>=rect.l&&a.x<=rect.r&&Math.max(a.y,b.y)>=rect.t&&Math.min(a.y,b.y)<=rect.b;return a.y>=rect.t&&a.y<=rect.b&&Math.max(a.x,b.x)>=rect.l&&Math.min(a.x,b.x)<=rect.r}
  function routeScore(points,obstacles){let hits=0;for(let i=1;i<points.length;i++)obstacles.forEach(r=>{if(segmentHits(points[i-1],points[i],r))hits++});const length=points.slice(1).reduce((sum,p,i)=>sum+Math.abs(p.x-points[i].x)+Math.abs(p.y-points[i].y),0);return hits*100000+length}
  function routeRelation(r){const s=model.elements.find(n=>n.id===r.source),t=model.elements.find(n=>n.id===r.target);if(!s||!t)return[];const ports=relationPorts(r),obstacles=model.elements.filter(n=>n!==s&&n!==t&&!isDescendant(s.id,n.id)&&!isDescendant(t.id,n.id)).map(n=>nodeBox(n));if(r.visual?.manualRoute){if(r.visual.freeRoute){const p=r.visual.manualRoute.map(v=>({...v}));p[0]=DiagramGeometry.anchor(nodeBox(s),ports.source);p[p.length-1]=DiagramGeometry.anchor(nodeBox(t),ports.target);return p}const manual=DiagramGeometry.attachRoute(r.visual.manualRoute,DiagramGeometry.anchor(nodeBox(s),ports.source),DiagramGeometry.anchor(nodeBox(t),ports.target));if(manual)return manual}const result=DiagramGeometry.route(nodeBox(s),nodeBox(t),ports.source,ports.target,obstacles);return result.points}
  function pointOnRoute(points,t){const lengths=points.slice(1).map((p,i)=>Math.hypot(p.x-points[i].x,p.y-points[i].y)),total=lengths.reduce((a,b)=>a+b,0);let target=total*t;for(let i=0;i<lengths.length;i++){if(target<=lengths[i]){const a=points[i],b=points[i+1],f=lengths[i]?target/lengths[i]:0;return{x:a.x+(b.x-a.x)*f,y:a.y+(b.y-a.y)*f}}target-=lengths[i]}return points.at(-1)}
  function renderEdges(){const curves=model.relations.map(r=>{const points=routeRelation(r);if(!points.length)return'';const path=points.map((p,i)=>`${i?'L':'M'} ${p.x} ${p.y}`).join(' '),label=pointOnRoute(points,r.visual?.labelPosition??.5),sel=selected?.kind==='edge'&&selected.id===r.id;return `<path class="edge-hit" data-id="${r.id}" d="${path}"/><path class="edge-path ${sel?'edge-selected':''}" d="${path}"/><text class="edge-label" data-id="${r.id}" x="${label.x}" y="${label.y-7}" text-anchor="middle">${esc(r.type)}</text>${r.properties?.source?.trim()?`<text class="edge-source-mark" data-id="${r.id}" x="${label.x}" y="${label.y-23}" text-anchor="middle">§</text>`:''}`}).join('');const draft=pending?`<path class="drag-line" d="M ${pending.startX} ${pending.startY} L ${pending.x} ${pending.y}"/>`:'';els.edges.innerHTML=curves+draft;renderEndpointHandles();$$('.edge-hit').forEach(p=>p.onclick=e=>{e.stopPropagation();select({kind:'edge',id:p.dataset.id})});$$('.edge-label').forEach(label=>label.onpointerdown=e=>{e.preventDefault();e.stopPropagation();const r=model.relations.find(x=>x.id===label.dataset.id);selected={kind:'edge',id:r.id};drag={kind:'edge-label',id:r.id,startX:e.clientX,start:r.visual?.labelPosition??.5};els.canvas.setPointerCapture(e.pointerId);renderEndpointHandles();renderInspector()})}
  function select(s){selected=s;render()}
  function isDescendant(candidateId,parentId){let current=model.elements.find(n=>n.id===candidateId);while(current?.parentId){if(current.parentId===parentId)return true;current=model.elements.find(n=>n.id===current.parentId)}return false}
  function renderInspector(){syncPrecisionInspector();const forms=[els.paletteInfo,els.nodeForm,els.edgeForm,els.groupForm];forms.forEach(f=>f.hidden=true);$$('.palette-item').forEach(b=>b.classList.toggle('is-selected',selected?.kind==='palette'&&selected.id===b.dataset.type));$('#inspectorEmpty').hidden=!!selected;if(!selected)return;if(selected.kind==='palette'){const type=TYPES.find(t=>t[0]===selected.id),info=TYPE_INFO[selected.id];if(!type||!info){selected=null;return renderInspector()}els.paletteInfo.hidden=false;$('#inspectorTitle').textContent='Elementtyp';$('#paletteInfoTitle').textContent=type[1];$('#paletteInfoDescription').textContent=info[0];$('#paletteInfoGuidance').textContent=info[1];$('#paletteInfoExamples').textContent=info[2];return}const obj=getSelected();if(!obj){selected=null;return renderInspector()}const form=selected.kind==='node'?els.nodeForm:selected.kind==='edge'?els.edgeForm:els.groupForm;form.hidden=false;$('#inspectorTitle').textContent=selected.kind==='node'?'Element':selected.kind==='edge'?'Beziehung':'Institutioneller Bereich';if(selected.kind==='node'){form.elements.label.value=obj.label;form.elements.type.value=obj.type;const parents=model.elements.filter(n=>n.id!==obj.id&&!isDescendant(n.id,obj.id));form.elements.parentId.innerHTML='<option value="">Keinem Element</option>'+parents.map(n=>`<option value="${n.id}">${esc(n.label)}</option>`).join('');form.elements.parentId.value=obj.parentId||'';form.elements.groupId.innerHTML='<option value="">Keinem Bereich</option>'+model.groups.map(g=>`<option value="${g.id}">${esc(g.label)}</option>`).join('');form.elements.groupId.value=obj.groupId||'';['level','branch','term','members','structure'].forEach(k=>form.elements[k].value=obj.properties[k]||'');form.elements.independent.checked=!!obj.properties.independent}else if(selected.kind==='edge'){form.elements.relation.value=obj.type;form.elements.labelPosition.value=obj.visual?.labelPosition??.5;form.elements.source.value=obj.properties?.source||'';['decision','majority','conditions','source'].forEach(k=>form.elements[k].value=obj.properties[k]||'');const s=model.elements.find(n=>n.id===obj.source),t=model.elements.find(n=>n.id===obj.target);$('#edgeStatement').textContent=`${s?.label} → ${obj.type} → ${t?.label}`}else{form.elements.label.value=obj.label;form.elements.kind.value=obj.kind||'level';const blocked=descendantGroupIds(obj.id);form.elements.parentGroupId.innerHTML='<option value="">Keinen übergeordneten Bereich</option>'+model.groups.filter(g=>!blocked.includes(g.id)).map(g=>`<option value="${g.id}">${esc(g.label)}</option>`).join('');form.elements.parentGroupId.value=obj.parentGroupId||''}}
  function updateFromInspector(e){if(!selected)return;const obj=getSelected(),name=e.target.name;if(selected.kind==='node'){if(name==='label'||name==='type'||name==='parentId'||name==='groupId')obj[name]=e.target.value;else obj.properties[name]=e.target.type==='checkbox'?e.target.checked:e.target.value}else if(selected.kind==='edge'){if(name==='relation')obj.type=e.target.value;else if(name==='labelPosition'){obj.visual=obj.visual||{};obj.visual.labelPosition=Number(e.target.value)}else obj.properties[name]=e.target.value}else if(name==='kind'||name==='parentGroupId')obj[name]=e.target.value;else obj.label=e.target.value;renderNodes();renderGroups();renderEdges();renderInspector();save()}
  function getSelected(){return selected?.kind==='node'?model.elements.find(x=>x.id===selected.id):selected?.kind==='edge'?model.relations.find(x=>x.id===selected.id):model.groups.find(x=>x.id===selected.id)}
  function removeSelected(){if(!selected||selected.kind==='palette')return;if(selected.kind==='node'){model.elements.filter(x=>x.parentId===selected.id).forEach(x=>{const p=nodePosition(x);x.visual.x=p.x;x.visual.y=p.y;x.parentId=''});model.elements=model.elements.filter(x=>x.id!==selected.id);model.relations=model.relations.filter(x=>x.source!==selected.id&&x.target!==selected.id)}else if(selected.kind==='edge')model.relations=model.relations.filter(x=>x.id!==selected.id);else{model.elements.forEach(x=>{if(x.groupId===selected.id)x.groupId=''});model.groups.forEach(x=>{if(x.parentGroupId===selected.id)x.parentGroupId=''});model.groups=model.groups.filter(x=>x.id!==selected.id)}selected=null;render();save()}
  function setMode(mode,persist=true){model.mode=mode;$$('.mode-switch button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$$('.advanced-fields').forEach(x=>x.hidden=mode!=='advanced');if(persist)save()}
  function toggleDiagramView(){const active=document.body.classList.toggle('diagram-mode');$('#viewButton').textContent=active?'Bearbeiten':'Diagramm';$('#diagramTitle').hidden=true;if(active){pending=null;selected=null;$('#diagramPreview').innerHTML=buildExportSvg();$('#diagramPreview').hidden=false;els.viewport.hidden=true;els.empty.hidden=true}else{$('#diagramPreview').hidden=true;els.viewport.hidden=false;render()}}
  function exportWarnings(){const warnings=[];if(!model.elements.length)warnings.push('Das Modell enthält noch keine Elemente.');const unnamed=model.elements.filter(n=>!n.label.trim()).length;if(unnamed)warnings.push(unnamed+' Elemente sind nicht benannt.');const boxes=model.elements.map(nodeBox),outside=boxes.filter(b=>b.l<0||b.t<0||b.r>4000||b.b>3000).length;if(outside)warnings.push(outside+' Elemente liegen teilweise außerhalb der Modellfläche; der Export schließt sie ein.');let conflicts=0;for(const r of model.relations){const points=routeRelation(r),obstacles=model.elements.filter(n=>n.id!==r.source&&n.id!==r.target&&!isDescendant(r.source,n.id)&&!isDescendant(r.target,n.id)).map(nodeBox);if(points.slice(1).some((p,i)=>DiagramGeometry.blocked(points[i],p,obstacles)))conflicts++}if(conflicts)warnings.push(conflicts+' Verbindungen durchqueren noch ein Element. Verschiebe das Element oder ändere den Pfeilanschluss.');let overlaps=0;for(let i=0;i<model.elements.length;i++)for(let j=i+1;j<model.elements.length;j++){const a=model.elements[i],b=model.elements[j],x=boxes[i],y=boxes[j];if(!isDescendant(a.id,b.id)&&!isDescendant(b.id,a.id)&&x.l<y.r&&x.r>y.l&&x.t<y.b&&x.b>y.t)overlaps++}if(overlaps)warnings.push(overlaps+' Elementpaare überlappen sich.');if($('#exportPaper').value!=='auto'){const b=exportBounds(),paper=$('#exportPaper').value==='a3'?[273,396]:[186,273];if($('#exportOrientation').value==='landscape')paper.reverse();const pt=13*Math.min(paper[0]/(b.r-b.l),paper[1]/(b.b-b.t+54))*72/25.4;if(pt<8)warnings.push('Die kleinste Schrift wird beim Einpassen etwa '+pt.toFixed(1)+' pt groß. Größeres Papier oder SVG verwenden.')}return warnings}
  function openExport(){const warnings=exportWarnings(),box=$('#exportValidation');box.classList.toggle('has-warnings',warnings.length>0);box.textContent=warnings.length?warnings.join(' '):'Das Modell ist für den Export bereit.';$('#exportDialog').showModal()}
  function exportBounds(){const boxes=model.elements.map(nodeBox);model.groups.forEach(g=>boxes.push({l:g.x,t:g.y-24,r:g.x+g.w,b:g.y+g.h}));model.relations.forEach(r=>{const pts=routeRelation(r);pts.forEach(p=>boxes.push({l:p.x-12,t:p.y-12,r:p.x+12,b:p.y+12}));if(pts.length){const p=pointOnRoute(pts,r.visual?.labelPosition??.5),half=r.type.length*3.8;boxes.push({l:p.x-half,t:p.y-24,r:p.x+half,b:p.y+5})}});if(!boxes.length)return{l:0,t:0,r:800,b:600};return{l:Math.min(...boxes.map(b=>b.l))-36,t:Math.min(...boxes.map(b=>b.t))-36,r:Math.max(...boxes.map(b=>b.r))+36,b:Math.max(...boxes.map(b=>b.b))+36}}
  function buildExportSvg(){const b=exportBounds(),title=$('#exportTitle').checked,top=b.t-(title?54:0),w=b.r-b.l,h=b.b-top,paper=$('#exportPaper').value,landscape=$('#exportOrientation').value==='landscape',mm=paper==='a3'?[297,420]:[210,297],size=landscape?mm.reverse():mm,color=$('#exportTheme').value==='color',attrs=paper==='auto'?'width="'+Math.ceil(w)+'" height="'+Math.ceil(h)+'"':'width="'+size[0]+'mm" height="'+size[1]+'mm"';const groups=model.groups.map(g=>{const line=g.kind==='level'?'<path d="M '+g.x+' '+g.y+' H '+(g.x+g.w)+'" stroke-dasharray="3 4"/>':g.kind==='branch'?'':'<rect x="'+g.x+'" y="'+g.y+'" width="'+g.w+'" height="'+g.h+'" fill="none"/>';return line+'<text x="'+(g.x+12)+'" y="'+(g.y-9)+'" font-size="16" font-weight="700" stroke="none">'+esc(g.label)+'</text>'}).join('');const nodes=[...model.elements].sort((a,b)=>nodeDepth(a)-nodeDepth(b)).map(n=>{const p=nodePosition(n),z=nodeSize(n),t=TYPES.find(x=>x[0]===n.type),lines=wrapLabel(n.label,z.w-24);return '<rect x="'+(p.x-z.w/2)+'" y="'+(p.y-z.h/2)+'" width="'+z.w+'" height="'+z.h+'" rx="3" fill="white" stroke="'+(color?t[3]:'#213633')+'"/><text font-size="16" font-weight="700" text-anchor="middle" stroke="none">'+lines.map((line,i)=>'<tspan x="'+p.x+'" y="'+(p.y-z.h/2+z.ownH/2-(lines.length-1)*19/2+5.5+i*19)+'">'+esc(line)+'</tspan>').join('')+'</text>'}).join('');const edges=model.relations.map(r=>{const pts=routeRelation(r);if(!pts.length)return'';const d=pts.map((p,i)=>(i?'L':'M')+' '+p.x+' '+p.y).join(' '),p=pointOnRoute(pts,r.visual?.labelPosition??.5);return '<path d="'+d+'" fill="none" marker-end="url(#arrowExport)"/><text x="'+p.x+'" y="'+(p.y-7)+'" text-anchor="middle" font-size="13" font-weight="600" paint-order="stroke" stroke="white" stroke-width="5">'+esc(r.type)+'</text>'+(r.properties?.source?.trim()?'<text x="'+p.x+'" y="'+(p.y-23)+'" text-anchor="middle" font-size="12" font-weight="700" stroke="none">§</text>':'')}).join('');return '<svg xmlns="http://www.w3.org/2000/svg" '+attrs+' viewBox="'+b.l+' '+top+' '+w+' '+h+'" font-family="Arial, Helvetica, sans-serif" fill="#213633" stroke="#213633" stroke-width="1.5"><defs><marker id="arrowExport" markerWidth="10" markerHeight="10" refX="9" refY="3" orient="auto"><path d="M0 0 L9 3 L0 6" fill="none"/></marker></defs><rect x="'+b.l+'" y="'+top+'" width="'+w+'" height="'+h+'" fill="white" stroke="none"/>'+groups+nodes+edges+(title?'<text x="'+((b.l+b.r)/2)+'" y="'+(top+32)+'" font-size="'+Math.min(28,(w-24)/(Math.max(1,model.title.length)*.62))+'" font-weight="700" text-anchor="middle" stroke="none">'+esc(model.title)+'</text>':'')+'</svg>'}
  function exportSvg(){const svg=buildExportSvg(),blob=new Blob([svg],{type:'image/svg+xml'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(model.title||'staatsmodell').toLowerCase().replace(/[^a-z0-9äöüß]+/gi,'-')+'.svg';a.click();URL.revokeObjectURL(a.href)}
  function printPdf(){const svg=buildExportSvg(),paper=$('#exportPaper').value==='a3'?'A3':'A4',orientation=$('#exportOrientation').value,win=window.open('','_blank');if(!win){alert('Das Druckfenster wurde vom Browser blockiert.');return}win.document.write(`<!doctype html><html><head><title>${esc(model.title)}</title><style>@page{size:${paper} ${orientation};margin:12mm}html,body{margin:0;height:100%}body{display:grid;place-items:center}svg{max-width:100%;max-height:100%;width:100%;height:100%}</style></head><body>${svg}<script>onload=()=>setTimeout(()=>print(),150)<\/script></body></html>`);win.document.close()}
  function exportModel(){const blob=new Blob([JSON.stringify(model,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(model.title||'staatsmodell').toLowerCase().replace(/[^a-z0-9äöüß]+/gi,'-')+'.staatsmodell.json';a.click();URL.revokeObjectURL(a.href)}
  function importModel(e){const file=e.target.files[0];if(!file)return;file.text().then(text=>{const data=validateModel(JSON.parse(text));model=data;selected=null;pending=null;$('#modelTitle').value=model.title;setMode(model.mode,false);setZoom(model.view?.zoom||1,false);render();save()}).catch(error=>alert('Import nicht möglich: '+error.message));e.target.value=''}
  function fit(){const b=exportBounds(),w=els.canvas.clientWidth,h=els.canvas.clientHeight;model.view=model.view||{};model.view.zoom=Math.max(.1,Math.min(1.6,Math.min(w/(b.r-b.l),h/(b.b-b.t))));model.view.panX=w/2-(b.l+b.r)/2*model.view.zoom;model.view.panY=h/2-(b.t+b.b)/2*model.view.zoom;applyView()}
  function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}

  // One geometry model drives hit testing, display and exported output.
  function wrapLabel(text,width){const max=Math.max(8,Math.floor(width/8)),lines=[];for(const paragraph of String(text||'').split('\n')){let line='';for(const word of paragraph.split(/\s+/)){if(line&&line.length+word.length+1>max){lines.push(line);line=''}for(let i=0;i<word.length;i+=max){const part=word.slice(i,i+max);if(i){lines.push(line);line=''}line+=(line?' ':'')+part}}lines.push(line)}return lines}
  function nodeDepth(n){let depth=0;while(n?.parentId&&depth<50){depth++;n=model.elements.find(x=>x.id===n.parentId)}return depth}
  function nodeBox(n){const p=nodePosition(n),size=nodeSize(n);return{l:p.x-size.w/2,r:p.x+size.w/2,t:p.y-size.h/2,b:p.y+size.h/2}}
  function relationPorts(r){const s=model.elements.find(n=>n.id===r.source),t=model.elements.find(n=>n.id===r.target),a=nodePosition(s),b=nodePosition(t),horizontal=Math.abs(a.x-b.x)>Math.abs(a.y-b.y);const result={source:r.visual?.sourcePort||{side:horizontal?(a.x<b.x?'right':'left'):(a.y<b.y?'bottom':'top'),t:.5},target:r.visual?.targetPort||{side:horizontal?(a.x<b.x?'left':'right'):(a.y<b.y?'top':'bottom'),t:.5}};return{source:DiagramGeometry.snapPort(nodeBox(s),result.source),target:DiagramGeometry.snapPort(nodeBox(t),result.target)}}
  function renderEndpointHandles(){const layer=$('#endpointLayer');if(!layer)return;layer.innerHTML='';const r=selected?.kind==='edge'?model.relations.find(x=>x.id===selected.id):null;const ids=r?[r.source,r.target]:pending?model.elements.map(n=>n.id):hoverNodeId?[hoverNodeId]:[];layer.innerHTML=model.elements.filter(n=>ids.includes(n.id)).map(n=>'<g class="port-markers active" data-node="'+n.id+'">'+DiagramGeometry.ports(nodeBox(n)).map(port=>{const p=DiagramGeometry.anchor(nodeBox(n),port);return '<circle class="port-marker '+(hoverPort?.id===n.id&&hoverPort.port.side===port.side&&hoverPort.port.t===port.t?'is-hot':'')+'" data-side="'+port.side+'" data-t="'+port.t+'" cx="'+p.x+'" cy="'+p.y+'" r="'+(5/currentZoom())+'"/>'}).join('')+'</g>').join('');layer.querySelectorAll('.port-marker').forEach(el=>{el.onpointerdown=e=>{if(e.button!==0)return;const group=el.closest('.port-markers');startConnect(e,group.dataset.node,{side:el.dataset.side,t:Number(el.dataset.t)})}});if(!r)return;const points=routeRelation(r),ports=relationPorts(r);layer.innerHTML+=points.slice(1).map((p,i)=>{const a=points[i],horizontal=Math.abs(a.y-p.y)<.001;return '<line class="segment-handle" data-index="'+i+'" x1="'+a.x+'" y1="'+a.y+'" x2="'+p.x+'" y2="'+p.y+'" style="cursor:'+(horizontal?'ns-resize':'ew-resize')+'"><title>Abschnitt quer verschieben</title></line>'}).join('');layer.innerHTML+=points.slice(1,-1).map((p,i)=>'<circle class="corner-handle" data-index="'+(i+1)+'" cx="'+p.x+'" cy="'+p.y+'" r="'+(5/currentZoom())+'"><title>Ecke ziehen · Rechtsklick entfernt den Punkt</title></circle>').join('');layer.innerHTML+=['source','target'].map(end=>{const p=DiagramGeometry.anchor(nodeBox(model.elements.find(n=>n.id===r[end])),ports[end]);return '<circle class="endpoint-handle" data-end="'+end+'" cx="'+p.x+'" cy="'+p.y+'" r="'+(6/currentZoom())+'"><title>Am nächsten Rasterpunkt einrasten</title></circle>'}).join('');layer.querySelectorAll('.corner-handle').forEach(el=>{el.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();e.stopPropagation();drag={kind:'corner',id:r.id,index:Number(el.dataset.index),points};els.canvas.setPointerCapture(e.pointerId)};el.oncontextmenu=e=>{e.preventDefault();e.stopPropagation();r.visual=r.visual||{};r.visual.manualRoute=points.filter((_,i)=>i!==Number(el.dataset.index));r.visual.freeRoute=true;hoverPort=null;renderEdges();save()}});layer.querySelectorAll('.endpoint-handle').forEach(el=>el.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();e.stopPropagation();drag={kind:'endpoint',id:r.id,end:el.dataset.end};els.canvas.setPointerCapture(e.pointerId)});layer.querySelectorAll('.segment-handle').forEach(el=>el.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();e.stopPropagation();const index=Number(el.dataset.index),axis=Math.abs(points[index].y-points[index+1].y)<.001?'y':'x';drag={kind:'segment',id:r.id,index,points,start:point(e)[axis],axis};els.canvas.setPointerCapture(e.pointerId)})}
  function syncPrecisionInspector(){const panel=$('#precisionPanel');if(!panel)return;panel.hidden=selected?.kind!=='edge';if(selected?.kind==='edge'){const r=model.relations.find(x=>x.id===selected.id);if(r){const ports=relationPorts(r);for(const end of ['source','target']){$('#'+end+'Side').value=ports[end].side;$('#'+end+'Offset').value=Math.round(ports[end].t*100)}}}const n=selected?.kind==='node'?model.elements.find(x=>x.id===selected.id):null;$('#nodeWidthField').hidden=!n;if(n)$('#nodeWidth').value=n.visual.width||180}
  let undoStack=[],redoStack=[],savedSnapshot=null;
  function remember(){const next=JSON.stringify(model);if(savedSnapshot!==null&&next!==savedSnapshot){undoStack.push(savedSnapshot);if(undoStack.length>70)undoStack.shift();redoStack=[]}savedSnapshot=next;updateHistoryButtons()}
  function updateHistoryButtons(){if($('#undoButton')){$('#undoButton').disabled=!undoStack.length;$('#redoButton').disabled=!redoStack.length}}
  function historyStep(redo){const from=redo?redoStack:undoStack,to=redo?undoStack:redoStack;if(!from.length)return;to.push(JSON.stringify(model));model=JSON.parse(from.pop());savedSnapshot=JSON.stringify(model);selected=null;pending=null;drag=null;$('#modelTitle').value=model.title;setMode(model.mode,false);applyView();render();save()}
  function validateModel(data){if(data?.version!==1||!Array.isArray(data.elements)||!Array.isArray(data.relations))throw Error('Keine gültige Modelldatei.');const copy=JSON.parse(JSON.stringify(data));copy.groups=copy.groups||[];copy.view=copy.view||{};copy.title=String(copy.title||'Mein Staatsmodell');if(copy.elements.length>200||copy.relations.length>500)throw Error('Das Modell ist zu groß (maximal 200 Elemente / 500 Beziehungen).');const ids=new Set();for(const n of [...copy.elements,...copy.groups,...copy.relations]){if(typeof n.id!=='string'||!/^[\w-]+$/.test(n.id)||ids.has(n.id))throw Error('Ungültige oder doppelte Kennung.');ids.add(n.id)}const ni=new Set(copy.elements.map(n=>n.id)),gi=new Set(copy.groups.map(g=>g.id));for(const n of copy.elements){if(!TYPES.some(t=>t[0]===n.type))throw Error('Unbekannter Elementtyp.');n.label=String(n.label||'');n.properties=n.properties||{};n.visual=n.visual||{};if(!Number.isFinite(n.visual.x)||!Number.isFinite(n.visual.y))throw Error('Ungültige Elementposition.');if(n.parentId&&!ni.has(n.parentId))throw Error('Übergeordnetes Element fehlt.');if(n.groupId&&!gi.has(n.groupId))n.groupId=''}for(const g of copy.groups){if(!['x','y','w','h'].every(k=>Number.isFinite(g[k]))||g.w<1||g.h<1)throw Error('Ungültige Bereichsgröße.');if(g.parentGroupId&&!gi.has(g.parentGroupId))throw Error('Übergeordneter Bereich fehlt.')}for(const [items,key] of [[copy.elements,'parentId'],[copy.groups,'parentGroupId']]){for(const item of items){const seen=new Set([item.id]);let p=item[key];while(p){if(seen.has(p))throw Error('Kreisförmige Verschachtelung.');seen.add(p);p=items.find(n=>n.id===p)?.[key]}}}for(const r of copy.relations){if(!ni.has(r.source)||!ni.has(r.target)||r.source===r.target||!Object.values(RELATIONS).flat().includes(r.type))throw Error('Ungültige Beziehung.');r.visual=r.visual||{};if(r.visual.manualRoute&&(!Array.isArray(r.visual.manualRoute)||r.visual.manualRoute.length<2||r.visual.manualRoute.length>200||r.visual.manualRoute.some((p,i,a)=>!Number.isFinite(p.x)||!Number.isFinite(p.y))))throw Error('Ungültiger manueller Pfeilverlauf.');r.properties=r.properties||{};for(const end of ['sourcePort','targetPort']){const p=r.visual[end];if(p&&(!['left','right','top','bottom'].includes(p.side)||!Number.isFinite(p.t)||p.t<0||p.t>1))throw Error('Ungültiger Pfeilanschluss.')}}return copy}
  function createFramework(){if((model.elements.length||model.groups.length)&&!confirm('Das aktuelle Modell durch eine leere Ebenenstruktur ersetzen? Vorher bei Bedarf exportieren.'))return;model=blank();model.title='Staatsaufbau';for(let row=0;row<3;row++){const id=uid('group');model.groups.push({id,label:['Zentralstaat','Gliedstaaten / Regionen','Kommunale Ebene'][row],kind:'level',x:70,y:80+row*440,w:960,h:410});for(let col=0;col<3;col++)model.groups.push({id:uid('group'),parentGroupId:id,label:['Legislative','Exekutive','Judikative'][col],kind:'branch',x:90+col*310,y:135+row*440,w:280,h:320})}selected=null;$('#modelTitle').value=model.title;render();fit();save()}
  let hoverPort=null,hoverNodeId=null;
  function findHoverPort(p){let best=null;for(const n of model.elements){const box=nodeBox(n),port=DiagramGeometry.snapPort(box,DiagramGeometry.nearestPort(box,p)),at=DiagramGeometry.anchor(box,port),distance=Math.hypot(at.x-p.x,at.y-p.y);if(distance<16/currentZoom()&&(!best||distance<best.distance))best={id:n.id,port,point:at,distance}}return best}
  function setupEnhancements(){
    const toolbar=$('.canvas-toolbar'),tools=document.createElement('div');tools.className='history-tools';tools.innerHTML='<button id="undoButton" class="quiet" title="Rückgängig (Strg+Z)" aria-label="Rückgängig">↶</button><button id="redoButton" class="quiet" title="Wiederholen (Strg+Y)" aria-label="Wiederholen">↷</button>';toolbar.prepend(tools);
    $('#undoButton').onclick=()=>historyStep(false);$('#redoButton').onclick=()=>historyStep(true);
    const framework=document.createElement('button');framework.id='frameworkButton';framework.className='secondary wide';framework.textContent='Ebenenstruktur vorbereiten';framework.onclick=createFramework;$('.palette').append(framework);
    $('.palette .hint').textContent='Klicken zum Kennenlernen. Auf die Fläche ziehen zum Platzieren.';
    $('#connectionHint').hidden=true;
    const preview=document.createElement('div');preview.id='diagramPreview';preview.hidden=true;els.canvas.append(preview);
    const overlay=document.createElementNS('http://www.w3.org/2000/svg','svg');overlay.id='endpointOverlay';overlay.innerHTML='<g id="endpointLayer"></g>';els.viewport.append(overlay);
    const precision=document.createElement('section');precision.id='precisionPanel';precision.hidden=true;precision.innerHTML='<h3>Pfeilanschlüsse</h3><p>Griffpunkte rasten im 20er-Raster ein. Jeden Linienabschnitt quer ziehen, um den Verlauf zu ordnen.</p>'+['source','target'].map(end=>'<label>'+ (end==='source'?'Startpunkt':'Pfeilspitze')+'<select id="'+end+'Side"><option value="top">Oben</option><option value="right">Rechts</option><option value="bottom">Unten</option><option value="left">Links</option></select><input id="'+end+'Offset" aria-label="Position in Prozent" type="range" min="2" max="98" step="1"></label>').join('');els.edgeForm.prepend(precision);const reset=document.createElement('button');reset.type='button';reset.className='secondary';reset.textContent='Pfeilverlauf automatisch ordnen';reset.onclick=()=>{const r=getSelected();if(selected?.kind!=='edge')return;delete r.visual.manualRoute;renderEdges();save()};precision.append(reset);
    for(const end of ['source','target'])for(const control of ['Side','Offset'])$('#'+end+control).oninput=e=>{e.stopPropagation();if(selected?.kind!=='edge')return;const r=model.relations.find(x=>x.id===selected.id);r.visual=r.visual||{};r.visual[end+'Port']=DiagramGeometry.snapPort(nodeBox(model.elements.find(n=>n.id===r[end])),{side:$('#'+end+'Side').value,t:Number($('#'+end+'Offset').value)/100});renderEdges();save()};
    const width=document.createElement('label');width.id='nodeWidthField';width.innerHTML='Breite des Elements<input id="nodeWidth" type="range" min="150" max="700" step="10">';els.nodeForm.insertBefore(width,els.nodeForm.querySelector('.advanced-fields'));$('#nodeWidth').oninput=e=>{e.stopPropagation();const n=getSelected();if(selected?.kind!=='node')return;n.visual.width=Number(e.target.value);renderNodes();renderEdges();save()};
    els.canvas.addEventListener('pointerdown',e=>{if(document.body.classList.contains('diagram-mode')&&e.button!==1){e.stopImmediatePropagation();return}if(e.button===0&&!(e.target.closest('.node,.group,.edge-label,.edge-hit,.endpoint-handle,.segment-handle,.corner-handle,.port-marker'))){pending=null;selected=null;render()}},true);
    // Capture stays on the canvas even when SVG handles are redrawn during a drag.
    document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select')||document.querySelector('dialog[open]'))return;if((e.ctrlKey||e.metaKey)&&['z','y'].includes(e.key.toLowerCase())){e.preventDefault();historyStep(e.key.toLowerCase()==='y'||e.shiftKey)}});
    $('#relationDialog').addEventListener('close',()=>{pending=null;renderEdges()});
    for(const id of ['exportTheme','exportTitle','exportPaper','exportOrientation'])$('#'+id).addEventListener('change',()=>{const warnings=exportWarnings(),box=$('#exportValidation');box.classList.toggle('has-warnings',warnings.length>0);box.textContent=warnings.length?warnings.join(' '):'Das Modell ist für den Export bereit.';if(document.body.classList.contains('diagram-mode'))$('#diagramPreview').innerHTML=buildExportSvg()});
    remember();syncPrecisionInspector();
  }

  TYPES.push(['constitution','Verfassung / Grundordnung','§','#65736e']);
  TYPE_INFO.constitution=['Eine Verfassung oder Grundordnung legt fest, wie staatliche Herrschaft organisiert und begrenzt wird. Sie ist eine Rechtsgrundlage, kein handelndes Organ.','Verbinde die Grundordnung etwa mit „begründet Kompetenzen von“. Wer ihre Einhaltung kontrolliert, wird durch eine eigene Beziehung zum zuständigen Gericht dargestellt.','Verfassung, Grundgesetz, historische Grundordnung'];
  RELATIONS['Rechtliche Grundlagen']=['begründet Kompetenzen von','bindet','prüft Vereinbarkeit mit'];
  init();
  setupEnhancements();
})();
