window.TypeMapDocumentStyles = (() => {
  const fonts = {
    modern: "'CMU Serif', 'Computer Modern Serif', Georgia, serif",
    garamond: "'EB Garamond', Georgia, serif",
    sans: "'Source Sans 3', Arial, sans-serif",
    code: "'Source Code Pro', 'Courier New', monospace",
  };

  const styles = {
    paper: {
      label: "Paper",
      purpose: "akademisches Paper / LaTeX-Clon / wissenschaftlicher Aufsatz",
      style: {
        fontFamily: fonts.modern,
        fontSize: 16,
        lineHeight: 1.3,
        measure: 64,
        textAlign: "justify",
        hyphenation: "auto",
        language: "de",
        ligatures: true,
        titleFontFamily: fonts.modern,
        subtitleFontFamily: fonts.modern,
        metaFontFamily: fonts.modern,
        headingFontFamily: fonts.modern,
        quoteFontFamily: fonts.modern,
        codeFontFamily: fonts.code,
        paragraphSpacing: 0,
        firstLineIndent: true,
        quoteStyle: "regular",
      },
      headingScale: { 1: 1.63, 2: 1.12, 3: 1, 4: 0.94, 5: 0.9, 6: 0.86, 7: 0.82 },
      titleScale: { title: 1.63, subtitle: 1.08, authors: 0.72, titleLineHeight: 1.15, subtitleLineHeight: 1.25, authorsLineHeight: 1.25 },
    },
    article: {
      label: "Article",
      purpose: "journalistischer Artikel / Nachrichten- oder Magazinbeitrag",
      style: {
        fontFamily: fonts.garamond,
        fontSize: 16.5,
        lineHeight: 1.4,
        measure: 66,
        textAlign: "justify",
        hyphenation: "auto",
        language: "de",
        ligatures: true,
        titleFontFamily: fonts.sans,
        subtitleFontFamily: fonts.sans,
        metaFontFamily: fonts.sans,
        headingFontFamily: fonts.sans,
        quoteFontFamily: fonts.garamond,
        codeFontFamily: fonts.code,
        paragraphSpacing: 0.45,
        firstLineIndent: false,
        quoteStyle: "italic",
      },
      headingScale: { 1: 1.7, 2: 1.15, 3: 1, 4: 0.94, 5: 0.9, 6: 0.86, 7: 0.82 },
      titleScale: { title: 1.7, subtitle: 1.09, authors: 0.7, titleLineHeight: 1.1, subtitleLineHeight: 1.25, authorsLineHeight: 1.25 },
    },
    essay: {
      label: "Essay",
      purpose: "essayistischer / reflektierender Langtext",
      style: {
        fontFamily: fonts.garamond,
        fontSize: 17.25,
        lineHeight: 1.45,
        measure: 66,
        textAlign: "justify",
        hyphenation: "auto",
        language: "de",
        ligatures: true,
        titleFontFamily: fonts.garamond,
        subtitleFontFamily: fonts.garamond,
        metaFontFamily: fonts.sans,
        headingFontFamily: fonts.garamond,
        quoteFontFamily: fonts.garamond,
        codeFontFamily: fonts.code,
        paragraphSpacing: 0.55,
        firstLineIndent: false,
        quoteStyle: "italic",
      },
      headingScale: { 1: 1.68, 2: 1.22, 3: 1.05, 4: 0.98, 5: 0.92, 6: 0.88, 7: 0.84 },
      titleScale: { title: 1.68, subtitle: 1.1, authors: 0.67, titleLineHeight: 1.1, subtitleLineHeight: 1.25, authorsLineHeight: 1.25 },
    },
    feature: {
      label: "Feature",
      purpose: "längerer Magazinartikel / Reportage / Feuilleton",
      style: {
        fontFamily: fonts.garamond,
        fontSize: 17.25,
        lineHeight: 1.47,
        measure: 68,
        textAlign: "justify",
        hyphenation: "auto",
        language: "de",
        ligatures: true,
        titleFontFamily: fonts.sans,
        subtitleFontFamily: fonts.garamond,
        metaFontFamily: fonts.sans,
        headingFontFamily: fonts.sans,
        quoteFontFamily: fonts.garamond,
        codeFontFamily: fonts.code,
        paragraphSpacing: 0.55,
        firstLineIndent: false,
        quoteStyle: "italic",
      },
      headingScale: { 1: 1.91, 2: 1.22, 3: 1.05, 4: 0.98, 5: 0.92, 6: 0.88, 7: 0.84 },
      titleScale: { title: 1.91, subtitle: 1.19, authors: 0.67, titleLineHeight: 1.05, subtitleLineHeight: 1.25, authorsLineHeight: 1.25 },
    },
    report: {
      label: "Report",
      purpose: "sachlicher Bericht / Projektbericht / interne Dokumentation",
      style: {
        fontFamily: fonts.sans,
        fontSize: 15.5,
        lineHeight: 1.4,
        measure: 72,
        textAlign: "left",
        hyphenation: "none",
        language: "de",
        ligatures: true,
        titleFontFamily: fonts.sans,
        subtitleFontFamily: fonts.sans,
        metaFontFamily: fonts.sans,
        headingFontFamily: fonts.sans,
        quoteFontFamily: fonts.sans,
        codeFontFamily: fonts.code,
        paragraphSpacing: 0.5,
        firstLineIndent: false,
        quoteStyle: "italic",
      },
      headingScale: { 1: 1.68, 2: 1.23, 3: 1.06, 4: 1, 5: 0.94, 6: 0.9, 7: 0.86 },
      titleScale: { title: 1.68, subtitle: 1.1, authors: 0.74, titleLineHeight: 1.15, subtitleLineHeight: 1.25, authorsLineHeight: 1.25 },
    },
    technical: {
      label: "Technical",
      purpose: "technische Dokumentation / Spezifikation / Entwicklerdokument",
      style: {
        fontFamily: fonts.sans,
        fontSize: 15.5,
        lineHeight: 1.4,
        measure: 76,
        textAlign: "left",
        hyphenation: "none",
        language: "de",
        ligatures: true,
        titleFontFamily: fonts.sans,
        subtitleFontFamily: fonts.sans,
        metaFontFamily: fonts.sans,
        headingFontFamily: fonts.sans,
        quoteFontFamily: fonts.sans,
        codeFontFamily: fonts.code,
        paragraphSpacing: 0.55,
        firstLineIndent: false,
        quoteStyle: "regular",
      },
      headingScale: { 1: 1.68, 2: 1.23, 3: 1.06, 4: 1, 5: 0.94, 6: 0.9, 7: 0.86 },
      titleScale: { title: 1.68, subtitle: 1.1, authors: 0.74, titleLineHeight: 1.15, subtitleLineHeight: 1.25, authorsLineHeight: 1.25 },
    },
    notes: {
      label: "Notes",
      purpose: "Arbeitsnotizen / Wissensmanagement / Obsidian-artige Notizen",
      style: {
        fontFamily: fonts.sans,
        fontSize: 15.75,
        lineHeight: 1.45,
        measure: 76,
        textAlign: "left",
        hyphenation: "none",
        language: "de",
        ligatures: true,
        titleFontFamily: fonts.sans,
        subtitleFontFamily: fonts.sans,
        metaFontFamily: fonts.sans,
        headingFontFamily: fonts.sans,
        quoteFontFamily: fonts.sans,
        codeFontFamily: fonts.code,
        paragraphSpacing: 0.55,
        firstLineIndent: false,
        quoteStyle: "italic",
      },
      headingScale: { 1: 1.52, 2: 1.2, 3: 1.05, 4: 1, 5: 0.94, 6: 0.9, 7: 0.86 },
      titleScale: { title: 1.52, subtitle: 1.02, authors: 0.7, titleLineHeight: 1.15, subtitleLineHeight: 1.25, authorsLineHeight: 1.25 },
    },
    manuscript: {
      label: "Manuscript",
      purpose: "Rohfassung / literarisches Manuskript / längeres Schreiben",
      style: {
        fontFamily: fonts.garamond,
        fontSize: 17.75,
        lineHeight: 1.58,
        measure: 62,
        textAlign: "left",
        hyphenation: "none",
        language: "de",
        ligatures: true,
        titleFontFamily: fonts.garamond,
        subtitleFontFamily: fonts.garamond,
        metaFontFamily: fonts.sans,
        headingFontFamily: fonts.garamond,
        quoteFontFamily: fonts.garamond,
        codeFontFamily: fonts.code,
        paragraphSpacing: 0,
        firstLineIndent: true,
        quoteStyle: "italic",
      },
      headingScale: { 1: 1.52, 2: 1.18, 3: 1.05, 4: 1, 5: 0.94, 6: 0.9, 7: 0.86 },
      titleScale: { title: 1.52, subtitle: 0.96, authors: 0.65, titleLineHeight: 1.15, subtitleLineHeight: 1.25, authorsLineHeight: 1.25 },
    },
    code: {
      label: "Code",
      purpose: "code-lastiges Dokument / Snippets / Konfiguration / technische Skizzen",
      style: {
        fontFamily: fonts.code,
        fontSize: 14.25,
        lineHeight: 1.42,
        measure: 82,
        textAlign: "left",
        hyphenation: "none",
        language: "de",
        ligatures: true,
        titleFontFamily: fonts.sans,
        subtitleFontFamily: fonts.sans,
        metaFontFamily: fonts.sans,
        headingFontFamily: fonts.sans,
        quoteFontFamily: fonts.sans,
        codeFontFamily: fonts.code,
        paragraphSpacing: 0.4,
        firstLineIndent: false,
        quoteStyle: "regular",
      },
      headingScale: { 1: 1.68, 2: 1.34, 3: 1.12, 4: 1, 5: 0.94, 6: 0.9, 7: 0.86 },
      titleScale: { title: 1.68, subtitle: 1.12, authors: 0.77, titleLineHeight: 1.15, subtitleLineHeight: 1.25, authorsLineHeight: 1.25 },
    },
    letter: {
      label: "Letter",
      purpose: "Brief / Anschreiben / formelle Korrespondenz",
      style: {
        fontFamily: fonts.garamond,
        fontSize: 16.25,
        lineHeight: 1.4,
        measure: 64,
        textAlign: "left",
        hyphenation: "auto",
        language: "de",
        ligatures: true,
        titleFontFamily: fonts.sans,
        subtitleFontFamily: fonts.sans,
        metaFontFamily: fonts.sans,
        headingFontFamily: fonts.sans,
        quoteFontFamily: fonts.garamond,
        codeFontFamily: fonts.code,
        paragraphSpacing: 0.55,
        firstLineIndent: false,
        quoteStyle: "italic",
      },
      headingScale: { 1: 1.23, 2: 1, 3: 0.94, 4: 0.9, 5: 0.86, 6: 0.82, 7: 0.8 },
      titleScale: { title: 1.23, subtitle: 0.92, authors: 0.68, titleLineHeight: 1.2, subtitleLineHeight: 1.25, authorsLineHeight: 1.25 },
    },
    minimal: {
      label: "Minimal",
      purpose: "ablenkungsarmes Schreiben / universelle Rohfassung",
      style: {
        fontFamily: fonts.sans,
        fontSize: 17,
        lineHeight: 1.52,
        measure: 72,
        textAlign: "left",
        hyphenation: "none",
        language: "de",
        ligatures: true,
        titleFontFamily: fonts.sans,
        subtitleFontFamily: fonts.sans,
        metaFontFamily: fonts.sans,
        headingFontFamily: fonts.sans,
        quoteFontFamily: fonts.sans,
        codeFontFamily: fonts.code,
        paragraphSpacing: 0.65,
        firstLineIndent: false,
        quoteStyle: "italic",
      },
      headingScale: { 1: 1.41, 2: 1.12, 3: 1, 4: 0.94, 5: 0.9, 6: 0.86, 7: 0.82 },
      titleScale: { title: 1.41, subtitle: 0.94, authors: 0.65, titleLineHeight: 1.15, subtitleLineHeight: 1.25, authorsLineHeight: 1.25 },
    },
  };

  return {
    fonts,
    styles,
    order: ["paper", "article", "essay", "feature", "report", "technical", "notes", "manuscript", "code", "letter", "minimal"],
  };
})();
