window.TypeMapDocumentStyles = (() => {
  const fonts = {
    modern: "'CMU Serif', 'Computer Modern Serif', Georgia, serif",
    garamond: "'EB Garamond', Garamond, Georgia, serif",
    sans: "'Source Sans 3', Arial, sans-serif",
    code: "'Source Code Pro', 'Courier New', monospace",
  };

  const styles = {
    paper: {
      label: "Paper",
      purpose: "Akademisches Paper, LaTeX-Clon und wissenschaftlicher Aufsatz",
      style: {
        fontFamily: fonts.modern,
        fontSize: 16,
        lineHeight: 1.3,
        measure: 64,
        textAlign: "justify",
        hyphenation: "auto",
        language: "de",
        ligatures: true,
        titleFontFamily: fonts.modern,
        titleWeight: 400,
        subtitleFontFamily: fonts.modern,
        subtitleWeight: 400,
        metaFontFamily: fonts.modern,
        metaWeight: 400,
        headingFontFamily: fonts.modern,
        headingWeight: 700,
        headingSpacingBefore: 1.25,
        quoteFontFamily: fonts.modern,
        codeFontFamily: fonts.code,
        paragraphSpacing: 0,
        firstLineIndent: true,
        quoteStyle: "regular",
      },
      headingScale: { 1: 1.63, 2: 1.12, 3: 1, 4: 0.94, 5: 0.9, 6: 0.86, 7: 0.82 },
      titleScale: { title: 1.63, subtitle: 1.08, authors: 1, titleLineHeight: 1.15, subtitleLineHeight: 1.25, authorsLineHeight: 1.3 },
    },
    report: {
      label: "Artikel",
      purpose: "Redaktioneller Artikel, Essay und journalistischer Langtext",
      style: {
        fontFamily: fonts.garamond,
        fontSize: 15.5,
        lineHeight: 1.4,
        measure: 72,
        textAlign: "justify",
        hyphenation: "auto",
        language: "de",
        ligatures: true,
        titleFontFamily: fonts.sans,
        titleWeight: 700,
        subtitleFontFamily: fonts.sans,
        subtitleWeight: 400,
        metaFontFamily: fonts.sans,
        metaWeight: 400,
        headingFontFamily: fonts.sans,
        headingWeight: 700,
        headingSpacingBefore: 1.25,
        quoteFontFamily: fonts.garamond,
        codeFontFamily: fonts.code,
        paragraphSpacing: 0.5,
        firstLineIndent: false,
        quoteStyle: "italic",
      },
      headingScale: { 1: 1.68, 2: 1.23, 3: 1.06, 4: 1, 5: 0.94, 6: 0.9, 7: 0.86 },
      titleScale: { title: 1.68, subtitle: 1.1, authors: 0.74, titleLineHeight: 1.15, subtitleLineHeight: 1.25, authorsLineHeight: 1.25 },
    },
    notebook: {
      label: "Notebook",
      purpose: "Ablenkungsarmes Schreiben und universelle Rohfassung",
      style: {
        fontFamily: fonts.sans,
        fontSize: 17,
        lineHeight: 1.52,
        measure: 72,
        textAlign: "left",
        hyphenation: "none",
        language: "de",
        ligatures: true,
        titleFontFamily: fonts.sans,
        titleWeight: 600,
        subtitleFontFamily: fonts.sans,
        subtitleWeight: 400,
        metaFontFamily: fonts.sans,
        metaWeight: 400,
        headingFontFamily: fonts.sans,
        headingWeight: 600,
        headingSpacingBefore: 1.25,
        quoteFontFamily: fonts.sans,
        codeFontFamily: fonts.code,
        paragraphSpacing: 0.65,
        firstLineIndent: false,
        quoteStyle: "italic",
      },
      headingScale: { 1: 1.41, 2: 1.12, 3: 1, 4: 0.94, 5: 0.9, 6: 0.86, 7: 0.82 },
      titleScale: { title: 1.41, subtitle: 0.94, authors: 0.65, titleLineHeight: 1.15, subtitleLineHeight: 1.25, authorsLineHeight: 1.25 },
    },
  };

  return {
    fonts,
    styles,
    order: ["paper", "report", "notebook"],
  };
})();
